CS_SBOX_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Competitor_Info__c</fullName>
        <description>Added by MD on 09/05/2013 as part of the Phase 2 development</description>
        <label>Competitor Info</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitive_Spend__c</fullName>
        <description>Added by LM on 3/15/2013; New for SFDC rollout</description>
        <label>Competitive Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <label>Competitor Name</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gorkana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus/PRWeb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 9/4/2013 for Phase 2 rollout</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Expiration_Date__c</fullName>
        <label>Service Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Provided__c</fullName>
        <label>Service Provided</label>
        <picklist>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor_Info__c</fullName>
        <description>Created by LM on 9/3/2013 for Phase 2 rollout</description>
        <label>Competitor Info</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <description>Added by MD 09/13/2012. A Field to hold the name of the Competitor that the Sale was Lost to or Stolen from</description>
        <inlineHelpText>A Competitor Name must be selected when Closing an Opportunity and the Close Reason is &quot;Competitor&quot;</inlineHelpText>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/CompetitorHelper.cls
public with sharing class CompetitorHelper
{
	public Map<ID, Opportunity> oppsMap {get; Set;}
	public Map<ID, Account> accountsMap {get; Set;}
	private Map<ID, List<Competitor__c>> compOppsMap = new Map<ID, List<Competitor__c>>();
	private Map<ID, List<Competitor__c>> compAccountsMap = new Map<ID, List<Competitor__c>>();
	
	private Set<ID> accountIds = new Set<ID>();
	private Set<ID> opportunityIds = new Set<ID>();
	
	public CompetitorHelper(List<Competitor__c> comps)
	{
		for (Competitor__c comp : comps)
		{
			accountIds.add(comp.Account__c);
		
			if (comp.Opportunity__c != null)
			{
				opportunityIds.add(comp.Opportunity__c);
			}
		}
		
		// Get all the relevant Competitors, opps and Accounts from the database
		List<Competitor__c> competitorsList = [Select Id, Account__c, Opportunity__c, Competitive_Spend__c, Competitor_Name__c, Service_Expiration_Date__c, Service_Provided__c, CreatedDate from Competitor__c where Account__c IN :accountIds or Opportunity__c IN :opportunityIds];
		List<Opportunity> oppsList = [Select Id, Competitor_Info__c from Opportunity where Id IN :opportunityIds];
		List<Account> accountList = [Select Id, Competitor_Info__c from Account where Id IN :accountIds];
		oppsMap = new Map<ID, Opportunity>(oppsList);
		accountsMap = new Map<ID, Account>(accountList);
		
		if (competitorsList != null)
		{
			for (Competitor__c c : competitorsList)
			{
				if (compAccountsMap.containsKey(c.Account__c))
				{
					compAccountsMap.get(c.Account__c).add(c);
				}
				else
				{
					List<Competitor__c> newCompList = new List<Competitor__c>();
					newCompList.add(c);
					compAccountsMap.put(c.Account__c, newCompList);
				}
			
				if (c.Opportunity__c != null && compOppsMap.containsKey(c.Opportunity__c))
				{
					compOppsMap.get(c.Opportunity__c).add(c);
				}
				else
				{
					List<Competitor__c> newCompList = new List<Competitor__c>();
					newCompList.add(c);
					compOppsMap.put(c.Opportunity__c, newCompList);
				}
			}
		}
	}
	
	public void UpdateAccountCompetitorField(String accountId)
	{
		Account a = accountsMap.get(accountId);
		List<Competitor__c> compList = compAccountsMap.get(accountId);
		a.competitor_Info__c = BuildCompetitorName(compList);
	}
	
	public void UpdateOpportunityCompetitorField(String opportunityId)
	{
		if (opportunityId != null)
		{
			Opportunity o = oppsMap.get(opportunityId);
			List<Competitor__c> oppsCompList = compOppsMap.get(opportunityId);
			o.competitor_Info__c = BuildCompetitorName(oppsCompList);
		}
	}
	
	private String BuildCompetitorName(List<Competitor__c> compList)
	{
		if (compList != null)
		{
			String competitorText = '';
			
			for (Competitor__c c : compList)
			{
				if (c.Competitor_Name__c != null)
				{
					competitorText += c.Competitor_Name__c;
				}
				else
				{
					competitorText += 'No Competitor Name';
				}
				
				if (c.Service_Provided__c != null)
				{
					String[] tmpString = c.Service_Provided__c.split(';');
					
					Integer i = 1;
					competitorText += ', (';
					for (String s : tmpString)
					{
						if (i > 1)
						{
							competitorText += ', ';
						}
						
						competitorText += s;
						i++;
					}
					
					competitorText += ')';
				}
				else
				{
					competitorText += ', No Services Provided';
				}
				
				if (c.Service_Expiration_Date__c != null)
				{
					competitorText += ', ';
					DateTime dtConverted = Datetime.newInstance(c.Service_Expiration_Date__c.year(), c.Service_Expiration_Date__c.month(), c.Service_Expiration_Date__c.day(),0,0,0);
					competitorText += dtConverted.format('MM/dd/yyyy');
				}
				else
				{
					competitorText += ', No Expiration Date';
				}
				
				if (c.Competitive_Spend__c != null)
				{
					competitorText += ', $';
					competitorText += c.Competitive_Spend__c;
				}
				else
				{
					competitorText += ', No Competitive Spend';
				}
				
				competitorText += ', ';
				competitorText += c.CreatedDate.Format('MM/dd/yyyy');
				competitorText += '\r\n';
			}
			
			return competitorText;
		}
		
		return null;
	}

}