CS_SBOX_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Required_Invoice_Contact_Email__c</fullName>
        <description>Created by LM on 9/4/2013 for Phase 1 rollout</description>
        <label>Required Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Required_Invoice_Contact_Name__c</fullName>
        <description>Created by LM on 9/4/2013 for Phase 1 rollout</description>
        <label>Required Invoice Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/BDC_Activity_Type__c.object
<CustomObject>
    <description>Hold the Activity Types for the BDC Activities that should be created from a Renewal Opp</description>
    <fields>
        <fullName>Call_Template__c</fullName>
        <description>The template for the Renewal Call</description>
        <label>Call Template</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Days_Months__c</fullName>
        <description>Should the number entered be taken to be either Days or Months</description>
        <label>Days/Months</label>
        <picklist>
            <picklistValues>
                <fullName>Days</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <description>The Date to set the Due Date Against</description>
        <label>From</label>
        <picklist>
            <picklistValues>
                <fullName>Renewal Creation Date</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Due Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Renewal_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only create this Activity if the Customer is a New Renewal Customer</description>
        <label>New Renewal Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_Months__c</fullName>
        <description>The Number of Days or Months from either the Creation Date or Due Date that Task should have its Due Date Set As</description>
        <label>Number of Days/Months</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BDC Activity Type</label>
    <nameField>
        <label>BDC Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BDC Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Renewal_Due_Date__c</fullName>
        <formula>Opportunity__r.Renewal_Due_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Due Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <businessProcess>Client Services</businessProcess>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>At_Risk__c</fullName>
        <description>Created by LM on 9/26/2013 for Phase 2 rollout</description>
        <label>At Risk?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Change_Shipping_Email__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Shipping Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Change_Shipping_First_Name__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Shipping First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Shipping_Last_Name__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Shipping Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Shipping_Phone__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Shipping Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Close_Reasons_del__c</fullName>
        <description>Remember to duplicate any changes here in the Develop/Custom Settings section, too.</description>
        <label>Close Reasons</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Auto-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Reputation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content: Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content: Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Use Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eliminated/Reduced PR Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hired Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated Services Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Analysis Methodology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needed Full Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Payment/Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response From Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business/Merger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secured 2 yr deal (CA use only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified Lead</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <description>Added by MD 09/13/2012. A Field to hold the name of the Competitor that the Sale was Lost to or Stolen from</description>
        <inlineHelpText>A Competitor Name must be selected when Closing an Opportunity and the Close Reason is &quot;Competitor&quot;</inlineHelpText>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact_Email__c</fullName>
        <inlineHelpText>Please input the email address for the Invoice Contact above.</inlineHelpText>
        <label>Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact_Name__c</fullName>
        <label>Invoice Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Year_Spend__c</fullName>
        <label>Last Year Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Renewal_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/31/2013 for Phase 2 rollout</description>
        <label>New Renewal Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Opportunity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Sale</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gets checked by the Renewal Process from the Contract</description>
        <label>Renewal Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Due_Date__c</fullName>
        <description>Created by LM on 8/31/2013 for Phase 2 rollout</description>
        <label>Renewal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep_Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal Rep Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Tasks_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is set automatically after all the Renewal Tasks have completed to avoid them being duplicated</description>
        <label>Renewal Tasks Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_At_Risk_Case_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training At Risk Case Created</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Invoice_Contact_Email__c</fullName>
        <formula>SBQQ__Opportunity__r.Invoice_Contact_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact_Name__c</fullName>
        <description>Created by LM on</description>
        <formula>SBQQ__Opportunity__r.Invoice_Contact_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Contact Name</label>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <description>Closed Look</description>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/TestOpportunityHelper.cls
@isTest
private class TestOpportunityHelper {
     
	static testMethod void TestUpdateInvoiceDetails()
	{
		TestLibrary.InitAvaTax();
    
		User u = TestLibrary.createUser('Testuser', TestLibrary.BROADCAST_TRANSACTION_PROFILE);
		insert u;
        
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id);  
    
		insert acc;       
      
		Opportunity newOpp = TestLibrary.CreateOpportunity('TestOp', u.Id, acc.Id);
		newOpp.RecordTYpeId = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
		newOpp.Opportunity_Status__c = '';
    
		Opportunity op2 = TestLibrary.CreateOpportunity('TestOp2', u.Id, acc.Id);
		op2.RecordTYpeId = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
    
      
		List<Opportunity> opList = new List<Opportunity>();
		opList.add(newOpp);
		opList.add(op2);
      
		insert opList;
      
		Test.startTest();
    
		newOpp.Opportunity_Status__c = 'Pending Fulfillment'; 
		update newOpp;
            
		op2.Invoice_Contact_Email__c = 'jill@email.com';
		op2.Invoice_Contact_Name__c = 'Jill';
            
		try{
			update op2;
			//System.assert(false);
		}
		catch(exception e){
			//
		}
            
		Test.stopTest();
            
		Opportunity result = [Select Id,Opportunity_Status__c,Account.Required_Invoice_Contact_Name__c, Account.Required_Invoice_Contact_Email__c,Invoice_Contact_Email__c,Invoice_Contact_Name__c From Opportunity Where id=:newOpp.Id];      
                   
		//       system.assert(result.Opportunity_Status__c == 'Pending Fulfillment');
		System.debug('Opp Contact Email = ' + result.Invoice_Contact_Email__c + ' acc Contact Email = ' + result.Account.Required_Invoice_Contact_Email__c);
		//       system.assertEquals(result.Invoice_Contact_Email__c, result.Account.Required_Invoice_Contact_Email__c);
		//       system.assertEquals(result.Invoice_Contact_Name__c,result.Account.Required_Invoice_Contact_Name__c);         
      
	}
    
 
	static testMethod void TestCompleteRenewal(){
		TestLibrary.InitAvaTax();
          
		User u = TestLibrary.createUser('Testuser', TestLibrary.BROADCAST_TRANSACTION_PROFILE);
		insert u;
        
		System.runAs(u)
		{
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id); 
          
		insert acc;      
                 
		Opportunity op = TestLibrary.CreateOpportunity('TestOp', u.Id, acc.Id);
		op.RecordTYpeId = TestLibrary.OPPORTUNITY_RENEWALS_RECORD_TYPE;
		op.Type = 'Renewal'; 
		op.At_Risk__c = 'Yes';  
		op.Renewal_Due_Date__c = Date.today().addDays(30);
		insert op;
            
		Contract c = TestingUtils.createContract(acc.Id, op.Id);
		insert c;
            
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems('Test Product', 'CRT', op.Id, 1, 'Monitoring Services', 'Professional', 'Social Newsroom');
		insert olList;
          
		Test.startTest();
		op.Renewal_Completed__c = false;  
            
		List<Opportunity> opList = new List<Opportunity>();
		opList.add(op);
		opportunityHelper.CompleteRenewal(opList);
		update opList;
            
		Test.stopTest();
            
		op = [Select Id, Renewal_Completed__c,New_Renewal_Customer__c,Last_Year_Spend__c from Opportunity where Id = :op.Id];
		//  system.assertEquals(op.New_Renewal_Customer__c,false);   
		//  system.assertEquals(op.Renewal_Completed__c,true);   
            
	}    
		}
  
	static testMethod void TestAssignRetentionOwner(){
		TestLibrary.InitAvaTax();
          
		User u = TestLibrary.createUser('Testuser', TestLibrary.BROADCAST_TRANSACTION_PROFILE);
		insert u;
        
		System.runAs(u)
		{
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id); 
          
		insert acc;      
                 
		Opportunity op = TestLibrary.CreateOpportunity('TestOp', u.Id, acc.Id);
		insert op;
            
		Contract c = TestingUtils.createContract(acc.Id, op.Id);
		insert c;
            
		Product2 p = TestLibrary.createProduct('Ld Test Product', 'ld01', 'Distribution Services');
            
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems(p.ProductCode, op.Id, 1);
		insert olList;
          
		List<Opportunity> opList = new List<Opportunity>();
		opList.add(op);
          
		Test.startTest();
		OpportunityHelper.AssignRetentionOwner(opList);
		Test.stopTest();
            
		// op = [Select Id, Renewal_Rep_Assigned__c from Opportunity where Id = :op.Id];
		// system.assert(op.Renewal_Rep_Assigned__c == false);
            
	}  
		}
  
	static testMethod void TestCreateRenewalActivities()
	{
		TestLibrary.InitAvaTax();
         
		// Create all the BDC Records
		List<BDC_Activity_Type__c> atList = new List<BDC_Activity_Type__C>();
		atList.add(new BDC_Activity_Type__c(Name = 'BDC 6 Month Call', Call_Template__c = 'Test', Days_Months__c = 'Months', From__c = 'Renewal Due Date', New_Renewal_Customer__c = false, Number_of_Days_Months__c = 1));
		insert atList;
	  
		User u = TestLibrary.createUser('Testuser', TestLibrary.BROADCAST_TRANSACTION_PROFILE);
		insert u;
        
		System.runAs(u)
		{
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id); 
         
		insert acc;      
                 
		Opportunity op = TestLibrary.CreateOpportunity('TestOp', u.Id, acc.Id);
		op.Type = 'Renewal';
		op.Renewal_Completed__c = true;
		op.Renewal_Due_Date__c = Date.today().addDays(30);
		op.New_Renewal_Customer__c = false;
		op.Renewal_Tasks_Completed__c = false;
		insert op;
            
		Contract c = TestingUtils.createContract(acc.Id, op.Id);
		insert c;
            
		Product2 p = TestLibrary.createProduct('Ld Test Product', 'ld01', 'Distribution Services');
            
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems(p.ProductCode, op.Id, 1);
		insert olList;
          
		List<Opportunity> opList = new List<Opportunity>();
		opList.add(op);
          
		Test.startTest();
		OpportunityHelper.CreateRenewalActivities(opList);
		//  update opList;
		Test.stopTest();
            
		//Task t = [Select Id,Status,Priority,WhatId From Task Where WhatId = :op.Id limit 1];
		//op = [Select Id, Renewal_Tasks_Completed__c from Opportunity where Id = :op.Id];
		//system.assertEquals(t.WhatId,op.id);
		//system.assert(op.Renewal_Tasks_Completed__c == false);
            
	}  
		}
 
    
	static testMethod void TestUpdateContactIfShippingDetailsChange(){
		TestLibrary.InitAvaTax();
          
		User u = TestLibrary.createUser('Testuser', TestLibrary.BROADCAST_TRANSACTION_PROFILE);
		insert u;
        
		System.runAs(u)
		{
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id); 
          
		insert acc;      
                 
		Opportunity op = TestLibrary.CreateOpportunity('TestOp', u.Id, acc.Id);
		insert op;
            
		op.Change_Shipping_Email__c = 'jackjill@email.com';
		op.Change_Shipping_First_Name__c = 'Jack';
		op.Change_Shipping_Last_Name__c = 'Jill';
		op.Change_Shipping_Phone__c = '1231231234';
           
		Test.startTest();
		update op;
		Test.stopTest();
            
		Contact c = [Select Firstname,Lastname From Contact Where Firstname = 'Jack' And Lastname = 'Jill' Limit 1];
		system.assert(c != null);
            
	}
		}
    
	static testMethod void TestCreateTrainingCases(){
      
		TestLibrary.InitAvaTax();
          
		User u = TestLibrary.createUser('Testuser', TestLibrary.SYSTEM_ADMIN_USER_PROFILE);
		insert u;
        
		System.runAs(u)
		{
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id); 
          
		insert acc;      
                 
		Opportunity op = TestLibrary.CreateOpportunity('TestOp', u.Id, acc.Id);
		op.RecordTYpeId = TestLibrary.OPPORTUNITY_RENEWALS_RECORD_TYPE;
		op.At_Risk__c = 'Yes';  
		op.Type = 'Renewal'; 
		op.Renewal_Due_Date__c = Date.today().addDays(30);
		insert op;
            
		Opportunity op2 = TestLibrary.CreateOpportunity('TestOp2', u.Id, acc.Id);
		op2.RecordTYpeId = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
		insert op2;
            
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems('Test Product ld02', 'ld002', op2.Id, 1, 'Plan Services', 'Enterprise', '');
		insert olList;
            
		Opportunity op3 = TestLibrary.CreateOpportunity('TestOp3', u.Id, acc.Id);
		op3.RecordTYpeId = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
		insert op3;
            
		List<OpportunityLineItem> olList2 = TestLibrary.CreateOpportunityLineItems('Test Product ld03', 'RESTRAININGHALFDAY', op3.Id, 1, 'Packages', 'Basic', '');
		insert olList2;
              
                                             
		Test.startTest();
              
		op.Training_At_Risk_Case_Created__c = false;
		update op; 
            
		op2.Training_At_Risk_Case_Created__c = false;
		op2.StageName = 'Closed Won';
		op2.Close_Reasons_del__c = 'Price';
		op2.Competitor_Name__c = 'Vocus';
		op2.Up_Against__c = 'GoogleNews';
		update op2;
            
		op3.Training_At_Risk_Case_Created__c = false;
		op3.StageName = 'Closed Won';
		op3.Close_Reasons_del__c = 'Price';
		op3.Competitor_Name__c = 'Vocus';
		op3.Up_Against__c = 'GoogleNews';
		update op3;
            
		List<Opportunity> opList = new List<Opportunity>();
		opList.add(op);
		opList.add(op2);
		opList.add(op3);
		OpportunityHelper.CreateTrainingCases(opList);
		update opList;
		Test.stopTest();
            
		Case c = [Select Opportunity_Type__c, Opportunity_Owner__c, State_Province__c, AccountId From Case Where Subject = 'At Risk Training' And Type = 'At Risk Request' limit 1];
		op = [Select Id, type, OwnerId, Shipping_State__c, AccountId,Training_At_Risk_Case_Created__c From Opportunity Where id = :op.Id];
		system.assertEquals(c.Opportunity_Type__c, op.Type);
		system.assertEquals(c.Opportunity_Owner__c, op.OwnerId);
		system.assertEquals(c.State_Province__c, op.Shipping_State__c);
		system.assertEquals(c.AccountId, op.AccountId);
            
            /*Case c2 = [Select Opportunity_Type__c, Opportunity_Owner__c, State_Province__c, AccountId From Case Where Subject = 'Consult Training' And Type='Consult Request' limit 1];
            op2 = [Select Id, type, OwnerId, Shipping_State__c, AccountId,Training_At_Risk_Case_Created__c From Opportunity Where id = :op2.Id];
            system.assertEquals(c2.Opportunity_Type__c, op2.Type);
            system.assertEquals(c2.Opportunity_Owner__c, op2.OwnerId);
            system.assertEquals(c2.State_Province__c, op2.Shipping_State__c);
            system.assertEquals(c2.AccountId, op2.AccountId);
            
            Case c3 = [Select Opportunity_Type__c, Opportunity_Owner__c, State_Province__c, AccountId From Case Where Subject = 'On-Site Training' And Type='On-Site Request' limit 1];
            op3 = [Select Id, type, OwnerId, Shipping_State__c, AccountId,Training_At_Risk_Case_Created__c From Opportunity Where id = :op3.Id];
            system.assertEquals(c3.Opportunity_Type__c, op3.Type);
            system.assertEquals(c3.Opportunity_Owner__c, op3.OwnerId);
            system.assertEquals(c3.State_Province__c, op3.Shipping_State__c);
            system.assertEquals(c3.AccountId, op3.AccountId);*/

	} 
        
		}
        
	static testMethod void TestCreateClientServicesCases(){
		TestLibrary.InitAvaTax();
          
		User u = TestLibrary.createUser('Testuser', TestLibrary.SYSTEM_ADMIN_USER_PROFILE);
		insert u;
        
		System.runAs(u)
		{
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id); 
          
		insert acc;      
                      
		Opportunity op = TestLibrary.CreateOpportunity('TestOp1', u.Id, acc.Id);
		op.RecordTYpeId = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
		insert op;
            
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems('Test Product CCSA', 'CCSA', op.Id, 1, 'Monitoring Services', 'Basic', '');
		insert olList;
            
		Opportunity op2 = TestLibrary.CreateOpportunity('TestOp2', u.Id, acc.Id);
		op2.RecordTYpeId = TestLibrary.OPPORTUNITY_RENEWALS_RECORD_TYPE;
		op2.At_Risk__c = 'Yes';  
		op2.Type = 'Renewal'; 
		op2.Renewal_Due_Date__c = Date.today().addDays(30);
		//insert op2;
            
		List<OpportunityLineItem> olList2 = TestLibrary.CreateOpportunityLineItems('Test Product CCSA2 unfiltered', 'CCSA2', op2.Id, 1, 'Monitoring Services', 'Basic', '');
		//insert olList2;
            
		Opportunity op3 = TestLibrary.CreateOpportunity('TestOp3', u.Id, acc.Id);
		op3.RecordTYpeId = TestLibrary.OPPORTUNITY_RENEWALS_RECORD_TYPE;
		op3.At_Risk__c = 'Yes';  
		op3.Type = 'Renewal'; 
		op3.Renewal_Due_Date__c = Date.today().addDays(30);
		//insert op3;
            
		List<OpportunityLineItem> olList3 = TestLibrary.CreateOpportunityLineItems('Test Product CCSA3', 'CCSA3', op3.Id, 1, 'Broadcast Services', 'Professional', 'Social Newsroom');
		//insert olList3;
                                                
		Test.startTest();
		op.Client_Services_Tasks_Created__c = false;
		op.StageName = 'Closed Won';
		op.Close_Reasons_del__c = 'Price';
		op.Competitor_Name__c = 'Vocus';
		op.Up_Against__c = 'GoogleNews';
		update op;
            
		op2.Client_Services_Tasks_Created__c = false;
		op2.StageName = 'Closed Won';
		op2.Close_Reasons_del__c = 'Price';
		op2.Competitor_Name__c = 'Vocus';
		op2.Up_Against__c = 'Universal';
		//update op2;
              
		op3.Client_Services_Tasks_Created__c = false;
		op3.StageName = 'Closed Won';
		op3.Close_Reasons_del__c = 'Price';
		op3.Competitor_Name__c = 'Vocus';
		op3.Up_Against__c = 'Meltwater';
		//update op3;
            
		List<Opportunity> oppList = new List<Opportunity>();
		oppList.add(op);
		//oppList.add(op2);
		//oppList.add(op3);
		OpportunityHelper.CreateClientServicesCases(oppList);
		update oppList;
		Test.stopTest();
            
            /*Case c = [Select Id From Case Where Subject  like 'New Small Business Outreach%'];
            op = [Select Id, Client_Services_Tasks_Created__c From Opportunity Where id = :op.Id];
            system.assertEquals(t.Status, 'Not Started');
            system.assertEquals(t.Priority, 'Normal');
            system.assertEquals(t.WhatId,op.id);
            system.assert(op.Client_Services_Tasks_Created__c == true);
            
            Task t2 = [Select Id,Status,Priority,WhatId From Task Where Subject  like 'Verification Call%' and whatId = :op2.Id limit 1];
            op2 = [Select Id, Client_Services_Tasks_Created__c From Opportunity Where id = :op2.Id];
            system.assertEquals(t2.Status, 'Not Started');
            system.assertEquals(t2.Priority, 'Normal');
            system.assertEquals(t2.WhatId,op2.id);
        
            Task t3 = [Select Id,Status,Priority,WhatId From Task Where Subject  like 'PitchEngine Setup%' and whatId = :op3.Id limit 1];
            op3 = [Select Id, Client_Services_Tasks_Created__c From Opportunity Where id = :op3.Id];
            system.assertEquals(t3.Status, 'Not Started');
            system.assertEquals(t3.Priority, 'Normal');
            system.assertEquals(t3.WhatId,op3.id);*/
	}
		}
   
	static testMethod void TestCreateCreditRiskAssessmentCase(){
		TestLibrary.InitAvaTax();
          
		User u = TestLibrary.createUser('Testuser', TestLibrary.BROADCAST_TRANSACTION_PROFILE);
		insert u;
        
		System.runAs(u)
		{
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id); 
		insert acc;      
                 
		Opportunity op = TestLibrary.CreateOpportunity('TestOp1', u.Id, acc.Id);
		op.RecordTYpeId = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
		insert op;
            
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems('Test Product CCSA', 'CCSA', op.Id, 1, 'Monitoring Services', 'Basic', '');
		insert olList;
                        
		Test.startTest();
              
		op = [Select Id, Credit_Risk_Case_Created__c, Number_of_Products__c, CA_Rep__c, GP_Cust_ID__c, AccountId, Sub_Account__c from Opportunity where Id = :op.Id];
		List<Opportunity> oppList = new List<Opportunity>();
		oppList.add(op);
		OpportunityHelper.CreateCreditRiskAssessmentCase(oppList);
		update op;
		Test.stopTest();
    
		///Case c = [Select Opportunity__c, AccountId From Case Where Opportunity__c =:op.Id limit 1];
		//op = [Select Id, AccountId, Credit_Risk_Case_Created__c from Opportunity where id=:op.id];
		//system.assertEquals(c.Opportunity__c, op.id);
		//system.assertEquals(c.AccountId, op.AccountId);
		//system.assert(op.Credit_Risk_Case_Created__c == true);
	}
		}
  
	static testMethod void TestProcessOpportunities()
	{
		TestingUtils.InitAvaTax();
		
		Account acc = TestingUtils.CreateAccount();  
		insert acc;	   	
	   	
		Opportunity newOpp = TestingUtils.createOpportunity(acc.Id);
		newOpp.Type = 'New';
		insert newOpp;
		
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems('Test Product CCSA', 'CCSA', newOpp.Id, 1, 'Monitoring Services', 'Basic', '');
		insert olList;
		
		SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Status__c = 'Draft', SBQQ__SubscriptionTerm__c = 12, 
			SBQQ__StartDate__c = Date.today(), Payment_Type__c = 'Credit Card', SBQQ__Opportunity__c = newOpp.Id, SBQQ__Type__c = 'Quote');
		insert quote;
		
		SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(SBQQ__Quote__c = quote.Id);
		insert quoteLine;
		
		Contract cont = TestingUtils.createContract(acc.Id, newOpp.Id);
		cont.SBQQ__RenewalOpportunity__c = newOpp.Id;
		cont.SBQQ__Quote__c = quote.Id;
		insert cont;
		
		Product2 connectProd = TestingUtils.createProduct(false);
		connectProd.Family = 'Connect Services';
		connectProd.ProductCode = 'Connect1';
		connectProd.Commissionable_Product__c = true;
		insert connectProd;
		Product2 broadcastProd = TestingUtils.createProduct(false);
		broadcastProd.Family = 'Broadcast Services';
		broadcastProd.ProductCode = 'Broadcast1';
		insert broadcastProd;
		
		SBQQ__Subscription__c sub = TestingUtils.createSubscription(acc.Id, cont.Id, connectProd.Id);
		sub.SBQQ__QuoteLine__c = quoteLine.Id;
		//		insert sub;
		//		System.debug('Product = ' + sub.SBQQ__Product__c + ' Product Family = ' + sub.Product_Family__c + ' Com Product = ' + sub.Commissionable_Product__c + ' Opp Type = ' + sub.Opp_Type__c);
		
		Asset ass1 = TestingUtils.createAsset(acc.Id, connectProd.Id);
		ass1.SBQQ__QuoteLine__c = quoteLine.Id;
		insert ass1;
		Asset ass2 = TestingUtils.createAsset(acc.Id, connectProd.Id);
		ass2.SBQQ__QuoteLine__c = quoteLine.Id;
		insert ass2;
		
		Test.startTest();
		
		Database.executeBatch(new batchProcessOpportunities(), 1);
		
		Test.stopTest();
	}
	
	static testMethod void TestProcessRenewalOpps()
	{
		TestingUtils.InitAvaTax();
		Account acc = TestingUtils.CreateAccount();  
		insert acc;	   	
		   	
		Opportunity newOpp = TestingUtils.createOpportunity(acc.Id);
		newOpp.Type = 'Renewal';
		insert newOpp;
			
		List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems('Test Product CCSA', 'CCSA', newOpp.Id, 1, 'Plan Services', 'Basic', 'Basic Database');
		insert olList;
			
		SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Status__c = 'Draft', SBQQ__SubscriptionTerm__c = 12, 
			SBQQ__StartDate__c = Date.today(), Payment_Type__c = 'Credit Card', SBQQ__Opportunity__c = newOpp.Id, SBQQ__Type__c = 'Quote');
		insert quote;
			
		SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(SBQQ__Quote__c = quote.Id);
		insert quoteLine;
			
		Contract cont = TestingUtils.createContract(acc.Id, newOpp.Id);
		cont.SBQQ__RenewalOpportunity__c = newOpp.Id;
		cont.SBQQ__Quote__c = quote.Id;
		insert cont;
			
		Product2 connectProd = TestingUtils.createProduct(false);
		connectProd.Family = 'Connect Services';
		connectProd.ProductCode = 'Connect1';
		connectProd.Commissionable_Product__c = true;
		insert connectProd;
		Product2 broadcastProd = TestingUtils.createProduct(false);
		broadcastProd.Family = 'Broadcast Services';
		broadcastProd.ProductCode = 'Broadcast1';
		insert broadcastProd;
			
		SBQQ__Subscription__c sub = TestingUtils.createSubscription(acc.Id, cont.Id, connectProd.Id);
		sub.SBQQ__QuoteLine__c = quoteLine.Id;
		//		insert sub;
		//		System.debug('Product = ' + sub.SBQQ__Product__c + ' Product Family = ' + sub.Product_Family__c + ' Com Product = ' + sub.Commissionable_Product__c + ' Opp Type = ' + sub.Opp_Type__c);
			
		Asset ass1 = TestingUtils.createAsset(acc.Id, connectProd.Id);
		ass1.SBQQ__QuoteLine__c = quoteLine.Id;
		insert ass1;
		Asset ass2 = TestingUtils.createAsset(acc.Id, connectProd.Id);
		ass2.SBQQ__QuoteLine__c = quoteLine.Id;
		insert ass2;
			
		Test.startTest();
			
		Database.executeBatch(new batchProcessRenewalOpps(), 1);
			
		Test.stopTest();
		
	}
}