CS_SBOX_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Analysis_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Analysis Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Broadcast_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Broadcast Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Tier__c</fullName>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <inlineHelpText>Client Support team assigned to this account.</inlineHelpText>
        <label>CS Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International - Tier2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Setup Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News Consultants</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Connect_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Connect Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monitoring_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Monitoring Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Plan Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Invoice_Contact_Email__c</fullName>
        <description>Created by LM on 9/4/2013 for Phase 1 rollout</description>
        <label>Required Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Required_Invoice_Contact_Name__c</fullName>
        <description>Created by LM on 9/4/2013 for Phase 1 rollout</description>
        <label>Required Invoice Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Added by LM on 2/6/2013; From MS CRM</description>
        <inlineHelpText>Federal Tax Exempt status of the Account</inlineHelpText>
        <label>Federal Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <description>Created by LM on 9/16/2013 for Phase 2 rollout</description>
        <label>Edition</label>
        <picklist>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 9/16/2013 for Phase 2 rollout</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Sales_Support_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <businessProcess>Client Services</businessProcess>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 9/4/2013 for Phase 2 rollout</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote that generated this contract.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 3/25/2014 for Phase2</description>
        <label>Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Renewals</fullName>
        <active>true</active>
        <businessProcess>Subscription Sales Process</businessProcess>
        <label>Renewals</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <description>Created by LM on 11/27/2013 for Phase 2 rollout</description>
        <label>Edition</label>
        <picklist>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-CisionPoint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Family__c</fullName>
        <label>Sub Family</label>
        <picklist>
            <controllingField>Family</controllingField>
            <picklistValues>
                <fullName>Advanced Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analyze Tab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Analysts Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Monitoring Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Additional Users</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Email/Fax Points</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Premium Data/Add-ons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Monitoring CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Monitoring Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Monitoring Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Newsroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web/Wire Distribution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Change_Billing_City__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Billing_Country__c</fullName>
        <description>Created by LM on 6/4/2014 for Phase2</description>
        <label>Change Billing Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Billing_State__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Billing State</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Billing_Street__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Billing_Zip__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Billing Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Invoice_Contact_Email__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Change_Invoice_Contact_Name__c</fullName>
        <description>Created by LM on 4/28/2014 for Phase2 DocuSign Rollout</description>
        <label>Change Invoice Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Invoice_Contact_Phone__c</fullName>
        <description>Created by LM on 6/4/2014 for Phase2</description>
        <label>Change Invoice Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 4/16/2014 for Phase2</description>
        <label>Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <label>Admin</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/OpportunityCache.cls
public class OpportunityCache
{
	public static Map<Id, Account> accountsMap = null;
	public static Map<String, Contact> contactsMap = null;
	public static Map<ID, List<OpportunityLineItem>> lineItemsMap = null;
	public static Map<Id, SBQQ__Quote__c> quotesMap = null;
	public static Map<ID, OpportunityContactRole> primaryOcrMap = null;
	public static Map<ID, List<OpportunityContactRole>> ocrMap = null;
	public static Map<Id, User> usersMap = null;
	public static List<BDC_Activity_Type__c> activityTypesList = null;
	public static Map<ID, List<Competitor__c>> competitorsMap = null;
	public static Map<ID, List<Contract>> contractsMap = null;
	//public static Map<ID, Contract> contractMap = null;
	public static Map<Id, Contract> renewalContractMap = null;
		
	public static Id TaskRenewalRecordType = null;
	public static Id CaseTrainingRecordType = null;
	public static Id CaseClientServicesRecordType = null;
	public static Id CaseContractAdminRecordType = null;
	public static Id OpportunityNewBizRecordType = null;
	public static Id OpportunityRenewalsRecordType = null;
	public static Id OpportunityLockedNewBizRecordType = null;
	public static Id OpportunityLockedRenewalsRecordType = null;
	public static Id TaskClientServicesRecordType = null;
	public static Id salesforceAdminUser = null;
	public static Id defaultContractAdminUser = null;
	
	public static Id QuoteAdminRecordType = null;
	public static Id QuoteNewQuoteRecordType = null;
	public static Id QuoteBeforeApprovalsRecordType = null;
	public static Id QuoteAfterApprovalsRecordType = null;
	public static Id QuotePostSignatureRecordType = null;
	public static Id QuoteClosedRecordType = null;
	
	public static Id profileId = userinfo.getProfileId();	
	public static Id currentUserId = UserInfo.getUserId();
	public static String profileName = null;
	
	private static List<Opportunity> GenerateAccountsMapOppsList = new List<Opportunity>();
	private static List<Opportunity> GenerateContactMapOppsList = new List<Opportunity>();
	private static List<Opportunity> GenerateOpportunityLineItemMapList = new List<Opportunity>();
	private static List<Opportunity> GeneratePrimaryQuotesList = new List<Opportunity>();
	private static List<Opportunity> GenerateOCRList = new List<Opportunity>();
	private static List<Opportunity> GenerateCompetitorsList = new List<Opportunity>();
	private static List<Opportunity> GenerateRenewalContractList = new List<Opportunity>();
	private static List<Opportunity> GenerateContractsList = new List<Opportunity>();
		
	public static void GenerateAccountsMap(List<Opportunity> oppsList)
	{
		if (accountsMap == null || UtilityClass.HasListChanged(GenerateAccountsMapOppsList, oppsList))
		{
			Set<ID> accountIds = new Set<ID>();
			for (Opportunity opp: oppsList)
  			{
				System.Debug('ADDING Account Id ' + opp.AccountId);
    			accountIds.add(opp.AccountId);
  			}
  
  			accountsMap = new Map<ID, Account>([select Id, Plan_Customer__c, Connect_Customer__c, Monitoring_Customer__c, Analysis_Customer__c, Broadcast_Customer__c, Project_Lead__c, CS_Tier__c, Name, Renewal_Rep__r.Name, Required_Invoice_Contact_Email__c, Required_Invoice_Contact_Name__c, BillingState from Account where Id IN :accountIds]);
		
			System.debug('Accounts Map size = ' + accountsMap.size());
			GenerateAccountsMapOppsList.clear();
			GenerateAccountsMapOppsList.addAll(oppsList);
		}
	}

	public static void GenerateContactMap(List<Opportunity> oppsList)
	{
		if (contactsMap == null || UtilityClass.HasListChanged(GenerateContactMapOppsList, oppsList))
		{
			// Get all the Account Ids for the Opps
			Set<Id> accountIds = new Set<Id>();
			for (Opportunity o : oppsList)
			{
				if (o.AccountId != null)
				{
					accountIds.add(o.AccountId);
				}
			}
			
			// Get all Contacts for each of these accounts
			List<Contact> contList = [Select Id, AccountId, FirstName, LastName, Email, Phone from Contact where AccountId in :accountIds];
			contactsMap = new Map<String, Contact>();
			if (contList != null)
			{
				for (Contact c : contList)
				{
					String key = c.AccountId + '|' + c.LastName + '|' + c.Email;
					contactsMap.put(key, c);
				}
			}
			
			GenerateContactMapOppsList.clear();
			GenerateContactMapOppsList.addAll(oppsList);
		}
	}
	
	public static void GenerateOpportunityLineItemMap(List<Opportunity> oppsList)
	{
		if (lineItemsMap == null || UtilityClass.HasListChanged(GenerateOpportunityLineItemMapList, oppsList))
		{
			List<OpportunityLineItem> liList = [select Id, UnitPrice, OpportunityId, Product_Family__c, PriceBookEntry.Product2.ProductCode, TotalPrice, PriceBookEntry.Product2.Family, PricebookEntry.Product2.Name, PriceBookEntry.Product2.Edition__C, PriceBookEntry.Product2.Sub_Family__c from OpportunityLineItem where OpportunityId IN :oppsList];
			
			lineItemsMap = new Map<ID, List<OpportunityLineItem>>();
			
			if (liList != null)
			{
				for (OpportunityLineItem li : liList)
				{
					if (lineItemsMap.containsKey(li.OpportunityId))
					{
						lineItemsMap.get(li.OpportunityId).add(li);
					}
					else
					{
						List<OpportunityLineItem> tempLi = new List<OpportunityLineItem>();
						tempLi.add(li);
						lineItemsMap.put(li.OpportunityId, tempLi);
					}
				}
			}
			
			GenerateOpportunityLineItemMapList.clear();
			GenerateOpportunityLineItemMapList.addAll(oppsList);
		}
		
	}
	
	public static void GeneratePrimaryQuotes(List<Opportunity> oppsList)
	{
		if (quotesMap == null || UtilityClass.HasListChanged(GeneratePrimaryQuotesList, oppsList))
		{
			List<SBQQ__Quote__c> quoteList = [select Id, SBQQ__StartDate__c, SBQQ__Opportunity__c, SBQQ__PrimaryContact__c, Tax_Exempt__c, Change_Billing_Street__c, Change_Billing_City__c, Change_Billing_State__c, Change_Billing_Zip__c, Change_Billing_Country__c, Change_Invoice_Contact_Email__c, Change_Invoice_Contact_Name__c, Change_Invoice_Contact_Phone__c from SBQQ__Quote__c where SBQQ__Opportunity__c IN :oppsList and SBQQ__Primary__c = true];
			
			quotesMap = new Map<Id, SBQQ__Quote__c>();
			
			if (quoteList != null)
			{
				for (SBQQ__Quote__c q : quoteList)
				{
					quotesMap.put(q.SBQQ__Opportunity__c, q);
				}
			}
			
			GeneratePrimaryQuotesList.clear();
			GeneratePrimaryQuotesList.addAll(oppsList);
		}
	}
	
	public static void GenerateOCR(List<Opportunity> oppsList)
	{
		if (ocrMap == null || UtilityClass.HasListChanged(GenerateOCRList, oppsList))
		{
			List<OpportunityContactRole> ocrList = [Select Id, ContactId, OpportunityId, IsPrimary from OpportunityContactRole where OpportunityId IN :oppsList];
			ocrMap = new Map<ID, List<OpportunityContactRole>>();
			primaryOcrMap = new Map<ID, OpportunityContactRole>();
			
			if (ocrList != null)
			{						
				for (OpportunityContactRole ocr : ocrList)
				{
					if (ocrMap.containsKey(ocr.OpportunityId))
					{
						ocrMap.get(ocr.OpportunityId).add(ocr);	
					}
					else
					{
						List<OpportunityContactRole> tempList = new List<OpportunityContactRole>();
						tempList.add(ocr);
						ocrMap.put(ocr.OpportunityId, tempList);
					}
					
					if (ocr.IsPrimary)
					{
						primaryOcrMap.put(ocr.OpportunityId, ocr);
					}
				}
			}
			
			GenerateOCRList.clear();
			GenerateOCRList.addAll(oppsList);
		}
	}
	
	public static void GenerateRenewalContract(List<Opportunity> oppsList)
	{
		if (renewalContractMap == null || (renewalContractMap != null && renewalContractMap.values().size() == 0) || UtilityClass.HasListChanged(GenerateRenewalContractList, oppsList))
		{
			List<Contract> contList = [Select Id, SBQQ__RenewalOpportunity__c, SBQQ__Opportunity__r.OwnerId, SBQQ__Opportunity__r.Type, SBQQ__Opportunity__r.Last_Year_Spend__c from Contract where SBQQ__RenewalOpportunity__c in :oppsList];
			renewalContractMap = new Map<ID, Contract>();
			
			if (contList != null)
			{						
				for (Contract c : contList)
				{
					renewalContractMap.put(c.SBQQ__RenewalOpportunity__c, c);
				}
			}
			
			GenerateRenewalContractList.clear();
			GenerateRenewalContractList.addAll(oppsList);
		}
	}
	
	public static void GenerateUsersMap()
	{
		if (usersMap == null)
		{
			usersMap = new Map<Id, User>([Select Id, CA_Rep__c from User where IsActive = true]);
			profileName = [Select Id,Name from Profile where Id=:profileId].Name;
		}
	}
	
	public static void GenerateBDCList()
	{
		if (activityTypesList == null)
		{
			activityTypesList = [select Id, Name, Days_Months__c, From__c, New_Renewal_Customer__c, Number_of_Days_Months__c from BDC_Activity_Type__c];
		}
	}
	
	public static void GenerateRecordTypeIds()
	{
		if (TaskRenewalRecordType == null)
		{
			Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName();
			if(rtMapByName.containsKey(Constants.RecordTypeAdmin))
				QuoteAdminRecordType = rtMapByName.get(Constants.RecordTypeAdmin).getRecordTypeId();
			if(rtMapByName.containsKey(Constants.RecordTypeNewQuote))
				QuoteNewQuoteRecordType = rtMapByName.get(Constants.RecordTypeNewQuote).getRecordTypeId();
			if(rtMapByName.containsKey(Constants.RecordTypeBeforeApprovals))
				QuoteBeforeApprovalsRecordType = rtMapByName.get(Constants.RecordTypeBeforeApprovals).getRecordTypeId();
			if(rtMapByName.containsKey(Constants.RecordTypeAfterApprovals))
				QuoteAfterApprovalsRecordType = rtMapByName.get(Constants.RecordTypeAfterApprovals).getRecordTypeId();
			if(rtMapByName.containsKey(Constants.RecordTypePostSignature))
				QuotePostSignatureRecordType = rtMapByName.get(Constants.RecordTypePostSignature).getRecordTypeId();
			if(rtMapByName.containsKey(Constants.RecordTypeClosed))
				QuoteClosedRecordType = rtMapByName.get(Constants.RecordTypeClosed).getRecordTypeId();
			
			List<RecordType> rtList = [select Id, Name, SObjectType from RecordType where (SObjectType = 'Task' and (Name = 'Renewal Sales' or Name = 'Client Services')) or (SObjectType = 'Opportunity' and (Name = 'New Biz' or Name = 'Renewals' or Name = 'Locked New Biz' or Name = 'Locked Renewals')) or (SObjectType = 'Case' and (Name = 'Training' or Name = 'Contract Admin' or Name = 'Client Services'))];

			if (rtList != null && rtList.size() > 0)
			{
				for (RecordType r : rtList)
				{
					if (r.SObjectType == 'Task' && r.Name == 'Renewal Sales')
					{
						TaskRenewalRecordType = r.Id;
					}
					else if (r.SObjectType == 'Case' && r.Name == 'Training')
					{
						CaseTrainingRecordType = r.Id;
					}
					else if (r.SObjectType == 'Case' && r.Name == 'Client Services')
					{
						CaseClientServicesRecordType = r.Id;
					}
					else if (r.SObjectType == 'Task' && r.Name == 'Client Services')
					{
						TaskClientServicesRecordType = r.Id;
					}
					else if (r.SObjectType == 'Opportunity' && r.Name == 'New Biz')
					{
						OpportunityNewBizRecordType = r.Id;
					}
					else if (r.SObjectType == 'Opportunity' && r.Name == 'Renewals')
					{
						OpportunityRenewalsRecordType = r.Id;
					}
					else if (r.SObjectType == 'Opportunity' && r.Name == 'Locked New Biz')
					{
						OpportunityLockedNewBizRecordType = r.Id;
					}
					else if (r.SObjectType == 'Opportunity' && r.Name == 'Locked Renewals')
					{
						OpportunityLockedRenewalsRecordType = r.Id;
					}
					else if (r.SObjectType == 'Case' && r.Name == 'Contract Admin')
					{
						CaseContractAdminRecordType = r.Id;
					}
				}
			}
		}
	}
	
	public static void GenerateAdminUserId()
	{
		if (salesforceAdminUser == null)
		{
			List<User> adminUser = [Select Id, Name from User where Name = 'SFDC Admin' or Name = 'Meghan Manetti'];
			
			if (adminUser != null)
			{
				for (User u : adminUser)
				{
					if (u.Name == 'SFDC Admin')
					{
						salesforceAdminUser = u.Id;
					}
					else
					{
						defaultContractAdminUser = u.Id;
					}
				}
			}
		}
	}
	
	public static void GenerateCompetitors(List<Opportunity> oppsList)
	{
		if (competitorsMap == null || UtilityClass.HasListChanged(GenerateCompetitorsList, oppsList))
		{
			List<Competitor__c> compsList = [Select Id, Opportunity__c, Competitor_Name__c, Opportunity_Close__c from Competitor__c where Opportunity__c IN :oppsList];
			
			competitorsMap = new Map<ID, List<Competitor__c>>();
			
			if (compsList != null)
			{
				for (Competitor__c c : compsList)
				{
					if (competitorsMap.containsKey(c.Opportunity__c))
					{
						competitorsMap.get(c.Opportunity__c).add(c);
					}
					else
					{
						List<Competitor__c> tempCompList = new List<Competitor__c>();
						tempCompList.add(c);
						competitorsMap.put(c.Opportunity__c, tempCompList);
					}
				}
			}
			
			GenerateCompetitorsList.clear();
			GenerateCompetitorsList.addAll(oppsList);
		}
	}	
}