CS_SBOX_20150209_01/Metadata/unpackaged/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(Product2.Family)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this asset.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote that generated this contract.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Renewal opportunity generated to track the renewal of this contract.</description>
        <inlineHelpText>Renewal opportunity generated to track the renewal of this contract.</inlineHelpText>
        <label>Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Contracts</relationshipLabel>
        <relationshipName>RenewedContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broadcast_Commissionable_Potential__c</fullName>
        <description>Created by LM on 11/5/2013 for Phase 2 rollout</description>
        <inlineHelpText>This total=Last Year&apos;s Broadcast Renewable Products-Last Year&apos;s Broadcast Non-Commissionable Products</inlineHelpText>
        <label>Broadcast Commissionable Potential</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Broadcast_Non_Commissionable_Potential__c</fullName>
        <description>Created by LM on 11/5/2013 for Phase 2 rollout</description>
        <inlineHelpText>This total=Last Year&apos;s Broadcast Renewable Products-Last Year&apos;s Broadcast Commissionable Products</inlineHelpText>
        <label>Broadcast Non-Commissionable Potential</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Potential__c</fullName>
        <description>Added by LM on 3/4/2013; From MS CRM</description>
        <inlineHelpText>This total=Last Year&apos;s Renewable Products-Last Year&apos;s Non-Commissionable Products</inlineHelpText>
        <label>Commissionable Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Year_Total_Spend__c</fullName>
        <description>Created by LM on 11/5/2013 for Phase 2 rollout</description>
        <inlineHelpText>All products purchased last year. (Renewable and Non-Renewable)</inlineHelpText>
        <label>Last Year Total Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Non_Commissionable_Potential__c</fullName>
        <description>Added by LM on 3/4/2013; From MS CRM</description>
        <inlineHelpText>This total=Last Year&apos;s Renewable Products-Last Year&apos;s Commissionable Products</inlineHelpText>
        <label>Non-Commissionable Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Commissionable_Potential__c</fullName>
        <formula>SBQQ__Opportunity__r.Commissionable_Potential__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commissionable Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net unit price for the product quoted by this line item.</description>
        <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
        <label>Net Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Subscription__c.object
<CustomObject>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Commissionable_Product__c</fullName>
        <formula>SBQQ__Product__r.Commissionable_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commissionable Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opp_Type__c</fullName>
        <formula>TEXT(SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity__r.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Potential_Amount__c</fullName>
        <description>Created by LM on 3/5/2014 for Phase2</description>
        <label>Potential Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(SBQQ__Product__r.Family)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract which parents this subscription</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net price for this subscription.</description>
        <inlineHelpText>Net price for this subscription.</inlineHelpText>
        <label>Net Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/batchRenewalTotals.cls
global class batchRenewalTotals implements Database.Batchable<sObject>, Schedulable
{
	private Map<Id, Opportunity> renewalOppsMap = null;
	private Map<Id, List<SBQQ__Subscription__c>> subsMap = null;
	private Map<Id, List<Asset>> assetMap = null;
	
	global Database.QueryLocator start(Database.BatchableContext BC)         
    {
    	return Database.getQueryLocator([select Id, SBQQ__RenewalOpportunity__c, SBQQ__Quote__c from Contract where SBQQ__RenewalOpportunity__c != null]);
    }
 
    global void execute(Database.BatchableContext bc, List<SObject> scope)
	{
		SetupBatch((List<Contract>)scope);
		
		for (Contract c : (List<Contract>)scope)
		{
			// Get the Opp for this Contract
			Opportunity opp = renewalOppsMap.get(c.SBQQ__RenewalOpportunity__c);
			
			// Get the subs lines for this Contract
			List<SBQQ__Subscription__c> subsList = subsMap.get(c.Id);
			
			// Get the Assetts for the quote linked to this Contract
			List<Asset> assetList = assetMap.get(c.SBQQ__Quote__c);
		
			Decimal totalNetPrice = 0;
			
			if (subsList != null)
			{
				Decimal totalCommissionablePotentialAmount = 0;
				Decimal totalNonCommissionablePotentialAmount = 0;
				Decimal totalBroadcastCommissionableAmount = 0;
				Decimal totalBroadcastNonCommissionableAmount = 0;
						
				for (SBQQ__Subscription__c s : subsList)
				{
					if (s.Potential_Amount__c != null)
					{
						if (s.Product_Family__c != 'Broadcast Services' && s.Commissionable_Product__c && (s.Opp_Type__c == 'New' || s.Opp_Type__c == 'Renewal' || s.Opp_Type__c == 'Renewal (Paid Extension)'))
						{
							totalCommissionablePotentialAmount += s.Potential_Amount__c;
						}
						else if (s.Product_Family__c != 'Broadcast Services' && s.Product_Family__c != 'Connect Services' && s.Commissionable_Product__c && s.Opp_Type__c == 'Upsell')
						{
							totalCommissionablePotentialAmount += s.Potential_Amount__c;
						}
						else if (s.Product_Family__c != 'Broadcast Services' && !s.Commissionable_Product__c && (s.Opp_Type__c == 'New' || s.Opp_Type__c == 'Renewal' || s.Opp_Type__c == 'Renewal (Paid Extension)'))
						{
							totalNonCommissionablePotentialAmount += s.Potential_Amount__c;
						}
						else if (s.Product_Family__c == 'Connect Services' && s.Commissionable_Product__c && s.Opp_Type__c == 'Upsell')
						{
							totalNonCommissionablePotentialAmount += s.Potential_Amount__c;
						}
						else if (s.Product_Family__c == 'Broadcast Services' && s.Commissionable_Product__c)
						{
							totalBroadcastCommissionableAmount += s.Potential_Amount__c;
						}
						else if (s.Product_Family__c == 'Broadcast Services' && !s.Commissionable_Product__c)
						{
							totalBroadcastNonCommissionableAmount += s.Potential_Amount__c;
						}
					}
					
					if (s.SBQQ__NetPrice__c != null)
					{
						totalNetPrice += s.SBQQ__NetPrice__c;
					}
				}
				
				opp.Commissionable_Potential__c = totalCommissionablePotentialAmount;
				opp.Non_Commissionable_Potential__c = totalNonCommissionablePotentialAmount;
				opp.Broadcast_Commissionable_Potential__c = totalBroadcastCommissionableAmount;
				opp.Broadcast_Non_Commissionable_Potential__c = totalBroadcastNonCommissionableAmount;
			}
			
			if (assetList != null)
			{
				for (Asset a : assetList)
				{
					if (a.Price != null)
					{
						totalNetPrice += a.Price;
					}
				}
			}
			
			opp.Last_Year_Total_Spend__c = totalNetPrice;
		}
		
		update renewalOppsMap.values();
	}
 
    global void finish(Database.BatchableContext bc)
	{
	} 
	
	private void SetupBatch(List<Contract> scope)
	{
		Set<Id> renewalOppsIds = new Set<Id>();
		Set<Id> quoteIds = new Set<Id>();
		for (Contract c : scope)
		{
			renewalOppsIds.add(c.SBQQ__RenewalOpportunity__c);
			
			if (c.SBQQ__Quote__c != null)
			{
				quoteIds.add(c.SBQQ__Quote__c);
			}
		}
		
		renewalOppsMap = new Map<Id, Opportunity>([Select Id, AccountId, Commissionable_Potential__c, Non_Commissionable_Potential__c, Broadcast_Commissionable_Potential__c, Broadcast_Non_Commissionable_Potential__c from Opportunity where Id in :renewalOppsIds]);
		
		List<SBQQ__Subscription__c> subsList = [select Id, SBQQ__Contract__c, Potential_Amount__c, Product_Family__c, Commissionable_Product__c, Opp_Type__c, SBQQ__NetPrice__c from SBQQ__Subscription__c where SBQQ__Contract__c in :scope];
		subsMap = new Map<Id, List<SBQQ__Subscription__c>>();
		if (subsList != null)
		{
			for (SBQQ__Subscription__c s : subsList)
			{
				if (subsMap.containsKey(s.SBQQ__Contract__c))
				{
					subsMap.get(s.SBQQ__Contract__c).add(s);
				}
				else
				{
					List<SBQQ__Subscription__c> tempList = new List<SBQQ__Subscription__c>();
					tempList.add(s);
					subsMap.put(s.SBQQ__Contract__c, tempList);
				}
			}
		}
		
		List<Asset> assetList = [Select Id, SBQQ__QuoteLine__r.SBQQ__Quote__c, Price from Asset where SBQQ__QuoteLine__r.SBQQ__Quote__c in :quoteIds];
		assetMap = new Map<Id, List<Asset>>();
		if (assetList != null)
		{
			for (Asset a : assetList)
			{
				if (assetMap.containsKey(a.SBQQ__QuoteLine__r.SBQQ__Quote__c))
				{
					assetMap.get(a.SBQQ__QuoteLine__r.SBQQ__Quote__c).add(a);
				}
				else
				{
					List<Asset> tempList = new List<Asset>();
					tempList.add(a);
					assetMap.put(a.SBQQ__QuoteLine__r.SBQQ__Quote__c, tempList);
				}
			}
		}
	}
	
	global void execute(SchedulableContext ctx)
	{
        Database.executeBatch(new batchRenewalTotals(), 50);
    }

}