CS_SBOX_20150209_01/Metadata/unpackaged/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(Product2.Family)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this asset.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote that generated this contract.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Renewal opportunity generated to track the renewal of this contract.</description>
        <inlineHelpText>Renewal opportunity generated to track the renewal of this contract.</inlineHelpText>
        <label>Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Contracts</relationshipLabel>
        <relationshipName>RenewedContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Commissionable_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Commissionable Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Commissionable_Product__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Created by LM on 3/14/2014</description>
        <label>Commissionable Product</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Subscription__c.object
<CustomObject>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Commissionable_Product__c</fullName>
        <formula>SBQQ__Product__r.Commissionable_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commissionable Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opp_Type__c</fullName>
        <formula>TEXT(SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity__r.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(SBQQ__Product__r.Family)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/TestBatchRenewalTotals.cls
@isTest
private with sharing class TestBatchRenewalTotals
{
	static testMethod void TestBatchRenewalTotals()
	{
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test1', TestLibrary.NEW_BIZ_PROFILE);
        insert u;
		        
		Account a = TestLibrary.CreateAccount('Test Account', u.Id);  
       	insert a;
		
		Contact c = TestLibrary.CreateContact('Test', 'Test@cisionus.com', u.Id, a.Id);
		insert c;
		
		Opportunity o = TestLibrary.CreateOpportunity('Test', u.Id, a.Id);
		insert o;
		
	  	List<OpportunityLineItem> olList = TestLibrary.CreateOpportunityLineItems('Test Product','CRT', o.Id, 1, 'Connect Services', 'Professional','Social Newsroom');
        insert olList;
		
		Product2 p = [Select Id from Product2 where Name = 'Test Product'];
		
		/*SBQQ__Quote__c q = TestLibrary.CreateQuote(a.Id, o.Id);
		insert q;
				
		SBQQ__QuoteLine__c quoteLine = TestLibrary.createQuoteLine(q.Id, p.Id);
		insert quoteLine;
				
		Contract cont = TestingUtils.createContract(a.Id, o.Id);
		cont.SBQQ__RenewalOpportunity__c = o.Id;
		cont.SBQQ__Quote__c = q.Id;
		insert cont;
					
		SBQQ__Subscription__c sub = TestingUtils.createSubscription(a.Id, cont.Id, p.Id);
		sub.SBQQ__QuoteLine__c = quoteLine.Id;
		insert sub;
		//System.debug('Product = ' + sub.SBQQ__Product__c + ' Product Family = ' + sub.Product_Family__c + ' Com Product = ' + sub.Commissionable_Product__c + ' Opp Type = ' + sub.Opp_Type__c);
		
		Asset ass1 = TestingUtils.createAsset(a.Id, p.Id);
		ass1.SBQQ__QuoteLine__c = quoteLine.Id;
		insert ass1;*/
				
		Test.startTest();
		
		Database.executeBatch(new batchRenewalTotals(), 1);
		
		Test.stopTest();
		
	}
	
	
	

	
}