CS_SBOX_20150209_01/Metadata/unpackaged/objects/BDC_Activity_Type__c.object
<CustomObject>
    <description>Hold the Activity Types for the BDC Activities that should be created from a Renewal Opp</description>
    <fields>
        <fullName>Call_Template__c</fullName>
        <description>The template for the Renewal Call</description>
        <label>Call Template</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>BDC Activity Type</label>
    <nameField>
        <label>BDC Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BDC Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/ShowCallTemplateController.cls
public with sharing class ShowCallTemplateController
{
	public final BDC_Activity_Type__c ActivityType {get; Set;}
	public Boolean DisplayTemplate {get; Set;}

	public ShowCallTemplateController()
	{
		DisplayTemplate = false;
        Task t = [SELECT Id, Renewal_Phone_Call_Templates__c FROM Task WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
		
		if (t.Renewal_Phone_Call_Templates__c != null)
		{
			ActivityType = [Select Id, Call_Template__c from BDC_Activity_Type__c where Id = :t.Renewal_Phone_Call_Templates__c];
		
			if (ActivityType != null)
			{
				DisplayTemplate = true;
			}
		}
    }
}