CS_SBOX_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Id__c</fullName>
        <label>Contract Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <description>Added by LM on 3/4/2013; From MS CRM</description>
        <label>Contract Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/ContractHelper.cls
public class ContractHelper
{
	public static List<SObject> objectsToUpdate = new List<SObject>();
	
	public static void AddContractNumberToOpportunity(List<Contract> contractsList)
	{
		Set<Id> oppIds = new Set<Id>();
				
		for (Contract c : contractsList)
		{
			if(c.SBQQ__Opportunity__c != null)
			{
				oppIds.add(c.SBQQ__Opportunity__c);
			}
		}
			
		Map<Id, Opportunity> oppsMap = new Map<Id, Opportunity>([Select Id, Contract_Id__c, Contract_Number__c from Opportunity Where Id in :oppIds]);		
		List<Opportunity> oppsToUpdate = new List<Opportunity>();
		for (Contract c : contractsList)
		{
			Opportunity o = oppsMap.get(c.SBQQ__Opportunity__c);
						
			if (o != null)
			{							
				o.Contract_Number__c = c.ContractNumber;
				o.Contract_Id__c = c.Id;
				oppsToUpdate.add(o);
			}
			
		}
		
		update oppsToUpdate;
	}
	
	

}