CS_SBOX_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote that generated this contract.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Discount_Amount_for_Approval__c</fullName>
        <label>Discount Amount for Approval</label>
        <summarizedField>SBQQ__QuoteLine__c.Discount_Amount_for_Approval__c</summarizedField>
        <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Discount_Percent_for_Approval__c</fullName>
        <formula>IF( SBQQ__ListAmount__c &lt;&gt; 0 ,
  Discount_Amount_for_Approval__c /  SBQQ__RegularAmount__c ,
  0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Percent for Approval</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__AdditionalDiscountAmount__c</fullName>
        <description>Amount of additional discount on this quote.</description>
        <formula>SBQQ__RegularAmount__c - SBQQ__CustomerAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount additionally discounted on this quote manually.</inlineHelpText>
        <label>Addl. Disc. Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Subscription term used to prorate eligible products.</description>
        <inlineHelpText>Subscription term used to prorate eligible products.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Type of quote</description>
        <inlineHelpText>Type of quote</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quote</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Discount_Amount_for_Approval__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Field populated by WFR. Do not use for data entry.</description>
        <inlineHelpText>Field populated by WFR. Do not use for data entry.</inlineHelpText>
        <label>Discount Amount for Approval</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__AdditionalDiscountAmount__c</fullName>
        <description>Additional customer discount extended on this line item in terms of absolute amount.</description>
        <inlineHelpText>Additional customer discount extended on this line item in the form of an absolute amount.</inlineHelpText>
        <label>Additional Disc. (Amt)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item.</description>
        <inlineHelpText>List unit price for the product quoted by this line item.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term for the subscription product in this line. If the product is not a subscription this value has no effect.</description>
        <inlineHelpText>Term for this subscription. If this product is not a subscription this value has no effect.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/TestUnlockQuoteExtension.cls
@isTest
private class TestUnlockQuoteExtension
{
	/*static void TestRecallApproval()
	{
		TestingUtils.InitAvaTax();
		
		List<Account> accounts = TestingUtils.createAccounts(1, false);      
        insert accounts;
		
		Contact cont = TestingUtils.createAgent(accounts[0].Id, 'Test2', '222222', false);
		insert cont;
		
        Opportunity opp = TestingUtils.createOpportunity(accounts[0].Id);
		opp.StageName = 'Qualified';
		insert opp;
		
		OpportunityContactRole ocr = TestingUtils.createOpportunityContactRole(opp.Id, cont.Id);
		insert ocr;
		
		SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Primary__c = true, SBQQ__Status__c = 'Draft', SBQQ__SubscriptionTerm__c = 12, 
			SBQQ__StartDate__c = Date.today(), Payment_Type__c = 'Credit Card', SBQQ__Opportunity__c = opp.Id, SBQQ__Type__c = 'Quote');
		insert quote;
		
        Product2 p = TestLibrary.createProduct('test', 'test', 'test');
        insert p;
        
        SBQQ__QuoteLine__c ql = TestLibrary.createQuoteLine(quote.Id, p.Id);
        ql.SBQQ__ListPrice__c = 4000;
        ql.SBQQ__Quantity__c = 1;
        ql.SBQQ__AdditionalDiscountAmount__c = 30;
        insert ql;
 
        System.Debug('############################Discount Amount for Approval = ' + quote.Discount_Amount_for_Approval__c);
        System.Debug('############################Discount Percent for Approval = ' + quote.Discount_Percent_for_Approval__c );
		Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
		req.setComments('Quote Submitted for approval. Please approve.');
		req.setObjectId(quote.Id);
		Approval.process(req);
		
		Test.startTest();
			PageReference pageRef = Page.UnlockQuote;
			pageRef.GetParameters().put('id', quote.Id);
        	Test.setCurrentPage(pageRef); 
		
			ApexPages.StandardController controller = new ApexPages.StandardController(quote); 
        	UnlockQuoteExtension extension = new UnlockQuoteExtension(controller);
			extension.UnlockQuote();		
		
		Test.stopTest();
	}*/
    
    static testmethod void TestUnlockContractRejected()
	{
		TestingUtils.InitAvaTax();
		
		List<Account> accounts = TestingUtils.createAccounts(1, false);      
        insert accounts;
		
		Contact cont = TestingUtils.createAgent(accounts[0].Id, 'Test2', '222222', false);
		insert cont;
		
        Opportunity opp = TestingUtils.createOpportunity(accounts[0].Id);
		opp.StageName = 'Cust: Contract Rejected';
		insert opp;
		
        OpportunityContactRole ocr = TestingUtils.createOpportunityContactRole(opp.Id, cont.Id);
		insert ocr;
		
		SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Primary__c = true, SBQQ__Status__c = 'Draft', SBQQ__SubscriptionTerm__c = 12, 
			SBQQ__StartDate__c = Date.today(), Payment_Type__c = 'Credit Card', SBQQ__Opportunity__c = opp.Id, SBQQ__Type__c = 'Quote');
		insert quote;
        
		Test.startTest();
			PageReference pageRef = Page.UnlockQuote;
			pageRef.GetParameters().put('id', quote.Id);
        	Test.setCurrentPage(pageRef); 
		
			ApexPages.StandardController controller = new ApexPages.StandardController(quote); 
        	UnlockQuoteExtension extension = new UnlockQuoteExtension(controller);
			extension.UnlockQuote();		
		
		Test.stopTest();
	}
    
    static testmethod void TestUnlockAPPRejected()
	{
		TestingUtils.InitAvaTax();
		
		List<Account> accounts = TestingUtils.createAccounts(1, false);      
        insert accounts;
		
		Contact cont = TestingUtils.createAgent(accounts[0].Id, 'Test2', '222222', false);
		insert cont;
		
        Opportunity opp = TestingUtils.createOpportunity(accounts[0].Id);
		opp.StageName = 'APP: Rejected';
		insert opp;
		 
        OpportunityContactRole ocr = TestingUtils.createOpportunityContactRole(opp.Id, cont.Id);
		insert ocr;
		
		SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Primary__c = true, SBQQ__Status__c = 'Draft', SBQQ__SubscriptionTerm__c = 12, 
			SBQQ__StartDate__c = Date.today(), Payment_Type__c = 'Credit Card', SBQQ__Opportunity__c = opp.Id, SBQQ__Type__c = 'Quote');
		insert quote;
        
		Test.startTest();
			PageReference pageRef = Page.UnlockQuote;
			pageRef.GetParameters().put('id', quote.Id);
        	Test.setCurrentPage(pageRef); 
		
			ApexPages.StandardController controller = new ApexPages.StandardController(quote); 
        	UnlockQuoteExtension extension = new UnlockQuoteExtension(controller);
			extension.UnlockQuote();		
		
		Test.stopTest();
	}
}