CS_SBOX_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Renewal opportunity generated to track the renewal of this contract.</description>
        <inlineHelpText>Renewal opportunity generated to track the renewal of this contract.</inlineHelpText>
        <label>Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Contracts</relationshipLabel>
        <relationshipName>RenewedContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalPricebookId__c</fullName>
        <description>ID of price book to use when renewing this contract.</description>
        <inlineHelpText>ID of price book to use when renewing this contract.</inlineHelpText>
        <label>Renewal Pricebook Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/replaceProductHelper.cls
public with sharing class replaceProductHelper {
	
	public static Map<Id,Contract> contractMap = new Map<Id,Contract>();
	
	public static Map<Id,Contract> processReplaceProduct(Id currentProduct, Id replaceProductId, Id replacePricebookId){
		
		Set<Id> opIds = new Set<Id>();
		List<OpportunityLineItem> OLIresults = new List<OpportunityLineItem>();
	 	
	 	List<Opportunity> oppList = [Select Id From Opportunity Where isClosed= false AND Type = 'Renewal' AND pricebook2id = :replacePricebookId];
	 	
	 	if(!oppList.isEmpty()){
	 		for(Opportunity o : oppList){
	 			opIds.add(o.Id);
	 		}
	 	}
	 	
	 	List<Contract> contractList = [Select Id, SBQQ__Opportunity__c, SBQQ__RenewalOpportunity__c, SBQQ__RenewalPricebookId__c from Contract 
                                                  WHERE SBQQ__RenewalOpportunity__c IN :opIds];
        
        if(!contractList.isEmpty()){
        	for(Contract c : contractList){
        		contractMap.put(c.SBQQ__RenewalOpportunity__c,c);
        	}
        }
        
        return contractMap;
	}

}