CS_SBOX_20150209_01/Metadata/unpackaged/objects/fw1__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>fw1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Alternate_Invoice_Number__c</fullName>
        <label>External Invoice Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Balance_Due__c</fullName>
        <formula>fw1__Total_Invoice_Amount__c  -  fw1__Total_Paid_Amount__c -  fw1__Authorized_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_State__c</fullName>
        <label>Billing State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_Street__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_Zip__c</fullName>
        <label>Billing Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.fw1__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Domain_Name__c</fullName>
        <label>Domain Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Email_Currency_Symbol__c</fullName>
        <label>Email Currency Symbol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Pending_Auto_Bill_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pending Auto Bill Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>fw1__Recipient_Email__c</fullName>
        <label>Recipient Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>fw1__Retry_Date__c</fullName>
        <label>Retry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_Country__c</fullName>
        <label>Shipping Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_Zip__c</fullName>
        <label>Shipping Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Paid_Amount__c</fullName>
        <label>Total Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw2__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Invoice</fullName>
        <active>true</active>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/fw1__Payment__c.object
<CustomObject>
    <fields>
        <fullName>fw1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Auto_BillPay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-BillPay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>fw1__Bank_Aba_Code__c</fullName>
        <inlineHelpText>Bank Routing Number</inlineHelpText>
        <label>Bank ABA Code</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>fw1__Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>30</length>
        <maskChar>X</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_State__c</fullName>
        <label>Billing State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_Street__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fw1__Billing_Zip__c</fullName>
        <label>Billing Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>19</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>fw1__Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>fw1__Domain_Name__c</fullName>
        <label>Domain Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Email_Currency_Symbol__c</fullName>
        <label>Email Currency Symbol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>fw1__Expiry_Month__c</fullName>
        <label>Expiry Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>fw1__Expiry_Year__c</fullName>
        <label>Expiry Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>fw1__Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Name_On_Account__c</fullName>
        <label>Name On Account</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Payment_Date__c</fullName>
        <label>Payment Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>fw1__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Payment_Processor__c</fullName>
        <label>Payment Processor</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_Country__c</fullName>
        <label>Shipping Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_Zip__c</fullName>
        <label>Shipping Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Paid_Amount__c</fullName>
        <description>This field contains the actual/net amount paid (i.e. minus refunds, voids, authorizations, etc.)</description>
        <formula>IF(OR(fw1__Payment_Method__c=&apos;Credit Card&apos;,fw1__Payment_Method__c=&apos;eCheck&apos;),  IF( fw1__Status__c  = &apos;Voided&apos;, 0,  fw1__Total_Captured_Amount__c  -  fw1__Total_Refunded_Amount__c),  fw1__Amount__c  -  fw1__Total_Refunded_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Charge</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Authorization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>fw1__eCheck_Type__c</fullName>
        <label>eCheck Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Opportunity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Sale</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/InvoicePayment.cls
public with sharing class InvoicePayment {
  @future (callout=true)
  public static void doPayment(id invId){
  	
  	fw1__Payment__c payment = new fw1__Payment__c();
  	fw1__Invoice__c invoice = getInvoice(invId);
  	fw1__Payment_Center_Setting__c setting = getPaymentSettings();
  	fw1__PaymentProfile__c profile = getPaymentProfile(invoice.fw1__Account__c);
    string processor = getDefaultPaymentProcessor();
    string paymentType = setting.fw1__Online_Payment_Type__c;
    
    
    if (processor != null && paymentType != null) {
        payment.fw1__Payment_Processor__c = processor;
        
                   
        if (invoice.fw1__Alternate_Invoice_Number__c != null) {
            payment.Name = 'Payment for ' + invoice.fw1__Alternate_Invoice_Number__c;
        } else {
            payment.Name = 'Payment for ' + invoice.Name;
        }
               
        payment.fw1__Amount__c = invoice.fw1__Balance_Due__c;
        payment.fw1__Type__c = paymentType;
        
        system.debug('===>' + payment.fw1__Payment_Processor__c + ';' + payment.fw1__Type__c + ';' + string.valueOf(payment.fw1__Amount__c));
        payment.fw1__Payment_Date__c = System.Now();
        payment.fw1__Invoice__c = invoice.Id;
        payment.fw1__Account__c = invoice.fw1__Account__c;
        payment.fw1__Contact__c = invoice.fw1__Contact__c;
        payment.fw1__Opportunity__c = invoice.fw2__Opportunity__c;
        payment.fw1__Email__c = invoice.fw1__Recipient_Email__c;
        payment.fw1__Auto_BillPay__c = true;
        payment.fw1__Email_Currency_Symbol__c = setting.fw1__Email_Currency_Symbol__c;  
        if (invoice.fw1__Billing_Street__c != null) {
		      payment.fw1__Billing_Street__c = invoice.fw1__Billing_Street__c;
		      payment.fw1__Billing_City__c = invoice.fw1__Billing_City__c;
		      payment.fw1__Billing_State__c = invoice.fw1__Billing_State__c;
		      payment.fw1__Billing_Zip__c = invoice.fw1__Billing_Zip__c;
		      payment.fw1__Billing_Country__c = invoice.fw1__Billing_Country__c;
        }  
        if (invoice.fw1__Shipping_Street__c != null) {
          payment.fw1__Shipping_Street__c = invoice.fw1__Shipping_Street__c;
          payment.fw1__Shipping_City__c = invoice.fw1__Shipping_City__c;
          payment.fw1__Shipping_State__c = invoice.fw1__Shipping_State__c;
          payment.fw1__Shipping_Zip__c = invoice.fw1__Shipping_Zip__c;
          payment.fw1__Shipping_Country__c = invoice.fw1__Shipping_Country__c;
        }
        if (profile.fw1__Bank_Account_Number__c != null){
          payment.fw1__Payment_Method__c = 'eCheck';
        } else {
          payment.fw1__Payment_Method__c = 'Credit Card';
        }
        if (payment.fw1__Payment_Method__c == 'Credit Card' || payment.fw1__Payment_Method__c == null) {
            payment.fw1__Credit_Card_Type__c = profile.fw1__CreditCardType__c;
            payment.fw1__First_Name__c = profile.fw1__First_Name__c;
            payment.fw1__Last_Name__c = profile.fw1__Last_Name__c;
            payment.fw1__Credit_Card_Number__c = profile.fw1__CreditCardNumber__c;
            payment.fw1__Expiry_Month__c = profile.fw1__ExpiryMonth__c;
            payment.fw1__Expiry_Year__c = profile.fw1__ExpiryYear__c;
        } else if (payment.fw1__Payment_Method__c == 'eCheck') {
            payment.fw1__Bank_ABA_Code__c = profile.fw1__Bank_ABA_Code__c;
            payment.fw1__Bank_Account_Number__c = profile.fw1__Bank_Account_Number__c;
            payment.fw1__Name_On_Account__c = profile.fw1__Name_On_Account__c;
            payment.fw1__ECheck_Type__c = 'WEB';
            payment.fw1__Type__c = 'Charge';                     
        }
        PaymentValidator validator = new PaymentValidator();
        
        Boolean isSuccessful;
        if(validator.DoValidate(payment)){
          isSuccessful = fw1.PaymentProcessor.doPayment(payment);
                 
        } else {
        	isSuccessful = false;
        }
        updateOpportunityStatus(invoice.fw2__Opportunity__c,isSuccessful);
        
    }
  }
  
  private static void updateOpportunityStatus(Id oppId, boolean isSuccessful){
  	string CLOSED = 'Closed';
    string PAYMENTERROR = 'Payment Error';
    
     Opportunity o;
     try{
         o = [SELECT Name,Opportunity_Status__c
              FROM Opportunity
              WHERE Id = :oppId
              LIMIT 1];
     } catch (Exception e) { }
     
     if (isSuccessful)
        o.Opportunity_Status__c = CLOSED;
     else
        o.Opportunity_Status__c = PAYMENTERROR;
     
     update o;
  }
  
  private static fw1__Invoice__c getInvoice(id invId){
  	
  	return [SELECT Name, Id,fw1__Balance_Due__c, fw1__Retry_Date__c, fw1__Total_Paid_Amount__c,
  	       fw1__Pending_Auto_Bill_Pay__c, fw1__Alternate_Invoice_Number__c,
  	       fw1__Account__c,fw1__Contact__c,fw1__Billing_Street__c,
  	       fw1__Billing_City__c,fw1__Billing_State__c,fw1__Billing_Zip__c,
  	       fw1__Billing_Country__c,fw1__Shipping_Street__c,fw1__Shipping_City__c,
  	       fw1__Shipping_State__c,fw1__Shipping_Zip__c,fw1__Shipping_Country__c,
  	       fw2__Opportunity__c,fw1__Recipient_Email__c
           FROM fw1__Invoice__c
           WHERE Id = :invId];
  }
  
  private static fw1__Payment_Center_Setting__c getPaymentSettings(){
    return 
      [SELECT 
         fw1__Default_Email_Subject__c, fw1__Default_Email_Message__c, 
         fw1__Default_Terms_And_Conditions__c,
         fw1__Online_Payment_Type__c,  
         fw1__Domain_Name__c,  fw1__Email_Currency_Symbol__c,
         fw1__Sender_Display_Name__c,
         fw1__Failed_Attempt1__c,fw1__Failed_Attempt2__c,
         fw1__Failed_Attempt3__c,fw1__Failed_Attempt_Final__c     
      FROM fw1__Payment_Center_Setting__c
      WHERE Name = 'Default Settings'
      LIMIT 1];
  }
  
  private static string getDefaultPaymentProcessor() {
    String defaultPaymentProcessor = '';
        
    fw1__Payment_Processor__c pProcessor = new fw1__Payment_Processor__c();
    try {
      pProcessor = [SELECT Name
                    FROM fw1__Payment_Processor__c
                    WHERE fw1__Use_As_Default__c = true
                    LIMIT 1];
      defaultPaymentProcessor = pProcessor.Name;
    } catch (Exception e) {
        System.Debug('There is no default Payment Processor: ' + e);
        try {
                pProcessor = [SELECT Name
                                FROM fw1__Payment_Processor__c
                               LIMIT 1];
                defaultPaymentProcessor = pProcessor.Name;
          } catch (Exception ex) {
                System.Debug('There are no Payment Processors.' + ex);
          }
    }
    return defaultPaymentProcessor;
  }
  
  private static fw1__PaymentProfile__c getPaymentProfile(id accountId){
    List<fw1__PaymentProfile__c> profiles = new List<fw1__PaymentProfile__c>();
    
    profiles = [SELECT Name,Id, fw1__Name_On_Account__c, fw1__Last_Name__c, fw1__First_Name__c, 
                  fw1__ExpiryYear__c, fw1__ExpiryMonth__c, fw1__CreditCardType__c, fw1__CreditCardNumber__c, 
                  fw1__Bank_Account_Number__c, fw1__Bank_ABA_Code__c
                FROM fw1__PaymentProfile__c
                WHERE fw1__Account__c = :accountId
                AND fw1__UseAsDefault__c = true
                LIMIT 1]; 
                
    if (profiles.size() > 0) 
      return profiles[0];
    else 
    	 return null;
   
  }
           
}