CS_SBOX_20150209_01/Metadata/unpackaged/objects/fw1__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>fw1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Authorized_Amount__c</fullName>
        <label>Authorized Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Balance_Due__c</fullName>
        <formula>fw1__Total_Invoice_Amount__c  -  fw1__Total_Paid_Amount__c -  fw1__Authorized_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>fw1__Email_Currency_Symbol__c</fullName>
        <label>Email Currency Symbol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Invoice_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>fw1__Invoice_Discount_Amount__c</fullName>
        <label>Invoice Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Invoice_Discount_Percentage__c</fullName>
        <label>Invoice Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>fw1__Net_Amount__c</fullName>
        <formula>fw1__Total_Lines_Amount__c - fw1__Total_Invoice_Discount_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Required_Down_Payment_Amount__c</fullName>
        <inlineHelpText>You can enter the required down payment amount here.</inlineHelpText>
        <label>Required Down Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Required_Down_Payment__c</fullName>
        <inlineHelpText>You can enter the required down payment percentage here.</inlineHelpText>
        <label>Required Down Payment %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_And_Handling__c</fullName>
        <inlineHelpText>Shipping And Handling Amount</inlineHelpText>
        <label>Shipping And Handling</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Tax__c</fullName>
        <inlineHelpText>Tax Percentage</inlineHelpText>
        <label>Tax</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Invoice_Amount__c</fullName>
        <formula>ROUND(fw1__Revolving_Balance__c + 
fw1__Net_Amount__c + 
( fw1__Net_Amount__c  *  fw1__Tax__c ) +  
fw1__Shipping_And_Handling__c + 
((IF(fw1__Net_Amount__c &gt; fw1__Total_Non_Installment__c, 
     fw1__Net_Amount__c - fw1__Total_Non_Installment__c, 
     0))  *   fw1__Installment_Fee__c ),2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Invoice_Discount_Amount__c</fullName>
        <formula>( fw1__Total_Lines_Amount__c  *  fw1__Invoice_Discount_Percentage__c ) +  fw1__Invoice_Discount_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Invoice Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Lines_Amount__c</fullName>
        <label>Total Lines Amount</label>
        <summarizedField>fw1__Invoice_Line__c.fw1__Amount__c</summarizedField>
        <summaryForeignKey>fw1__Invoice_Line__c.fw1__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Lines_Discount_Amount__c</fullName>
        <label>Total Lines Discount Amount</label>
        <summarizedField>fw1__Invoice_Line__c.fw1__Discount_Amount__c</summarizedField>
        <summaryForeignKey>fw1__Invoice_Line__c.fw1__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Lines_Discount_Percentage__c</fullName>
        <label>Total Lines Discount Percentage</label>
        <summarizedField>fw1__Invoice_Line__c.fw1__Discount_Percentage__c</summarizedField>
        <summaryForeignKey>fw1__Invoice_Line__c.fw1__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Lines_Discount_Quantity__c</fullName>
        <label>Total Lines Discount Quantity</label>
        <summarizedField>fw1__Invoice_Line__c.fw1__Discount_Quantity__c</summarizedField>
        <summaryForeignKey>fw1__Invoice_Line__c.fw1__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Paid_Amount__c</fullName>
        <label>Total Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Invoice</fullName>
        <active>true</active>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/fw1__Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Air_Date__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Air_Time__c</fullName>
        <label>Air Time</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_and_Station__c</fullName>
        <label>Market and Station</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Title__c</fullName>
        <label>Program Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fw1__Amount__c</fullName>
        <formula>fw1__Net_Amount__c  +  fw1__Sales_Tax__c +  fw1__Shipping_And_Handling__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>fw1__Discount_Quantity__c</fullName>
        <label>Discount Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fw1__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>fw1__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>fw1__Item_Description__c</fullName>
        <label>Item Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fw1__Net_Amount__c</fullName>
        <formula>ROUND(( ( fw1__Quantity__c - fw1__Discount_Quantity__c ) * fw1__Unit_Price__c ) - fw1__Total_Discount_Amount__c,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Paid_Amount__c</fullName>
        <label>Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fw1__Recurring_Invoice_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Invoice Line</label>
        <referenceTo>fw1__Recurring_Invoice_Line__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fw1__Sales_Tax_Rate__c</fullName>
        <label>Sales Tax Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>fw1__Sales_Tax__c</fullName>
        <formula>IF( fw1__Taxable__c, fw1__Net_Amount__c  *  fw1__Sales_Tax_Rate__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Shipping_And_Handling__c</fullName>
        <label>Shipping And Handling</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Taxable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Taxable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>fw1__Total_Discount_Amount__c</fullName>
        <formula>((( fw1__Quantity__c  -  fw1__Discount_Quantity__c ) *  fw1__Unit_Price__c ) *  fw1__Discount_Percentage__c)
+
fw1__Discount_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>fw1__Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <label>Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/PaymentReceiptPDFCntroller.cls
public with sharing class PaymentReceiptPDFCntroller {
  private string m_InvoiceId;
  public String InvoiceId {
    get{ return m_InvoiceId;} 
    set{ 
      m_InvoiceId = value;
      setInvoice();
      setInvoiceLine();
    }
  }
  
  public fw1__Invoice__c Invoice {get;set;}
  public List<fw1__Invoice_Line__c> InvoiceLines {get;set;}
  
  private void setInvoice(){
    Invoice = new fw1__Invoice__c();
    Invoice = [SELECT 
                    fw1__Total_Paid_Amount__c,
                    fw1__Total_Lines_Discount_Quantity__c, 
                    fw1__Total_Lines_Discount_Percentage__c, 
                    fw1__Total_Lines_Discount_Amount__c, 
                    fw1__Total_Lines_Amount__c, 
                    fw1__Total_Invoice_Discount_Amount__c, 
                    fw1__Total_Invoice_Amount__c, 
                    fw1__Net_Amount__c, 
                    fw1__Invoice_Discount_Percentage__c, 
                    fw1__Invoice_Discount_Amount__c, 
                    fw1__Invoice_Date__c, 
                    fw1__Email_Currency_Symbol__c, 
                    fw1__Due_Date__c, 
                    fw1__Balance_Due__c,
                    fw1__Tax__c,
                    fw1__Shipping_And_Handling__c,
                    fw1__Authorized_Amount__c,
                    fw1__Required_Down_Payment__c,
                    fw1__Required_Down_Payment_Amount__c,
                    Name
                  FROM fw1__Invoice__c WHERE Id = :InvoiceId]; 
  }
  
  private void setInvoiceLine(){
    InvoiceLines = new List<fw1__Invoice_Line__c>();
    InvoiceLines = [SELECT 
                         fw1__Unit_Price__c, 
                         fw1__Total_Discount_Amount__c, 
                         fw1__Taxable__c, 
                         fw1__Sales_Tax__c, 
                         fw1__Sales_Tax_Rate__c, 
                         fw1__Recurring_Invoice_Line__c, 
                         fw1__Quantity__c, 
                         fw1__Paid_Amount__c, 
                         fw1__Net_Amount__c, 
                         fw1__Item_Description__c, 
                         fw1__Invoice__c, 
                         fw1__Discount_Quantity__c, 
                         fw1__Discount_Percentage__c, 
                         fw1__Discount_Amount__c, 
                         fw1__Amount__c,  
                         Name, Id,
                         Air_Date__c,
                         Air_Time__c,
                         Market_and_Station__c,
                         Program_Title__c
                         FROM fw1__Invoice_Line__c 
                        WHERE fw1__Invoice__c = :InvoiceId];
    
  }
  
  public boolean getDisplayRequiredDownPayment(){
    if (Invoice.fw1__Required_Down_Payment__c == null)
     Invoice.fw1__Required_Down_Payment__c = 0;
     
    return ((Invoice.fw1__Total_Paid_Amount__c < 
    (Invoice.fw1__Total_Invoice_Amount__c * (Invoice.fw1__Required_Down_Payment__c / 100)))) && 
    (Invoice.fw1__Required_Down_Payment_Amount__c == null && Invoice.fw1__Required_Down_Payment__c > 0);
  }
  
  public boolean getDisplayDownPaymentAmount(){
    if (Invoice.fw1__Required_Down_Payment_Amount__c == null)
     Invoice.fw1__Required_Down_Payment_Amount__c = 0;
    return (Invoice.fw1__Total_Paid_Amount__c < Invoice.fw1__Required_Down_Payment_Amount__c) && (Invoice.fw1__Required_Down_Payment_Amount__c > 0);
  }
  
  public boolean getDisplaySubTotal(){
    return(Invoice.fw1__Invoice_Discount_Amount__c != 0 && Invoice.fw1__Invoice_Discount_Amount__c != null ||
           Invoice.fw1__Invoice_Discount_Percentage__c != 0 && Invoice.fw1__Invoice_Discount_Percentage__c != null ||
           Invoice.fw1__Tax__c != 0 && Invoice.fw1__Tax__c != null ||
           Invoice.fw1__Shipping_And_Handling__c != 0 && Invoice.fw1__Shipping_And_Handling__c != null);
  }
  
  
  @isTest    
  public static void testDoPayment(){
    PaymentReceiptPDFCntroller p = new PaymentReceiptPDFCntroller();
    /*
    Account a = new Account();
    a.Name = 'Test Account';
    a.BillingStreet = '123 oak st';
    a.BillingCity = 'torrance';
    a.BillingPostalCode = '90501';
    a.BillingCountry = 'USA';
    insert a;
    
    fw1__Invoice__c inv = new fw1__Invoice__c();
    inv.fw1__Account__c = a.Id;
    inv.fw1__Invoice_Date__c = Date.today();
    insert inv;
    
    p.InvoiceId = inv.id; 
    
    Boolean b;
    b = p.getDisplayRequiredDownPayment();
    b = p.getDisplayDownPaymentAmount();
    b = p.getDisplaySubTotal();
    */
  }
  
}