CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>At_Risk__c</fullName>
        <description>Created by LM on 9/26/2013 for Phase 2 rollout</description>
        <label>At Risk?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CA_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 12/3/2013 for Phase 2 rollout</description>
        <label>CA Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Services_Tasks_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Services Tasks Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Created_Date_Time__c</fullName>
        <label>Created Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Credit_Risk_Case_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has a case been created to assess the credit risk for the Opportunity</description>
        <label>Credit Risk Case Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GAS_or_Managed_Service_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GAS or Managed Service Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GP_Cust_ID__c</fullName>
        <formula>Account.GP_Cust_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GP Cust ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Year_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <inlineHelpText>For assigning Renewals only</inlineHelpText>
        <label>Last Year Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Year_Spend__c</fullName>
        <label>Last Year Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Renewal_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/31/2013 for Phase 2 rollout</description>
        <label>New Renewal Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Products__c</fullName>
        <label>Number of Products</label>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Opportunity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Sale</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Passed_to_Softrax__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 12/12/13 for da Phase 2</description>
        <label>Passed to Softrax?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previous_Year_s_Last_Year_Spend__c</fullName>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <inlineHelpText>For assigning Renewals only: this is the Last Year Spend value on the previous year&apos;s Renewal Opp.</inlineHelpText>
        <label>Previous Year’s Last Year Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Added by LM on 3/4/2013; From MS CRM</description>
        <label>Reason - At Risk</label>
        <picklist>
            <picklistValues>
                <fullName>Budget Objection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Threat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Responsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (See Notes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Issue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gets checked by the Renewal Process from the Contract</description>
        <label>Renewal Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Due_Date__c</fullName>
        <description>Created by LM on 8/31/2013 for Phase 2 rollout</description>
        <label>Renewal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep_Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal Rep Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Tasks_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is set automatically after all the Renewal Tasks have completed to avoid them being duplicated</description>
        <label>Renewal Tasks Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
        <inlineHelpText>QuoteQuickly uses this field to automatically convert assets and subscriptions.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Last_Touched_Date__c</fullName>
        <description>Created by LM on 5/6/2014 for Phase2</description>
        <label>Sales Last Touched Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Account Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_At_Risk_Case_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training At Risk Case Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_Order_Cases_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training Order Cases Created</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Renewals</fullName>
        <active>true</active>
        <businessProcess>Subscription Sales Process</businessProcess>
        <label>Renewals</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/batchProcessOpportunities.cls
global class batchProcessOpportunities implements Database.Batchable<sObject>, Schedulable
{ 	
	String IdtoProcess = '';
	
	global batchProcessOpportunities()
	{
		
	}
	
	global batchProcessOpportunities(String Id)
	{
		IdtoProcess = Id;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC)         
    {
        List<RecordType> rtList = [select Id, Name, SObjectType from RecordType where SObjectType = 'Opportunity' and (Name = 'New Biz' or Name = 'Renewals' or Name = 'Locked New Biz' or Name = 'Locked Renewals')];
		Id OpportunityNewBizRecordType = null;
        Id OpportunityRenewalsRecordType = null;
		Id OpportunityLockedNewBizRecordType = null;
        Id OpportunityLockedRenewalsRecordType = null;
        
        if (rtList != null && rtList.size() > 0)
		{
            for (RecordType r : rtList)
			{
				if (r.Name == 'New Biz')
				{
					OpportunityNewBizRecordType = r.Id;
				}
				else if (r.Name == 'Renewals')
				{
					OpportunityRenewalsRecordType = r.Id;
				}
				else if (r.Name == 'Locked New Biz')
				{
					OpportunityLockedNewBizRecordType = r.Id;
				}
				else if (r.Name == 'Locked Renewals')
				{
					OpportunityLockedRenewalsRecordType = r.Id;
				}
			}
		}
        
		DateTime dt = Datetime.now().addMinutes(-5);  //DateTime dt = system.today().addMinutes(-55);  //
		System.debug('DateTime = ' + dt);
		
		String query = 'select Id, Owner.IsActive, Amount, CloseDate, Owner.Name, GAS_or_Managed_Service_Check__c, SBQQ__Contracted__c, Reason__c, CA_Rep__c, Sub_Account__c, GP_Cust_ID__c, Number_of_Products__c, Credit_Risk_Case_Created__c, Client_Services_Tasks_Created__c, Shipping_State__c, Training_At_Risk_Case_Created__c, Training_Order_Cases_Created__c, RecordTypeId, StageName, Opportunity.At_Risk__c, Renewal_Completed__c, AccountId, Opportunity_Status__c, Type, OwnerId, Renewal_Rep_Assigned__c, CreatedDate, Renewal_Due_Date__c, Renewal_Tasks_Completed__c, Last_Year_Spend__c, Sales_Last_Touched_Date__c, Last_Year_Owner__c, Previous_Year_s_Last_Year_Spend__c, New_Renewal_Customer__c, Passed_to_Softrax__c from Opportunity where ';
        if (IdtoProcess == '')
		{
			query += '((At_Risk__c = \'Yes\' and RecordTypeId = \'' + OpportunityRenewalsRecordType + '\' and Training_At_Risk_Case_Created__c = False) ';
        	query += 'or (StageName = \'Closed Won\' and Passed_to_Softrax__c = false and (RecordTypeId = \'' + OpportunityRenewalsRecordType + '\' or RecordTypeId = \'' + OpportunityNewBizRecordType + '\' or RecordTypeId = \'' + OpportunityLockedRenewalsRecordType + '\' or RecordTypeId = \'' + OpportunityLockedNewBizRecordType + '\') and (Training_Order_Cases_Created__c = False or Client_Services_Tasks_Created__c = False)) ';
        	query += 'or (Credit_Risk_Case_Created__c = False and Number_of_Products__c > 0 and GP_Cust_ID__c = null) or (StageName = \'Closed Won\' and GAS_or_Managed_Service_Check__c = false)) and Owner.IsActive = true';
			System.debug('query = ' + query);
		}
		else
		{
			query += 'Id = \'' + IdtoProcess + '\'';
		}
		
    	return Database.getQueryLocator(query);		
		//[select Id, AccountId, Opportunity_Status__c, Type, OwnerId, Renewal_Rep_Assigned__c, Renewal_Due_Date__c, Renewal_Tasks_Completed__c, Last_Year_Spend__c, Sales_Last_Touched_Date__c, Last_Year_Owner__c, Previous_Year_s_Last_Year_Spend__c, New_Renewal_Customer__c from Opportunity where Type = 'Renewal' and Renewal_Completed__c = false and Created_Date_Time__c < :dt]
    }

	global void execute(Database.batchableContext bc, List<SObject> scope)
	{		
		if(scope != null)
		{
			OpportunityHelper.CreateTrainingCases((List<Opportunity>)scope);
        	OpportunityHelper.CreateClientServicesCases((List<Opportunity>)scope);    
       		OpportunityHelper.CreateCreditRiskAssessmentCase((List<Opportunity>)scope);
			OpportunityHelper.UpdatePassedToSoftraxFlag((List<Opportunity>)scope);
			OpportunityHelper.SendGASorManagedServicesEmail((List<Opportunity>)scope);
						
			update scope;
		}
	}

	global void finish(Database.batchableContext info)
	{
	}
	
	global void execute(SchedulableContext ctx)
	{
        Database.executeBatch(new batchProcessOpportunities(), 50);
    }
}