CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>At_Risk__c</fullName>
        <description>Created by LM on 9/26/2013 for Phase 2 rollout</description>
        <label>At Risk?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Commissionable_Potential__c</fullName>
        <description>Added by LM on 3/4/2013; From MS CRM</description>
        <inlineHelpText>This total=Last Year&apos;s Renewable Products-Last Year&apos;s Non-Commissionable Products</inlineHelpText>
        <label>Commissionable Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Renewal_Due_Date__c</fullName>
        <description>Created by LM on 8/31/2013 for Phase 2 rollout</description>
        <label>Renewal Due Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Round_Robin__c.object
<CustomObject>
    <description>This Object stores details to be used in all the Round Robin allocation processes</description>
    <fields>
        <fullName>Assign_Records__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Specifies whether records should be assigned to the user referenced by this rule. Allows for users to temporarily be taken out of the round robin processing</description>
        <label>Assign Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Dependent on the Object type pick list this determines the Group that this rule belongs to</description>
        <label>Group</label>
        <picklist>
            <controllingField>Object_Type__c</controllingField>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OnSite/Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Marketing New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (Broadcast Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (International Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was this the last Round Robin record to be allocated a Record</description>
        <label>Last Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Records_Assigned__c</fullName>
        <description>Shows the total number of records assigned</description>
        <label>Number of Records Assigned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>The type of Object to apply this rule to</description>
        <label>Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Print Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Open_Opps__c</fullName>
        <label>Open Opps</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Store_Stats__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Should a log be kept of all records allocated to this User</description>
        <label>Store Stats</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <label>Sub Group</label>
        <picklist>
            <controllingField>Group__c</controllingField>
            <picklistValues>
                <fullName>BASIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLIENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Small Business Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PitchEngine Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BROADCAST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Available_Potential__c</fullName>
        <label>Total Available Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the user who should be assigned a Record</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/TestBatchCalcOpenOpsAndTotPotentialForRR.cls
@isTest
private class TestBatchCalcOpenOpsAndTotPotentialForRR {
	static testMethod void TestCalcOpenOpsAndTotPotentialForRR() {
		// TO DO: implement unit test
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser('Test1', TestLibrary.NEW_BIZ_PROFILE);
        insert u;
		
		System.debug('*** User created...');
		
		//insert user in RR
		Round_Robin__c rr1 = new Round_Robin__c(User__c=u.Id,Object_Type__c='Opportunity',Group__c='CST',Sub_Group__c='NATIONAL',Assign_Records__c=true,Number_of_Records_Assigned__c=1,Last_Allocated__c=true,Store_Stats__c=true,Open_Opps__c=1,Total_Available_Potential__c=1000);
		insert rr1;
		        
		Account a = TestLibrary.CreateAccount('Test Account', u.Id);  
       	insert a;
		
		Contact c = TestLibrary.CreateContact('Test', 'Test@cisionus.com', u.Id, a.Id);
		insert c;
		
		Opportunity o = TestLibrary.CreateOpportunity('Test', u.Id, a.Id);
        o.RecordTYpeId = TestLibrary.OPPORTUNITY_RENEWALS_RECORD_TYPE;
		o.Type = 'Renewal'; 
		o.At_Risk__c = 'Yes';  
		o.Renewal_Due_Date__c = Date.today().addDays(10);
		o.Commissionable_Potential__c = 2000;
		insert o;
        
        system.debug('*** Opportunity Owner---'+ o.OwnerId);
        
        system.debug('*** Renewal_Due_Date__c ---'+o.Renewal_Due_Date__c);
		
		Test.startTest();
		
		  User uResult = [Select Id from User Where Alias = 'Test1'];
		  system.debug('*** user Id ---'+ uResult.Id);
		  System.assert(uResult != null);
		
       	  string SOQL = 'Select Id, User__c, Open_Opps__c, Total_Available_Potential__c from Round_Robin__c Where user__c = \''+ uResult.id + '\'';
          system.debug('***SQL---'+ SOQL);
          
          Database.executeBatch(new batchCalcOpenOpsAndTotPotentialForRR(SOQL),20); 

		  Round_Robin__c rrResult = [Select Id, User__c, Open_Opps__c, Total_Available_Potential__c from Round_Robin__c Where user__c = :uResult.id and Object_Type__c='Opportunity'];
		  
          system.debug('*** User ---'+ rrResult.User__c);
          system.debug('*** Open_Opps ---'+ rrResult.Open_Opps__c);
          system.debug('*** Total_Available_Potential__c ---'+ rrResult.Total_Available_Potential__c);
       
		  System.assert(rrResult != null);
		  //System.assert(rrResult.Open_Opps__c > 0);
		  //System.assert(rrResult.Total_Available_Potential__c > 0);
		
		
		Test.stopTest();
		
	}
	
	
	
}