CS_SBOX_20150209_01/Metadata/unpackaged/objects/Round_Robin__c.object
<CustomObject>
    <description>This Object stores details to be used in all the Round Robin allocation processes</description>
    <fields>
        <fullName>Assign_Records__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Specifies whether records should be assigned to the user referenced by this rule. Allows for users to temporarily be taken out of the round robin processing</description>
        <label>Assign Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Dependent on the Object type pick list this determines the Group that this rule belongs to</description>
        <label>Group</label>
        <picklist>
            <controllingField>Object_Type__c</controllingField>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OnSite/Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Marketing New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (Broadcast Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (International Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was this the last Round Robin record to be allocated a Record</description>
        <label>Last Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Records_Assigned__c</fullName>
        <description>Shows the total number of records assigned</description>
        <label>Number of Records Assigned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>The type of Object to apply this rule to</description>
        <label>Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Print Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Open_Opps__c</fullName>
        <label>Open Opps</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Store_Stats__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Should a log be kept of all records allocated to this User</description>
        <label>Store Stats</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <label>Sub Group</label>
        <picklist>
            <controllingField>Group__c</controllingField>
            <picklistValues>
                <fullName>BASIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLIENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Small Business Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PitchEngine Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BROADCAST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the user who should be assigned a Record</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/TestRoundRobinHelper.cls
@isTest
public with sharing class TestRoundRobinHelper
{
	static testMethod void RoundRobinHelperTest()
	{
		//Setup the Data
		User user1 = TestingUtils.createUser('rrTest1', TestingUtils.TEST_PROFILE_ID);
		insert user1;
		User user2 = TestingUtils.createUser('rrTest2', TestingUtils.TEST_PROFILE_ID);
		insert user2;
		User user3 = TestingUtils.createUser('rrTest3', TestingUtils.TEST_PROFILE_ID);
		insert user3;
		
		Round_Robin__c rr1 = new Round_Robin__c(User__c=user1.Id,Object_Type__c='Opportunity',Group__c='East',Sub_Group__c='NATIONAL',Assign_Records__c=true,Number_of_Records_Assigned__c=null,Last_Allocated__c=true,Store_Stats__c=true,Open_Opps__c=0);
		insert rr1;
		Round_Robin__c rr2 = new Round_Robin__c(User__c=user2.Id,Object_Type__c='Opportunity',Group__c='East',Sub_Group__c='NATIONAL',Assign_Records__c=true,Number_of_Records_Assigned__c=0,Last_Allocated__c=false,Store_Stats__c=true,Open_Opps__c=0);
		insert rr2;
		Round_Robin__c rr3 = new Round_Robin__c(User__c=user3.Id,Object_Type__c='Opportunity',Group__c='East',Sub_Group__c='NATIONAL',Assign_Records__c=true,Number_of_Records_Assigned__c=0,Last_Allocated__c=false,Store_Stats__c=true,Open_Opps__c=0);
		insert rr3;
		
		Test.startTest();
		
		RoundRobinHelper rrTest1 = new RoundRobinHelper('Opportunity', 'East');
		rrTest1.GetUserIds();
		rrTest1.GetNextUser(false, false);
		rrTest1.CreateStatisticRecord('TEST');
		rrTest1.GetNextUser(false, false);
		rrTest1.CreateStatisticRecord('TEST');
		rrTest1.GetNextUser(false, false);
		rrTest1.CreateStatisticRecord('TEST');
		rrTest1.GetNextUser(false, false);
		rrTest1.CreateStatisticRecord('TEST');
		rrTest1.GetNextUser(false, false);
		rrTest1.CreateStatisticRecord('TEST');
		rrTest1.GetNextUser(false, false);
		rrTest1.CreateStatisticRecord('TEST');
		rrTest1.UpdateRoundRobin();
		
		RoundRobinHelper rrTest2 = new RoundRobinHelper('Opportunity', 'East', 'NATIONAL');
		rrTest2.GetNextUser(false, true);
		rrTest2.GetNextUser(false, true);
		rrTest2.GetNextUser(false, true);
		
		Test.stopTest();
	}

}