CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/OpportunityUpdateExtension.cls
public with sharing class OpportunityUpdateExtension
{
	public Opportunity opp;
	
	public OpportunityUpdateExtension( ApexPages.StandardController stdController )
	{
	    opp = ( Opportunity )stdController.getRecord();       
    }

	public void SetPrimaryContactForQuote()
	{
		OpportunityUpdateExtension.SetPrimaryContactForQuoteFuture(opp.Id);
	}

	@future
	public static void SetPrimaryContactForQuoteFuture( Id oppId )
	{
		// Get the Primary OCR record for this Opportunity
		System.debug('############# oppId = ' + oppId);
		
		OpportunityContactRole[] ocr = [Select Id, contactId from OpportunityContactRole where OpportunityId = :oppId and IsPrimary = true];
		
		System.debug('############# ocr = ' + ocr);
		
		if (ocr.size() > 0)
		{
			// Get a list of Quotes that belong to this Opp
			List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__PrimaryContact__c from SBQQ__Quote__c where SBQQ__Opportunity__c = :oppId];
		
            if (quoteList != null)
            {
				for (SBQQ__Quote__c q : quoteList)
				{
					q.SBQQ__PrimaryContact__c = ocr[0].ContactId;
				}
            }
			
			update quoteList;
		}
	}
}