CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AR_Rep__c</fullName>
        <formula>IF(NAAT__c=TRUE, &quot;Sue Mierop&quot;, IF(BEGINS(Name, &quot;G&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;H&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;I&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;J&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;K&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;L&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;M&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;N&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;O&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;P&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;Q&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;R&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;S&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;T&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;U&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;V&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;W&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;X&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;Y&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;Z&quot;), &quot;Tony Mace&quot;, &quot;Richard Micus&quot;)))))))))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AR Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Services_Info__c</fullName>
        <description>Created by LM on 8/26/2013 for Phase 2 rollout</description>
        <label>Client Services Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Collections_Info__c</fullName>
        <description>Created by LM on 8/26/2013 for Phase 2 rollout</description>
        <label>Collections Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Credit_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Credit Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Sell__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/7/2014 for Phase2</description>
        <label>Do Not Sell</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extensions_Info__c</fullName>
        <description>Created by LM on 8/26/2013 for Phase 2 rollout</description>
        <label>Extensions Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LexisNexis_Named_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <inlineHelpText>Indicator of  an account exclusive to LexisNexis. Cision may not propose eNews to this account without executive approval.</inlineHelpText>
        <label>LexisNexis Named Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Biz_Info__c</fullName>
        <description>Created by LM on 9/11/2013 for Phase 2 rollout</description>
        <label>New Biz Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>New_Biz_Named_Account_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 1/22/2014 for Phase2</description>
        <inlineHelpText>The New Biz Named Account Rep owns this Account.  There is no requirement for the New Biz Named Account Rep to do any activity on the Account in order to &quot;keep&quot; the account .  Each night, the New Biz Named Account Rep will overwrite the New Biz Rep field.</inlineHelpText>
        <label>New Biz Named Account Rep</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>New Biz</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountsNewBizNamedAccountRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P_O_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Added by LM on 3/15/2013; From MS CRM</description>
        <label>P.O. Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuickShare_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <inlineHelpText>Indicator of  an account exclusive to LexisNexis. Cision may not propose QuickShare to this account without executive approval.</inlineHelpText>
        <label>QuickShare Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Info__c</fullName>
        <description>Created by LM on 8/26/2013 for Phase 2 rollout</description>
        <label>Renewal Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Renewal_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 11/4/2013 for Phase 2 rollout</description>
        <inlineHelpText>The Renewal Period is anytime in the period of time 90 days BEFORE the Renewal Due Date through 60 days AFTER the Renewal Due Date (or 60 days after after Closed Renewal).</inlineHelpText>
        <label>Renewal Period</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewals_Named_Account_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 1/22/2014 for Phase2</description>
        <label>Renewals Named Account Rep</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Renewal</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountsRenewalsNamedAccountRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/AccountAlertExtension.cls
public with sharing class AccountAlertExtension{
	public Boolean DisplayPopUp {get; set;}
	public Account acct {get; set;}
	
	public AccountAlertExtension(ApexPages.StandardController controller) 
    {
		 //  Get the Account Record
		
		String accountid = ApexPages.currentPage().getParameters().get('aid');
		//System.debug(accountid);
		
		if(accountid != null)
		{
			acct =  [select Id, Name, Renewal_Info__c, Collections_Info__c, Renewal_Period__c, New_Biz_Info__c, Client_Services_Info__c, Extensions_Info__c, Credit_Hold__c, P_O_Required__c, 
			LexisNexis_Named_Account__c, QuickShare_Account__c, AR_Rep__c, New_Biz_Named_Account_Rep__r.Name, Renewals_Named_Account_Rep__r.Name, Do_Not_Sell__c from Account where Id = :accountid]; //accountid
		}
		else
		{
			acct = (Account)controller.getRecord();		
			acct =  [select Id, Name, Renewal_Info__c, Renewal_Period__c, Collections_Info__c, New_Biz_Info__c, Client_Services_Info__c, Extensions_Info__c, Credit_Hold__c, P_O_Required__c, 
			LexisNexis_Named_Account__c, QuickShare_Account__c, AR_Rep__c,  New_Biz_Named_Account_Rep__r.Name, Renewals_Named_Account_Rep__r.Name, Do_Not_Sell__c from Account where Id = :acct.Id]; //accountid
		}
		
		//System.debug(acct);		   	  	
	}

}