CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Fortune_1000_Ranking__c</fullName>
        <description>Added by LM on 2/8/2013; From MS CRM</description>
        <label>Fortune 1000 Ranking</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAICS_Code_1__c</fullName>
        <description>Added by LM on 2/8/2013; From MS CRM</description>
        <label>NAICS Code 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Biz_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <inlineHelpText>This field shows the last New Biz Rep who has modified the Account or any related Contact, Opp, or Activity in the last 60 days.  The New Biz Named Account Rep, if there is one, will overwrite the New Biz Rep field each night.</inlineHelpText>
        <label>New Biz Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Plan Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Broadcast__c</fullName>
        <description>Created by LM on 8/26/2013 for Phase 2 rollout</description>
        <label>Total Spend (Broadcast)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Non_Broadcast__c</fullName>
        <description>Created by LM on 8/26/2013 for Phase 2 rollout</description>
        <label>Total Spend (Non-Broadcast)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Web_Employees__c</fullName>
        <description>Added by LM on 2/8/2013; From MS CRM</description>
        <label>PH2-Web Employees</label>
        <picklist>
            <picklistValues>
                <fullName>Under 1000 Employees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over 1000 Employees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Revenue__c</fullName>
        <description>Added by LM on 2/8/2013; From MS CRM</description>
        <label>PH2-Web Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>Under 200Mil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over 200Mil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Function_Department__c</fullName>
        <description>Created by LM on 9/27/2013 for Phase 2 rollout</description>
        <label>Function/Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investor Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Membership Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR/Corporate Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <description>Added by LM on 2/11/2013; From MS CRM</description>
        <label>Job Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freelancer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Journalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner/Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor/Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vice President</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Employees__c</fullName>
        <description>Created by LM on 9/27/2013 for Phase 2 rollout</description>
        <label>Web Employees</label>
        <picklist>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fewer than 1,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than 1,000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Revenue__c</fullName>
        <description>Created by LM on 9/27/2013 for Phase 2 rollout</description>
        <label>Web Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than $150 Million</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater than $150 Million</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Function_Department__c</fullName>
        <description>Created by LM on 9/27/2013 for Phase 2 rollout</description>
        <label>Function/Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investor Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Membership Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR/Corporate Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <description>Created by LM on 9/27/2013 for Phase 2 rollout</description>
        <label>Job Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freelancer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Journalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner/Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor/Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vice President</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Employees__c</fullName>
        <description>Created by LM on 9/5/2013 for Phase 2 rollout</description>
        <label>Web Employees</label>
        <picklist>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fewer than 1,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than 1,000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Revenue__c</fullName>
        <description>Created by LM on 9/5/2013 for Phase 2 rollout</description>
        <label>Web Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than $150 Million</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater than $150 Million</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CA_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 12/3/2013 for Phase 2 rollout</description>
        <label>CA Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>CA_Rep__c</fullName>
        <formula>SBQQ__Opportunity__r.CA_Rep__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CA Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer account. Defaulted on create from the opportunity.</description>
        <inlineHelpText>Customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>CA_Rep__c</fullName>
        <description>Created by LM on 1/30/2014 for Phase2 Rollout</description>
        <label>CA Rep</label>
        <relationshipName>CA_Rep</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/UtilityClass.cls
public with sharing class UtilityClass 
{
	public static String getSObjectTypeName(SObject so) 
	{
		return so.getSObjectType().getDescribe().getName();
	}
	
	public static Boolean HasListChanged(List<SObject> oldList, List<SObject> newList)
	{
		if (oldList != null && newList != null && oldList.size() > 0 && newList.size() > 0)
		{
			// If the old list contains no Ids and the new list does or visa versa then we should return true
			if ( (oldList[0].Id == null && newList[0].Id != null) || (oldList[0].Id != null && newList[0].Id == null) )
			{
				return true;
			}
			else
			{
				if (oldList[0].Id == null && newList[0].Id == null)
				{
					return false;
				}
				else
				{
					Boolean oldListContainsNulls = false;
					Boolean newListContainsNulls = false;
					
					for (SObject soOld : oldList)
					{
						if (soOld.Id == null)
						{
							oldListContainsNulls = true;
							break;
						}
					}
					
					for (SObject soNew : newList)
					{
						if (soNew.Id == null)
						{
							newListContainsNulls = true;
							break;
						}
					}
					
					if (!oldListContainsNulls && !newListContainsNulls)
					{
						Set<Id> oldResultIds = (new Map<Id,SObject>(oldList)).keySet();
						Set<Id> newResultIds = (new Map<Id,SObject>(newList)).keySet();
						
						if (oldResultIds.containsAll(newResultIds))
						{
							return false;
						}
						else
						{
							return true;
						}
					}
					else
					{
						return true;
					}
				}
			}
		}
		else
		{
			return true;
		}
	}
	
	public static User GetUser(String userName)
	{
		List<User> uList = null;
		
		uList = [Select U.Id, U.Email, U.Manager.Email, U.Manager.Name, U.Username, U.Name, U.Ca_Rep__c from User U where Name =: userName LIMIT 1];		
		
		if(uList.size() > 0)
			return uList.get(0);
		else
			return null;
			
	}
	
	public static User GetUser(Id userId)
	{
		List<User> uList = null;
		
		uList = [Select U.Id, U.Email, U.Manager.Email, U.Manager.Name, U.Username, U.Name, U.Ca_Rep__c from User U where Id =: userId LIMIT 1];		
		
		if(uList.size() > 0)
			return uList.get(0);
		else
			return null;
	}
	
	public static RecordType GetRecordType(Id recordTypeId)
	{		
		RecordType caseSupportRecordType = [Select R.IsActive, R.Description, R.Name, R.Id, R.DeveloperName from RecordType R WHERE R.Id  =: recordTypeId];
		
		return caseSupportRecordType;
	}
	
	public static RecordType GetRecordType(String Name)
	{		
		RecordType caseSupportRecordType = [Select R.IsActive, R.Description, R.Name, R.Id, R.DeveloperName from RecordType R WHERE R.Name  =: Name];
		
		return caseSupportRecordType;
	}
	
	public static SBQQ__Quote__c GetQuote(Id quoteId)
	{
		SBQQ__Quote__c quote = [SELECT q.Id, q.SBQQ__Account__c, q.SBQQ__Opportunity__c, q.Name from SBQQ__Quote__c q where q.Id =: quoteId];
		
		return quote;
	}
	
	public static Contact GetContact(Id contactId)
	{
		Contact con = [Select C.OwnerId, C.AccountId, C.Account.Name, C.Name, C.Phone, C.MailingCity, C.MailingState, C.MailingCountry, C.Account.AnnualRevenue, C.Account.Type, C.Account.Plan_Customer__c, C.Description, C.Account.Total_Spend_Non_Broadcast__c, C.Account.Total_Spend_Broadcast__c, C.Account.Fortune_1000_Ranking__c, C.Account.NAICS_Code_1__c, C.Account.Website, C.Account.New_Biz_Rep__c, C.Account.Renewal_Rep__c, C.Id, C.CreatedDate, 
						C.Email, C.Account.BillingState, C.Account.BillingCountry, C.Web_Employees__c, C.Web_Revenue__c, C.Job_Role__c, C.Function_Department__c, C.PR_Department_Size__c, C.PR_Activities__c, C.Areas_of_Interest__c, C.Web_Lead_Comments__c from Contact C where Id =: contactId];
		
		return con;		
	}	
	
	public static Opportunity GetOpportunity(Id oppId)
	{
		Opportunity opp = [Select Id, Name, AccountId, OwnerId, CampaignId, IsClosed from Opportunity where Id =: oppId];
		
		return opp;
	}
	
	public static Task GetTask(Id taskId)
	{	
		Task t = [Select T.Id, T.AccountId, T.Account.Name, T.Who.Name, T.OwnerId, T.RecordTypeId, t.RecordType.Name, T.Task_Type__c, T.WhatId from Task T where Id =: taskId];
		System.debug('###########################' + t);
		
		return t;
	}
	
	public static Lead GetLead(Id leadId)
	{
		Lead l = [Select Id, Name, OwnerId, NumberOfEmployees, Status, Lead_Pass_Rep__c, Web_Revenue__c, Email, Owner.Name, Company, Phone, City, State, Country, Job_Role__c, Function_Department__c, PR_Department_Size__c, PR_Activities__c, Areas_of_Interest__c, 
				 Web_Employees__c, Description, Rating from Lead where Id =: leadId];	
		
		return l;
	}
	
	public static Campaign GetCampaign(Id campaignId)
	{
		Campaign camp = [Select Id, Team_Queue__c, Name, Campaign_Goal__c from Campaign where Id =: campaignId];
		
		return camp;		
	}	
	
	public static Account GetAccount(Id acctId)
	{
		Account acct = [Select Id, Name from Account where Id =: acctId];
		
		return acct;		
	}	
	
	public static List<Schema.FieldSetMember> ReturnFieldSet(String objectName, String fieldSetName)
	{
		if (fieldSetName == null)
		{
			fieldSetName = 'Client_Services';
		}
		else
		{
			fieldSetName = fieldSetName.replace(' ', '_').replace('-', '_').replace('/', '_').replace('(', '_').replace(')', ' ').trim();
		}
		system.debug('fieldSetName=' + fieldSetName);
		Map<String, Schema.SObjectType> GlobalDescribeMap = Schema.getGlobalDescribe(); 
    	Schema.SObjectType SObjectTypeObj = GlobalDescribeMap.get(objectName);
    	Schema.DescribeSObjectResult DescribeSObjectResultObj = SObjectTypeObj.getDescribe();

       	Schema.FieldSet fieldSetObj = DescribeSObjectResultObj.FieldSets.getMap().get(fieldSetName);
		
		if(fieldSetObj != null)
     		return fieldSetObj.getFields(); 
		else
			return new List<Schema.FieldSetMember>();
	}
}