CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Analysis_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Analysis Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Broadcast_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Broadcast Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Connect_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Connect Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Directories__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/29/2013 for Phase 2 rollout</description>
        <label>CPS Directories</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Database__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/29/2013 for Phase 2 rollout</description>
        <label>CPS International Database</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monitoring_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Monitoring Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Named_Account_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Named Account Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>NamedAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Biz_Last_Touched_Date__c</fullName>
        <description>Added by LM on 1/17/14 for Phase2</description>
        <label>New Biz Last Touched Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Biz_Named_Account_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 1/22/2014 for Phase2</description>
        <inlineHelpText>The New Biz Named Account Rep owns this Account.  There is no requirement for the New Biz Named Account Rep to do any activity on the Account in order to &quot;keep&quot; the account .  Each night, the New Biz Named Account Rep will overwrite the New Biz Rep field.</inlineHelpText>
        <label>New Biz Named Account Rep</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>New Biz</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountsNewBizNamedAccountRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Biz_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <inlineHelpText>This field shows the last New Biz Rep who has modified the Account or any related Contact, Opp, or Activity in the last 60 days.  The New Biz Named Account Rep, if there is one, will overwrite the New Biz Rep field each night.</inlineHelpText>
        <label>New Biz Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Additional_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/29/2013 for Phase 2 rollout</description>
        <label>CPS Plan Additional Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/11/2013 for Phase 2 rollout</description>
        <label>Plan Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Premium_Data_Add_Ons__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/29/2013 for Phase 2 rollout</description>
        <label>CPS Plan Premium Data/Add-Ons</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 11/4/2013 for Phase 2 rollout</description>
        <inlineHelpText>The Renewal Period is anytime in the period of time 90 days BEFORE the Renewal Due Date through 60 days AFTER the Renewal Due Date (or 60 days after after Closed Renewal).</inlineHelpText>
        <label>Renewal Period</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Web_Wire_Distribution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by LM on 10/29/2013 for Phase 2 rollout</description>
        <label>CPS Web/Wire Distribution</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Invoice_Contact_Email__c</fullName>
        <inlineHelpText>Please input the email address for the Invoice Contact above.</inlineHelpText>
        <label>Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact_Name__c</fullName>
        <label>Invoice Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Due_Date__c</fullName>
        <description>Created by LM on 8/31/2013 for Phase 2 rollout</description>
        <label>Renewal Due Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Round_Robin__c.object
<CustomObject>
    <description>This Object stores details to be used in all the Round Robin allocation processes</description>
    <fields>
        <fullName>Assign_Records__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Specifies whether records should be assigned to the user referenced by this rule. Allows for users to temporarily be taken out of the round robin processing</description>
        <label>Assign Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Dependent on the Object type pick list this determines the Group that this rule belongs to</description>
        <label>Group</label>
        <picklist>
            <controllingField>Object_Type__c</controllingField>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OnSite/Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Marketing New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (Broadcast Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (International Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was this the last Round Robin record to be allocated a Record</description>
        <label>Last Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Records_Assigned__c</fullName>
        <description>Shows the total number of records assigned</description>
        <label>Number of Records Assigned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>The type of Object to apply this rule to</description>
        <label>Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Print Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Open_Hot_Leads_This_Month__c</fullName>
        <label>Open Hot Leads This Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Opps__c</fullName>
        <label>Open Opps</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Warm_Leads_This_Month__c</fullName>
        <label>Open Warm Leads This Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Store_Stats__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Should a log be kept of all records allocated to this User</description>
        <label>Store Stats</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <label>Sub Group</label>
        <picklist>
            <controllingField>Group__c</controllingField>
            <picklistValues>
                <fullName>BASIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLIENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Small Business Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PitchEngine Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BROADCAST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the user who should be assigned a Record</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__Subscription__c.object
<CustomObject>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestBatchProcesses.cls
@isTest
private class TestBatchProcesses
{
	static testMethod void TestBatchCalculateOpenLeadsForRoundRobin() 
    {
		//Setup the Data
		User user1 = TestingUtils.createUser('leadrr1', TestingUtils.TEST_PROFILE_ID);
		insert user1;
				
		Round_Robin__c rr1 = new Round_Robin__c(User__c=user1.Id,Object_Type__c='Lead',Group__c='West',Sub_Group__c='AM',Assign_Records__c=true,Number_of_Records_Assigned__c=null,Last_Allocated__c=true,Store_Stats__c=true,Open_Opps__c=0);
		insert rr1;
		
		List<Lead> leadList = TestingUtils.createLeads(4, false);
		leadList[0].OwnerId = user1.Id;
		leadList[0].Rating = 'Hot';
		leadList[1].OwnerId = user1.Id;
		leadList[1].Rating = 'Hot';
		leadList[2].OwnerId = user1.Id;
		leadList[2].Rating = 'Warm';
		leadList[3].OwnerId = user1.Id;
		leadList[3].Rating = 'Warm';
		insert leadList;
		
		List<Task> taskList = TestingUtils.createTasks(4, false);
		taskList[0].OwnerId = user1.Id;
		taskList[0].Task_Type__c = 'Campaign Response';
		taskList[0].Lead_Status__c = 'New';
		taskList[0].Rating__c = 'Hot';
		taskList[1].OwnerId = user1.Id;
		taskList[1].Task_Type__c = 'Campaign Response';
		taskList[1].Lead_Status__c = 'New';
		taskList[1].Rating__c = 'Hot';
		taskList[2].OwnerId = user1.Id;
		taskList[2].Task_Type__c = 'Campaign Response';
		taskList[2].Lead_Status__c = 'New';
		taskList[2].Rating__c = 'Warm';
		taskList[3].OwnerId = user1.Id;
		taskList[3].Task_Type__c = 'Campaign Response';
		taskList[3].Lead_Status__c = 'New';
		taskList[3].Rating__c = 'Warm';
		insert taskList;
		
		Test.startTest();
		
		string SOQL = 'Select Id, User__c, Object_Type__c, Open_Hot_Leads_This_Month__c, Open_Warm_Leads_This_Month__c from Round_Robin__c Where Id = \'' + rr1.Id + '\'';
		batchCalculateOpenLeadsForRoundRobin lead = new batchCalculateOpenLeadsForRoundRobin(SOQL);
		Database.executeBatch(lead, 1);			
		
		Test.stopTest();
	}
	
	static testMethod void TestBatchCalculateOpenOppsForRoundRobin() 
    {
		TestingUtils.InitAvaTax();

		//Setup the Data
		User user1 = TestingUtils.createUser('oppsrr', TestingUtils.TEST_PROFILE_ID);
		insert user1;
				
		Round_Robin__c rr1 = new Round_Robin__c(User__c=user1.Id,Object_Type__c='Opportunity',Group__c='West',Sub_Group__c='NATIONAL',Assign_Records__c=true,Number_of_Records_Assigned__c=null,Last_Allocated__c=true,Store_Stats__c=true,Open_Opps__c=0);
		insert rr1;
		
		Account a = TestingUtils.CreateAccount();  
		insert a;
		
		Opportunity opp = TestingUtils.createOpportunity(a.Id);
		opp.StageName = 'Contacted';
		opp.OwnerId = user1.Id;
		opp.Renewal_Due_Date__c = Date.today();
		insert opp;
		
		Test.startTest();
		
		string SOQL = 'Select Id, User__c, Open_Opps__c from Round_Robin__c where Id = \'' + rr1.Id + '\'';
    	Database.executeBatch(new batchCalculateOpenOppsForRoundRobin(SOQL),1); 
		
		Test.stopTest();
	}
	
	@isTest (SeeAllData=true)
	static void TestBatchProcessAccounts() 
	{
		TestingUtils.InitAvaTax();
		
		System.debug('Starting Process Accounts');
		Account a = TestingUtils.CreateAccount();  
		a.New_Biz_Last_Touched_Date__c = Date.today();
		a.Type = 'Customer';
		insert a;			
		System.debug('Account Created');
		
		Opportunity opp = TestingUtils.createOpportunity(a.Id);
    	opp.Invoice_Contact_Name__c = 'John';
    	opp.Invoice_Contact_Email__c = 'john@email.com';
		opp.Renewal_Due_Date__c = Date.today() + 7;
		opp.CloseDate = Date.today() - 7;
		opp.Type = 'Renewal';
    	insert opp;
		System.debug('Opp Created');
		
		Contract cont = TestingUtils.createContract(a.Id, opp.Id);
		insert cont;
		System.debug('Contract Created');
		
		Product2 prod = TestingUtils.createProduct(false);
		insert prod;
		
		SBQQ__Subscription__c sub = TestingUtils.createSubscription(a.Id, cont.Id, prod.Id);
		insert sub;
		System.debug('sub Created');
		
		List<SBQQ__Subscription__c> subsList = [Select Id from SBQQ__Subscription__c where SBQQ__Account__c = :a.Id];
		System.debug('Subs Count = ' + subsList.size());
		
		Asset ass = TestingUtils.createAsset(a.Id, prod.Id);
		insert ass;
		
		Test.startTest();	
		
		String SOQL = 'SELECT Id, Name, Type, Named_Account_Rep__c, New_Biz_Rep__c, New_Biz_Last_Touched_Date__c, New_Biz_Named_Account_Rep__c, Renewal_Rep__c, Renewal_Period__c, Plan_Customer__c, Connect_Customer__c, Monitoring_Customer__c, Analysis_Customer__c, Broadcast_Customer__c,' +
			' Directories__c, Plan_Additional_Users__c, Plan_Premium_Data_Add_Ons__c, International_Database__c, Web_Wire_Distribution__c, Content_Marketing__c, Social_Newsroom__c, Analyze_Tab__c, Broadcast_Monitoring__c,' +
			' Electronic_Monitoring__c, Managed_Services__c, Other_Monitoring_Services__c, Print_Monitoring__c, Social_Media_Monitoring_CP__c, Social_Media_Monitoring_Dashboard__c, Social_Media_Monitoring_Other__c,' + 
			' Advanced_Analytics__c, Global_Analysts__c, Canada__c, Distribution__c, Training__c, Broadcast_Rep__c, Broadcast_Last_Touched_Date__c, Credit_Limit__c, Paydex__c, Credit_Risk_Values_Date__c, Account_Ownership_History__c from Account where Id = \'' + a.Id + '\''; 

		
		batchProcessAccounts testBatch = new batchProcessAccounts(SOQL);
		Database.executeBatch(testBatch, 1);		
		Test.stopTest();
	}
	
	@isTest (SeeAllData=true)
	static void TestBatchCompetitorAlerts()
	{
		TestingUtils.InitAvaTax();
		
		List<Account> acc = TestingUtils.createAccounts(1, true);
			   	
	   	Opportunity opp = TestingUtils.createOpportunity(acc[0].Id);
    	opp.Invoice_Contact_Name__c = 'John';
    	opp.Invoice_Contact_Email__c = 'john@email.com';
    	insert opp;
		
		List<Competitor__c> compList = TestingUtils.createCompetitor(1, acc[0].Id, opp.Id);
		insert compList;
		
		List<Contact> conts = TestingUtils.createContacts(1, acc[0].Id, true);
						
		Test.startTest();
			string SOQL = 'Select Id, Name, Service_Expiration_Alert_Sent__c, Opportunity_Close__c, CreatedById, Account__c, Account__r.Name, Account__r.Renewal_Rep__c, Competitive_Spend__c, Competitor_Name__c, Competitor_Notes__c,  Service_Expiration_Date__c, Service_Provided__c from Competitor__c where Id = \'' + compList[0].Id + '\'';
    		Database.executeBatch(new batchCompetitorAlerts(SOQL),1); 
		Test.stopTest();
	}
	
	static testMethod void TestBatchSetPrimaryCampaignForOpp()
	{
		TestingUtils.InitAvaTax();
		
		Account acc = TestingUtils.CreateAccount();  
		insert acc;	   	
	   	
	   	Opportunity opp = TestingUtils.createOpportunity(acc.Id);
    	opp.Invoice_Contact_Name__c = 'John';
    	opp.Invoice_Contact_Email__c = 'john@email.com';
    	insert opp;
		
		List<Contact> contList = TestingUtils.createContacts(1, acc.Id, true);
		OpportunityContactRole ocr = TestingUtils.createOpportunityContactRole(opp.Id, contList[0].Id);
		insert ocr;
		Campaign camp = TestingUtils.createCampaign();
		camp.Type = 'Nurture';
		insert camp;
		CampaignMember campMember = TestingUtils.createCampaignMember(camp.Id, contList[0].Id);
		campMember.Status = 'Sent';
		insert campMember;
		
		Test.StartTest();
			String SOQL = 'SELECT Id, Name, CampaignId, CreatedDate FROM Opportunity WHERE Id = \'' + opp.Id + '\'';
			batchSetPrimaryCampaignForOpp batch = new batchSetPrimaryCampaignForOpp(SOQL);
			Database.executeBatch(batch,1); 
		Test.StopTest();
		
	}
	
	
	
	
}