CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Broadcast_Last_Touched_Date__c</fullName>
        <description>Created by LM on 2/17/14 for Phase2</description>
        <label>Broadcast Last Touched Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Broadcast_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Broadcast Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Biz_Last_Touched_Date__c</fullName>
        <description>Added by LM on 1/17/14 for Phase2</description>
        <label>New Biz Last Touched Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Biz_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <inlineHelpText>This field shows the last New Biz Rep who has modified the Account or any related Contact, Opp, or Activity in the last 60 days.  The New Biz Named Account Rep, if there is one, will overwrite the New Biz Rep field each night.</inlineHelpText>
        <label>New Biz Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Last_Touched_Date__c</fullName>
        <description>Added by LM on 2/8/2013; From MS CRM</description>
        <label>Sales Last Touched Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sales_Last_Touched_Date__c</fullName>
        <description>Created by LM on 5/6/2014 for Phase2</description>
        <label>Sales Last Touched Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer account. Defaulted on create from the opportunity.</description>
        <inlineHelpText>Customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/AccountHelper.cls
public with sharing class AccountHelper
{
	public static void AssignAccountOwner(Account a)
	{		
		if (a.Renewal_Rep__c != null)  
        {
            a.OwnerId = a.Renewal_Rep__c; 
        }
		else if(a.Renewal_Rep__c == null && a.New_Biz_Rep__c != null)
		{
			a.OwnerId = a.New_Biz_Rep__c; 
		}			
	}	
	
	public static void UpdateSalesLastTouchedDate(List<Id> accountIds)
	{
		Id profileId=userinfo.getProfileId();
		String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
		Id currentUserId = UserInfo.getUserId();
		System.debug('########################## Current User Id = ' + currentUserId); 
		if(accountIds != null)
		{
			System.debug('##################### accountIds = ' + accountIds);
			List<Account> accounts = [Select Id, Name, Sales_Last_Touched_Date__c from Account Where Id in :accountIds];
			//system.debug('ProfileName'+profileName);
						
			for(Account a :  accounts)
			{
				UpdateSalesLastTouchedDate(a, profileName, currentUserId);
			}
			
			update accounts;
		}
	}
	
	public static void UpdateSalesLastTouchedDate(List<Account> accList)
	{
		Id profileId=userinfo.getProfileId();
		String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
		Id currentUserId = UserInfo.getUserId();
		
		for (Account a : accList)
		{
			UpdateSalesLastTouchedDate(a, profileName, currentUserId);
		}
	}
	
	/*public static void UpdateSalesLastTouchedDate(Account a)
	{
		Id profileId=userinfo.getProfileId();
		String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
		Id currentUserId = UserInfo.getUserId();
		system.debug('currentUserId = '+currentUserId);
		
		UpdateSalesLastTouchedDate(a, profileName, currentUserId);							
	}*/	
	
	private static void UpdateSalesLastTouchedDate(Account a, String profileName, Id currentUserId)
	{	
		System.debug('Setting Last Touched Date');
		
		if(profileName == Constants.BroadcastTransactionManager || profileName == Constants.BroadcastTransactionSalesUser || profileName == Constants.NewBizManager ||
		profileName == Constants.NewBizSalesUser || profileName == Constants.RenewalsManager || profileName == Constants.RenewalsSalesUser)
		{
			System.debug('Broadcast Profile');
			a.Sales_Last_Touched_Date__c = Date.today();
			if(profileName == Constants.NewBizManager || profileName == Constants.NewBizSalesUser)
			{
				a.New_Biz_Last_Touched_Date__c = Date.today();
				a.New_Biz_Rep__c = currentUserId;
			}
			else if(profileName == Constants.BroadcastTransactionManager || profileName == Constants.BroadcastTransactionSalesUser)
			{
				a.Broadcast_Last_Touched_Date__c = Date.today();
				a.Broadcast_Rep__c = currentUserId;
				System.debug('Broadcast Last Touched Date = ' + a.Broadcast_Last_Touched_Date__c );
			}						
		}					
	}
					
	public static ID ReturnAccountIdFromId(Id objectId)
	{
		if(string.valueOf(objectId).startsWith('001'))
		{
			return objectId;
		}//Check for account associated to contact
		else if(string.valueOf(objectId).startsWith('003'))
		{
			Contact c = UtilityClass.GetContact(objectId);
			
			return c.AccountId;
			//accountIds.Add(t.WhatId);					
		}//Check for account associated to opp
		else if(string.valueOf(objectId).startsWith('006'))
		{
			Opportunity o = UtilityClass.GetOpportunity(objectId);
			
			return o.AccountId;
		}//Check for account associated to quote
		else if(string.valueOf(objectId).startsWith('a0q'))
		{
			SBQQ__Quote__c q = UtilityClass.GetQuote(objectId);
			
			return q.SBQQ__Account__c;
		}
		
		return null;
	}		
}