CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitive_Spend__c</fullName>
        <description>Added by LM on 3/15/2013; New for SFDC rollout</description>
        <label>Competitive Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <label>Competitor Name</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gorkana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus/PRWeb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competitor_Notes__c</fullName>
        <description>Created by LM on 9/9/2013 for Phase 2 rollout</description>
        <label>Competitor Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Close__c</fullName>
        <description>Created by LM on 9/9/2013 for Phase 2 rollout</description>
        <label>Opportunity Close</label>
        <picklist>
            <picklistValues>
                <fullName>Lost To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stolen From</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Expiration_Alert_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Expiration Alert Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Expiration_Date__c</fullName>
        <label>Service Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Provided__c</fullName>
        <label>Service Provided</label>
        <picklist>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <description>Added by MD 09/13/2012. A Field to hold the name of the Competitor that the Sale was Lost to or Stolen from</description>
        <inlineHelpText>A Competitor Name must be selected when Closing an Opportunity and the Close Reason is &quot;Competitor&quot;</inlineHelpText>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Round_Robin__c.object
<CustomObject>
    <description>This Object stores details to be used in all the Round Robin allocation processes</description>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>The type of Object to apply this rule to</description>
        <label>Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Print Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Open_Hot_Leads_This_Month__c</fullName>
        <label>Open Hot Leads This Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Opps__c</fullName>
        <label>Open Opps</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Warm_Leads_This_Month__c</fullName>
        <label>Open Warm Leads This Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the user who should be assigned a Record</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/batchJobTestHarnessController.cls
public with sharing class batchJobTestHarnessController
{
	public List<JobsWrapper> jobs {get; Set;}
		
	public batchJobTestHarnessController()
	{
		jobs = new List<JobsWrapper>();
		jobs.add(new JobsWrapper(1, 'CalculateOpenLeadsForRoundRobin'));
		jobs.add(new JobsWrapper(2, 'CalculateOpenOppsForRoundRobin'));
		jobs.add(new JobsWrapper(3, 'SendCompetitorAlerts'));
		jobs.add(new JobsWrapper(4, 'SetPrimaryCampaignForOpp'));
		jobs.add(new JobsWrapper(5, 'ProcessAccounts'));
		jobs.add(new JobsWrapper(6, 'RenewalTotals'));
		jobs.add(new JobsWrapper(7, 'ProcessOpportunities'));
	}
	
	public PageReference RunJobs()
	{
		// Get the Row Id of the job we need to run
		string RowId = ApexPages.currentPage().getParameters().get('RowId');

		JobsWrapper currentJob = jobs[Integer.valueOf(RowId)-1];
		
		if (RowId == '1')
		{
			string SOQL = 'Select Id, User__c, Open_Warm_Leads_This_Month__c, Open_Hot_Leads_This_Month__c, Object_Type__c from Round_Robin__c Where Object_Type__c = \'' + 'Lead' + '\'';
    		currentJob.JobId = Database.executeBatch(new batchCalculateOpenLeadsForRoundRobin(SOQL),20); 
 		}
		else if (RowId == '2')
		{
			string SOQL = 'Select Id, User__c, Open_Opps__c from Round_Robin__c';
    		currentJob.JobId = Database.executeBatch(new batchCalculateOpenOppsForRoundRobin(SOQL),20); 
		}
		else if (RowId == '3')
		{
			string SOQL = 'Select Id, Name, Service_Expiration_Alert_Sent__c, Opportunity_Close__c, CreatedById, Account__c, Account__r.Name, Account__r.Renewal_Rep__c, Account__r.OwnerId, Competitive_Spend__c, Competitor_Name__c, Competitor_Notes__c,  Service_Expiration_Date__c, Service_Provided__c from Competitor__c where (Competitor_Name__c != \'No Competitor\' and Competitor_Name__c != \'Client Won’t Say/Don’t Know\')';
    		currentJob.JobId = Database.executeBatch(new batchCompetitorAlerts(SOQL),10);
		}
		else if (RowId == '4')
		{
			String SOQL = 'SELECT Id, Name, CampaignId, CreatedDate FROM Opportunity WHERE Id IN (SELECT OpportunityId FROM OpportunityContactRole)';
			currentJob.JobId = Database.executeBatch(new batchSetPrimaryCampaignForOpp(SOQL),10); 
		}
		else if (RowId == '5')
		{
			currentJob.JobId = Database.executeBatch(new batchProcessAccounts(),1); 
		}
		else if (RowId == '6')
		{
			 currentJob.JobId = Database.executeBatch(new batchRenewalTotals(), 50);
		}
		else if (RowId == '7')
		{
			 currentJob.JobId = Database.executeBatch(new batchProcessOpportunities(), 50);
		}
		
		currentJob.Status = 'Started';
		
		return null;
	}
	
	public PageReference UpdateStatuses()
	{
		// Only run this if any of the Jobs have a status of processing
		Set<ID> jobIds = new Set<ID>();
		for (JobsWrapper j : jobs)
		{
			if (j.Status == 'Processing' || j.Status == 'Started' || j.Status == 'Batch Queued')
			{
				jobIds.add(j.JobId);
			}
		}
		
		if (jobIds.size() > 0)
		{
			List<AsyncApexJob> aList = [select Id, TotalJobItems, Status, NumberOfErrors, MethodName, JobType, JobItemsProcessed, CreatedDate, CreatedById, CompletedDate, ApexClassId, ApexClass.Name From AsyncApexJob where Id IN :jobIds];
			
			if (aList != null)
			{
				Map<ID, AsyncApexJob> aMap = new Map<ID, AsyncApexJob>(aList);
				
				for (JobsWrapper j : jobs)
				{
					AsyncApexJob aJob = aMap.get(j.JobId);
					if (aJob != null)
					{
						j.Status = aJob.Status;
											
						Double itemsProcessed = aJob.JobItemsProcessed;
            			Double totalItems = aJob.TotalJobItems;
 
            	       	//Determine the pecent complete based on the number of batches complete
            			if(totalItems == 0)
						{
                			j.percentComplete = 0;
            			}
						else
						{
                			j.percentComplete = ((itemsProcessed  / totalItems) * 100.0).intValue();
            			}
					}
				}
			}
		}
		
		return null;
	}
	
	public class JobsWrapper
	{
		public Integer RowId {get; Set;}
		public String FunctionName {get; Set;}
		public String Status {get; Set;}
		public String JobId {get; Set;}
		public Integer percentComplete {get; set;}
		
		public JobsWrapper(Integer RowId, String FunctionName)
		{
			this.RowId = RowId;
			this.FunctionName = FunctionName;
			Status = 'Not Started';
			percentComplete = 0;
		}
	}

}