CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Campaign__c</fullName>
        <description>Created by LM on 9/10/2013 for Phase 2 rollout</description>
        <label>Brand/Campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitive_Spend__c</fullName>
        <description>Added by LM on 3/15/2013; New for SFDC rollout</description>
        <label>Competitive Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <label>Competitor Name</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gorkana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus/PRWeb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competitor_Notes__c</fullName>
        <description>Created by LM on 9/9/2013 for Phase 2 rollout</description>
        <label>Competitor Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Close__c</fullName>
        <description>Created by LM on 9/9/2013 for Phase 2 rollout</description>
        <label>Opportunity Close</label>
        <picklist>
            <picklistValues>
                <fullName>Lost To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stolen From</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Expiration_Alert_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Expiration Alert Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Expiration_Date__c</fullName>
        <label>Service Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Provided__c</fullName>
        <label>Service Provided</label>
        <picklist>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/batchCompetitorAlerts.cls
global with sharing class batchCompetitorAlerts implements Database.Batchable<sObject>, Schedulable
{
	private String queryString = null;
	
	private Map<Id, User> usersMap = new Map<Id, User>([Select Id, Email, ManagerId, IsActive, Profile.Name from User]);
	private Id newBizTaskRecordTypeId = null;
	private Id renewalsTaskRecordTypeId = null;
	private Contact tempContact = null;
	private Id templateId = null;
	
	global batchCompetitorAlerts(String q)
	{
		queryString = q;
		
		tempContact = [select id, Email from Contact where email <> null limit 1];
		templateId = [select id from EmailTemplate where DeveloperName='CompetitorRenewalAlert'].id;
		
		List<RecordType> rtList = [select Id, Name, SObjectType from RecordType where SObjectType = 'Task' and (Name = 'Renewal Sales' or Name = 'New Biz Sales')];
		
		if (rtList != null && rtList.size() > 0)
		{
			for (RecordType r : rtList)
			{
				if (r.SObjectType == 'Task' && r.Name == 'New Biz Sales')
				{
					newBizTaskRecordTypeId = r.Id;
				}
				
				if (r.SObjectType == 'Task' && r.Name == 'Renewal Sales')
				{
					renewalsTaskRecordTypeId = r.Id;
				}
			}
		}

	}

	global Database.QueryLocator start(Database.BatchableContext BC)
	{
      return Database.getQueryLocator(queryString);
    }
	
	global void execute(Database.BatchableContext BC, List<Competitor__c>scope)
	{
		List <Competitor__c> competitorsExpiring = new List<Competitor__c>();
		
   		for (Competitor__c c : scope)
		{
			// See if the expiry date of this Competitor is 3 months or greater and an alert has not already been sent
			if (c.Service_Expiration_Date__c <= Date.Today().addMonths(3) && !c.Service_Expiration_Alert_Sent__c 
				&& (c.Opportunity_Close__c == null || c.Opportunity_Close__c == '' || c.Opportunity_Close__c == 'Lost To'))
			{
				// This Competitor needs an alert sending
				competitorsExpiring.add(c);
			}
		}
		
		if (competitorsExpiring.size() > 0)
		{
			List<Task> alertTasks = new List<Task>();
			
			for (Competitor__c c : competitorsExpiring)
			{
				// Create the Task
				Task t = new Task();
				t.OwnerId = GetAlertOwnerId(c);
				t.WhatId = c.Account__c;
				t.Subject = c.Account__r.Name + '\'s Contract with ' + c.Competitor_Name__c + ' is up in 3 months';
				t.Description = c.Account__r.Name + '\'s Contract with ' + c.Competitor_Name__c + ' is up on ' + c.Service_Expiration_Date__c.format() + '. This is a good time to reach out to them.';  
				t.ActivityDate = Date.today().addDays(1);
				t.RecordTypeId = GetRecordTypeFromUser(t.OwnerId);
				
				alertTasks.add(t);
				
				// Send the Email
				Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
				msg.setTemplateId(templateId);
				msg.setWhatId(c.ID);
				msg.setTargetObjectId(tempContact.id);
		
				List<String> toAddresses = new List<String>();
				toAddresses.add(usersMap.get(t.OwnerId).Email);
				msg.setToAddresses(toAddresses);
		
				// Send the emails in a transaction, then roll it back
				Savepoint sp = Database.setSavepoint();
				List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
				messages.add(msg);
				
				if (!Test.isRunningTest())
				{
					Messaging.sendEmail(messages);
				}
				
				Database.rollback(sp);
		
				// Now Actually Send the Email to the Correct Address
				Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
				emailToSend.setToAddresses(msg.getToAddresses());
				emailToSend.setPlainTextBody(msg.getPlainTextBody());
				emailToSend.setHTMLBody(msg.getHTMLBody());
				emailToSend.setSubject(msg.getSubject());
				List<Messaging.SingleEmailMessage> messagesToSend = new List<Messaging.SingleEmailMessage>();
				messagesToSend.add(emailToSend);
				
				if (!Test.IsRunningTest())
				{
					Messaging.sendEmail(messagesToSend);
				}
				
				//Set the flag to say the alert has been sent
				c.Service_Expiration_Alert_Sent__c = true;
			}
			
			insert alertTasks;
			update competitorsExpiring;
		}
    }
	
	public Id GetAlertOwnerId(Competitor__c c)
	{
		if (c.Account__r.Renewal_Rep__c != null)
		{
			return c.Account__r.Renewal_Rep__c;
		}
		else
		{
			User u = usersMap.get(c.CreatedById);
			
			if (u.IsActive)
			{
				return u.Id;
			}
			else
			{
				if (u.ManagerId != null)
				{
					User m = usersMap.get(u.ManagerId);
					
					if (m.IsActive)
					{
						return m.Id;
					}
				}
			}
		}
		
		return c.Account__r.OwnerId;
	}
	
	public Id GetRecordTypeFromUser(Id userId)
	{
		User userToCheck = usersMap.get(userId);
		String profileName = userToCheck.Profile.Name;
		
		if (profileName.toLowerCase().Contains('renewal'))
		{
			return renewalsTaskRecordTypeId;
		}
		
		return newBizTaskRecordTypeId;
	}
	
	global void finish(Database.BatchableContext BC)
	{
    
    }
	
	global void execute(SchedulableContext SC) 
    {  
		string SOQL = 'Select Id, Name, Service_Expiration_Alert_Sent__c, Opportunity_Close__c, CreatedById, Account__c, Account__r.Name, Account__r.OwnerId, Account__r.Renewal_Rep__c, Brand_Campaign__c, Competitive_Spend__c, Competitor_Name__c, Competitor_Notes__c,  Service_Expiration_Date__c, Service_Provided__c from Competitor__c where (Competitor_Name__c != \'No Competitor\' and Competitor_Name__c != \'Client Won’t Say/Don’t Know\')';
    	Database.executeBatch(new batchCompetitorAlerts(SOQL),10); 
	}
}