CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <description>Added by LM on 3/4/2013; From MS CRM</description>
        <label>Contract Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestContractTrigger.cls
@isTest
private class TestContractTrigger
{
	static testMethod void TestContractNumberAddedToOpp()
	{
		TestLibrary.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.STANDARD_USER_PROFILE);
        insert u;
		
		Account a = TestLibrary.CreateAccount('Test Account', u.Id);  
		a.Renewal_Rep__c = null;
		insert a;
		
		Opportunity opp = TestLibrary.CreateOpportunity('Test', u.Id, a.Id);  
		insert opp;
		
		Test.startTest();
			Contract c = new Contract(Status='Draft', StartDate = Date.today(), ContractTerm = 12, AccountId = a.Id, SBQQ__Opportunity__c = opp.Id);
			insert c;
			update c;
		Test.stopTest();
	
		opp = [Select Id, Contract_Number__c from Opportunity where Id = :opp.Id];
		c = [Select Id, ContractNumber from Contract where Id = :c.Id];
		System.Assert(opp.Contract_Number__c == c.ContractNumber);
	}
}