CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AR_Rep__c</fullName>
        <formula>IF(NAAT__c=TRUE, &quot;Sue Mierop&quot;, IF(BEGINS(Name, &quot;G&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;H&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;I&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;J&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;K&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;L&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;M&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;N&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;O&quot;), &quot;Diana Rene&quot;, IF(BEGINS(Name, &quot;P&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;Q&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;R&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;S&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;T&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;U&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;V&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;W&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;X&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;Y&quot;), &quot;Tony Mace&quot;, IF(BEGINS(Name, &quot;Z&quot;), &quot;Tony Mace&quot;, &quot;Richard Micus&quot;)))))))))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AR Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CisionPoint_ID__c</fullName>
        <description>Added by LM on 2/28/2013; From NetSuite</description>
        <label>CisionPoint ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Credit Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GP_Cust_ID__c</fullName>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>GP Cust ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CisionPoint_ID__c</fullName>
        <formula>Account.CisionPoint_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CisionPoint ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GP_Cust_ID__c</fullName>
        <formula>Account.GP_Cust_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GP Cust ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/OpportunityAlertExtension.cls
public with sharing class OpportunityAlertExtension{
	public Boolean DisplayPopUp {get; set;}
	public Opportunity opp {get; set;}
	public Account acct {get; set;}
	public String AlertMessage {get;set;}
	public OpportunityAlertExtension(ApexPages.StandardController controller) 
    {
		 // Get the Account Record
		String oppId = ApexPages.currentPage().getParameters().get('oid');
		//System.debug('oppId=' + oppId);
		
		if(oppId != null)
		{
			opp = [select Id, Name, Type, AccountId, RecordType.Name from Opportunity where Id = :oppId];
		}
		else
		{
			opp = (Opportunity)controller.getRecord();							
			opp = [select Id, Name, Type, AccountId, RecordType.Name from Opportunity where Id = :opp.Id];
		}	
				
		System.debug('opp=' + opp);
		if(opp.RecordType.Name == 'Transactional Broadcast')
		{
			AlertMessage = 'You can not route any Opps for this Account until the credit hold issue has been resolved. Do NOT create a new Account to bypass the Credit Hold.';	
		}
		else
		{
			AlertMessage = 'If you submit a quote for this Opp prior to it being taken off credit hold, Accounting will have to approve the quote before you can send out the DocuSign contract to the client.  Do NOT create a new Account to bypass the Credit Hold.';
		}
		
		if(opp !=null)	
			acct =  [select Id, Name, Type, CisionPoint_ID__c, AR_Rep__c, Credit_Hold__c, GP_Cust_ID__c from Account where Id = :opp.AccountId]; 			            		
	}

}