CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>New_Biz_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <inlineHelpText>This field shows the last New Biz Rep who has modified the Account or any related Contact, Opp, or Activity in the last 60 days.  The New Biz Named Account Rep, if there is one, will overwrite the New Biz Rep field each night.</inlineHelpText>
        <label>New Biz Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added by LM on 2/7/2013; From MS CRM</description>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Ad_Type__c</fullName>
        <description>Created by LM on 9/18/2013 for Phase 2 rollout; request from Pat</description>
        <label>Ad Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Bing/Yahoo/Adcenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blog</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google/Adwords</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M6/ Dstilery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retargeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Queue__c</fullName>
        <description>Created by LM on 9/5/2013 for Phase 2 rollout</description>
        <label>Team Queue</label>
        <picklist>
            <picklistValues>
                <fullName>New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analysis</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PR_Department_Size__c</fullName>
        <description>Created by LM on 9/27/2013 for Phase 2 rollout</description>
        <label>PR Department Size</label>
        <picklist>
            <picklistValues>
                <fullName>There is a whole bunch of us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>There are a few of us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>It&apos;s just me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>There is no PR department</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>PR_Department_Size__c</fullName>
        <description>Created by LM on 9/27/2013 for Phase 2 rollout</description>
        <label>PR Department Size</label>
        <picklist>
            <picklistValues>
                <fullName>There is a whole bunch of us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>There are a few of us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>It&apos;s just me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>There is no PR department</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Hire_Date__c</fullName>
        <defaultValue>datevalue(&apos;1/1/1900&apos;)</defaultValue>
        <description>Created by LM on 5/6/2014 for Phase2 (requested by Bryan Lehner and Ryan Erwin)</description>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestCampaignMemberTrigger.cls
@isTest
private class TestCampaignMemberTrigger 
{						
	static testMethod void CampaignMemberLeadWithoutRepsNewBizTest() 
	{		
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		//System.runAs(u)
		//{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data		
			Account a = GetAccount();					
			Lead l = GetLead();       		
			Campaign c = GetCampaign();       	
			CampaignMember cm = GetCampaignMember(c.Id, null, l.Id);     
			update cm;
			
			Test.startTest();
			a.Type = Constants.Customer;
	        a.Renewal_Rep__c = null;        
	        a.New_Biz_Rep__c = null;       
	        update a;
	        l.Description = 'Broadcast Renew';
	        l.Company = 'Test llc';
	        update l; 
	        
	        ExecuteCmRules(cm, c, Constants.NewBizQueue);           
	        
	        Test.stopTest();    
		//}
	}
	
	static testMethod void CampaignMemberLeadWithoutRepsLeadGenTest() 
	{		
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		//System.runAs(u)
		//{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data		
			Account a = GetAccount();					
			Lead l = GetLead();       		
			Campaign c = GetCampaign();       	
			CampaignMember cm = GetCampaignMember(c.Id, null, l.Id);       
			
			Test.startTest();
			a.Type = Constants.Customer;
	        a.Renewal_Rep__c = null;        
	        a.New_Biz_Rep__c = null;       
	        update a;
	        l.Description = 'Broadcast Renew';
	        l.Company = 'hospital';
	        update l; 
	                
	        ExecuteCmRules(cm, c, Constants.LeadGenerationQueue);        
	        
	        Test.stopTest();        		
		//}
	}
	
	      	
	
    static testMethod void CampaignMemberContactWithRepsNewBizTest()
    {
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
		
		User admin = TestLibrary.createUser ('Test2', TestLibrary.SYSTEM_ADMIN_USER_PROFILE);
        insert admin;
        
		System.runAs(u)
		{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data
			Account a = GetAccount();	
			a.Name = 'Test hospital';
			System.runAs(admin)
			{
				update a;
			}
			
			Contact cont = GetContact(a.Id);		        
			Campaign c = GetCampaign();       
			CampaignMember cm = GetCampaignMember(c.Id, cont.Id, null); 
	        
	        Test.startTest();
			cont.Description = 'international database monitoring';        
	        update cont;      
	        a.Renewal_Rep__c = TestingUtils.BT_MANAGER.Id;
	        a.New_Biz_Rep__c = TestingUtils.BT_MANAGER.Id;
			
			System.runAs(admin)
			{
	        	update a;
			}
	        
	      	ExecuteCmRules(cm, c, Constants.NewBizQueue);          
	        
	        Test.stopTest();  
		}
    }
	
	static testMethod void CampaignMemberContactWithRepsLeadGenTest()
    {
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		System.runAs(u)
		{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data
			Account a = GetAccount();			
			Contact cont = GetContact(a.Id);		        
			Campaign c = GetCampaign();       
			CampaignMember cm = GetCampaignMember(c.Id, cont.Id, null); 
	        
	        Test.startTest();
			cont.Description = 'Broadcast Renew';        
	        update cont;      
	        a.Renewal_Rep__c = TestingUtils.BT_MANAGER.Id;
	        a.New_Biz_Rep__c = TestingUtils.BT_MANAGER.Id;
	        update a;
	        
	        ExecuteCmRules(cm, c, Constants.LeadGenerationQueue);  
	        
	        Test.stopTest();  
		}
    }	
    
	static testMethod void CampaignMemberContactWithoutRepsNewBizTest() 
	{
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		System.runAs(u)
		{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data
			Account a = GetAccount();			
			Contact cont = GetContact(a.Id);		        
			Campaign c = GetCampaign();       
			CampaignMember cm = GetCampaignMember(c.Id, cont.Id, null);      
			
			Test.startTest();
			
	        cont.Description = 'Broadcast Renew';        
	        update cont; 
	        
	        a.Renewal_Rep__c = null;        
	        a.New_Biz_Rep__c = null;       
	        update a;
	        
	        ExecuteCmRules(cm, c, Constants.NewBizQueue);         
	        
	        Test.stopTest();        
		}
	}   
	
	static testMethod void CampaignMemberContactWithoutRepsLeadGenTest() 
	{
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		System.runAs(u)
		{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data
			Account a = GetAccount();			
			Contact cont = GetContact(a.Id);		        
			Campaign c = GetCampaign();       
			CampaignMember cm = GetCampaignMember(c.Id, cont.Id, null);      
			
			Test.startTest();
			
	        cont.Description = 'Broadcast Renew';        
	        update cont; 
	        
	        a.Renewal_Rep__c = null;        
	        a.New_Biz_Rep__c = null;       
	        update a;
	        
	        ExecuteCmRules(cm, c, Constants.LeadGenerationQueue);  
	        
	        Test.stopTest();     
		}
	}   

	static testMethod void CampaignMemberLeadWithoutRepsRenewalsRegionalLeadGenTest() 
	{		
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		//System.runAs(u)
		//{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data		
			Account a = GetAccount();					
			Lead l = GetLead();       		
			Campaign c = GetCampaign();       	
			CampaignMember cm = GetCampaignMember(c.Id, null, l.Id);       
			
			Test.startTest();
			
	        a.Renewal_Rep__c = null;        
	        a.New_Biz_Rep__c = null;       
	        update a;
	        l.Description = 'Broadcast Renew';
	        l.Company = 'hospital';
	        update l; 
	        
	        ExecuteCmRules(cm, c, Constants.RenewalsQueue);   
	        ExecuteCmRules(cm, c, Constants.RegionalLeadGen);        
	        
	        Test.stopTest();        
		//}
	}    
    
    static testMethod void CampaignMemberLeadWithRepsRenewalsRegionalLeadGenTest() 
	{		
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		///System.runAs(u)
		//{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data		
			Account a = GetAccount();					
			Lead l = GetLead();       		
			Campaign c = GetCampaign();       	
			CampaignMember cm = GetCampaignMember(c.Id, null, l.Id);       
			
			Test.startTest();
			
	        a.Renewal_Rep__c = TestingUtils.BT_MANAGER.Id;
	        a.New_Biz_Rep__c = TestingUtils.BT_MANAGER.Id;   
	        update a;
	        l.Description = 'Renew tv';
	        l.Company = 'hospital';
	        update l; 
	        
	        ExecuteCmRules(cm, c, Constants.RenewalsQueue);   
	        ExecuteCmRules(cm, c, Constants.RegionalLeadGen);        
	        
	        Test.stopTest();        
		//}
	}    
	
    static testMethod void CampaignMemberContactWithoutRepsRenewalsRegionalLeadGenGenTest() 
	{
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		System.runAs(u)
		{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data
			Account a = GetAccount();			
			Contact cont = GetContact(a.Id);		        
			Campaign c = GetCampaign();       
			CampaignMember cm = GetCampaignMember(c.Id, cont.Id, null);      
			
			Test.startTest();
			
	        cont.Description = 'Monitoring';        
	        update cont; 
	        
	        a.Renewal_Rep__c = null;        
	        a.New_Biz_Rep__c = null;       
	        update a;
	        
	        ExecuteCmRules(cm, c, Constants.RenewalsQueue);   
	        ExecuteCmRules(cm, c, Constants.RegionalLeadGen);  
	        
	        Test.stopTest();      
		}
	}   
    
    static testMethod void CampaignMemberContactWithoutRepsRenewalsRegionalLeadGenTest() 
	{
		TestingUtils.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.MARKETING_PROFILE);
        insert u;
        
		System.runAs(u)
		{
			TestingUtils.AddRoundRobinGroupsForMarketingCampaigns();
			//Set Up Data
			Account a = GetAccount();			
			Contact cont = GetContact(a.Id);		        
			Campaign c = GetCampaign();       
			CampaignMember cm = GetCampaignMember(c.Id, cont.Id, null);      
			
			Test.startTest();
			
	        cont.Description = 'Broadcast Renew';        
	        update cont; 
	        
	        a.Renewal_Rep__c = null;        
	        a.New_Biz_Rep__c = null;       
	        update a;
	        
	        ExecuteCmRules(cm, c, Constants.RenewalsQueue);   
	        ExecuteCmRules(cm, c, Constants.RegionalLeadGen);  
	        
	        Test.stopTest();        
		}
	}   
	private static Account GetAccount()
	{		
		Account a = TestingUtils.CreateAccount();   
        a.Renewal_Rep__c = TestingUtils.BT_MANAGER.Id;
        a.New_Biz_Rep__c = null;
		a.BillingState = 'IL';
		insert a;
		System.assert(a.Id != null);
		
		return a;
	}
	    
	private static Contact GetContact(Id accountId)
	{		
		List<Contact> contacts = TestingUtils.createContacts(1, accountId, false);        
        Contact cont = contacts.get(0);
        cont.Description = 'hospital';
		
        insert cont;
		System.assert(cont != null);
		
		return cont;
	}
	
	private static Lead GetLead()
	{
		List<Lead> leads = TestingUtils.createLeads(1, false);
        Lead l = leads.get(0);
        //User u = [SELECT Id, Name from User where Name = 'Eloqua Admin'];\
		Profile p = [select id from profile where name='Marketing'];

		User u = new User(FirstName='Eloqua', LastName='Admin', UserName='EloquaAdmin@cisionus.com', Email='test11@cisionus.com', Alias='alias',
                                LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', CommunityNickname='nickname',
                                ProfileId=p.Id, TimeZoneSidKey='America/New_York', isActive = true, Hire_Date__c = Date.today() );
		insert u;
        l.OwnerId = u.Id;     
        l.PR_Department_Size__c = Constants.MoreThan1000;
		insert l;
        System.assert(l.Id != null);
		
		return l;
	}
	
	private static Campaign GetCampaign()
	{
		List<Campaign> campaigns = TestingUtils.createCampaigns(1, false);
        Campaign c = campaigns.get(0);		 
		//c.Type = 'Sales Lead (1)';
		c.Type = 'Email';
		c.Ad_Type__c = '3rd Party';
		insert c;
		System.assert(c.Id != null);
		
		return c;
	}
	
	private static CampaignMember GetCampaignMember(Id campaignId, Id contactId, Id leadId)
	{
		CampaignMember cm = TestingUtils.createCampaignMember(campaignId, contactId);
        cm.Status = Constants.CampaignResponded;
        cm.CampaignId = campaignId;        
        cm.ContactId = contactId;
        cm.LeadId = leadId;		
		insert cm;
		System.assert(cm.Id != null);
		
		return cm;
	}
    
	
    private static void ExecuteCmRules(CampaignMember cm, Campaign c, String teamQueue)
    {
        if(teamQueue == Constants.NewBizQueue)
        {
          	//New Biz with Contact                
            c.Team_Queue__c = Constants.NewBizQueue;
            update c;        
            CampaignMemberHelper.ExecuteCampaignMemberRules(cm);               
        }
        else if(teamQueue == Constants.RenewalsQueue)
        {
             //Renewals
            c.Team_Queue__c = Constants.RenewalsQueue;
            update c;
            CampaignMemberHelper.ExecuteCampaignMemberRules(cm);
        }
		else if(teamQueue == Constants.LeadGenerationQueue)
        {
        	//Lead Generation
        	c.Team_Queue__c = Constants.LeadGenerationQueue;
			update c;
			CampaignMemberHelper.ExecuteCampaignMemberRules(cm);
        }       
        else if(teamQueue == Constants.RegionalLeadGen)
        {
            //Regional Lead Gen
            c.Team_Queue__c = Constants.RegionalLeadGen;
            update c;
            CampaignMemberHelper.ExecuteCampaignMemberRules(cm);  
        }
    }
}