CS_PROD_20150209_01/Metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Required_Invoice_Contact_Email__c</fullName>
        <description>Created by LM on 9/4/2013 for Phase 1 rollout</description>
        <label>Required Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Required_Invoice_Contact_Name__c</fullName>
        <description>Created by LM on 9/4/2013 for Phase 1 rollout</description>
        <label>Required Invoice Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestNewOpportunity.cls
@isTest
private class TestNewOpportunity
{
	static testMethod void TestNewOpportunity() 
    {
		TestLibrary.InitAvaTax();
    
      	User u = TestLibrary.createUser ('Testuser', TestLibrary.BROADCAST_TRANSACTION_PROFILE);
        insert u;
        
    	Account acc = TestLibrary.CreateAccount('Test Account', u.Id);  
        acc.Required_Invoice_Contact_Name__c = 'Jitter Bit';
        acc.Required_Invoice_Contact_Email__c = 'jbit@email.com';
    	insert acc;
		     		
        Opportunity newOpp = TestLibrary.CreateOpportunity('TestOp', u.Id, acc.Id);
        newOpp.RecordTYpeId = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
	    insert newOpp;
        
		Test.startTest();   
      		ApexPages.StandardController stdController = new ApexPages.StandardController(newOpp);
      		NewOpportunityController tst = new NewOpportunityController(stdController);
      		tst.getNewOppPage();  
      	Test.stopTest();
    }
}