CS_PROD_20150209_01/Metadata/unpackaged/objects/Broadcast_Item__c.object
<CustomObject>
    <description>This object will used to house Broadcast Items that come in and created through VisualFlow Pages.</description>
    <fields>
        <fullName>Air_Date_Time__c</fullName>
        <formula>TEXT(MONTH(Air_Date__c)) + &quot;/&quot; + 
TEXT(DAY(Air_Date__c)) + &quot;/&quot; + 
RIGHT(TEXT(YEAR(Air_Date__c)),2)    &amp; &quot; &quot; &amp; Air_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Air Date/Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Do_Not_Print_On_Labels__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is to prevent the Broadcast Item from being displayed when printing Broadcast Labels.</description>
        <inlineHelpText>This is to prevent the Broadcast Item from being displayed when printing Broadcast Labels.</inlineHelpText>
        <label>Do Not Print On Labels</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ItemNumber__c</fullName>
        <label>Item #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Station__c</fullName>
        <formula>IF(ISBLANK(Text(US_Markets__c )), IF(ISBLANK(Text(Cable_National_Markets__c )), IF(ISBLANK(Text( Canadian_International_Markets__c)), IF(ISBLANK(Text( Radio_Markets__c)), IF(ISBLANK(Write_In_Station__c),&quot;&quot;, Write_In_Station__c), Text( Radio_Markets__c) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text( Radio_Stations__c)), Write_In_Station__c, Text( Radio_Stations__c))), Text( Canadian_International_Markets__c) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text(Canadian_International_Stations__c)), Write_In_Station__c, Text(Canadian_International_Stations__c)) ) , Text(Cable_National_Markets__c ) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text(Cable_National_Stations__c)), Write_In_Station__c, Text(Cable_National_Stations__c))) , Text(US_Markets__c) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text(US_Stations__c)), Write_In_Station__c, Text(US_Stations__c)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market/Station</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <formula>Opportunity__r.Opportunity_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Title__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Program Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Description__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Subject/Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRT__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <inlineHelpText>This is the Total Running Time of the Clip.  TRT format is HH:MM:SS</inlineHelpText>
        <label>TRT</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Broadcast Item</label>
    <nameField>
        <displayFormat>BCast-{0000000000}</displayFormat>
        <label>Item Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <description>Added by LM on 2/21/2013</description>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/OpportunityPrintBroadcastItemsExtension.cls
public with sharing class OpportunityPrintBroadcastItemsExtension{
	
	public List<Broadcast_Item__c> lineItemsList {get; set;}
	public String BroadcastItemListHeader {get; set;}
	public Opportunity opp {get; set;}	
	
	public OpportunityPrintBroadcastItemsExtension(ApexPages.StandardController controller) 
    {
		opp = (Opportunity)controller.getRecord();
    	if (opp != null)
    	{
    		opp = [select Id, Name, opportunity_number__c, accountId from Opportunity where Id = :opp.Id]; 
			GetBroadcastItemList();
    	}
	}
	
	private void GetBroadcastItemList()
	{
		lineItemsList = [select Id, Market_Station__c, itemnumber__c, program_title__c, air_date_time__c, trt__c, Do_Not_Print_On_Labels__c, Subject_Description__c from Broadcast_Item__c where opportunity_number__c = :opp.opportunity_number__c and Do_Not_Print_On_Labels__c = false];
		Broadcast_Item__c item = lineItemsList.get(0);
		BroadcastItemListHeader = item.Subject_Description__c;
	}
}