CS_PROD_20150209_01/Metadata/unpackaged/objects/Broadcast_Item__c.object
<CustomObject>
    <description>This object will used to house Broadcast Items that come in and created through VisualFlow Pages.</description>
    <fields>
        <fullName>Air_Date_Time_Time_Zone__c</fullName>
        <formula>TEXT(MONTH(Air_Date__c)) + &quot;/&quot; + 
TEXT(DAY(Air_Date__c)) + &quot;/&quot; + 
RIGHT(TEXT(YEAR(Air_Date__c)),2) &amp; &quot; &quot; &amp; Air_Time__c &amp; &quot; &quot; &amp; TEXT(Time_Zone__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Air Date/Time/Time Zone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format_Options__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Format Options</label>
        <picklist>
            <picklistValues>
                <fullName>Windows Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quicktime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MPEG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MPEG2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>other - see  order instructions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ItemNumber__c</fullName>
        <label>Item #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>A concatenation field meant to display all the pertinent Broadcast Item / Product detail information in one field for use in Related List columns.</description>
        <formula>IF(AND(Search_Fee__c &gt;0, ISPICKVAL(Search_Request_Status__c, &quot;Not Found&quot;)), &quot;Search Fee&quot;, IF (ISBLANK(TEXT(Product_Detail__c)), TEXT(Inventory_Item__c) &amp; IF(INCLUDES(Attributes__c, &quot;Buzz Graph&quot;), &quot; - Buzz Graph&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Slate(s)&quot;), &quot; - Slate(s)&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Teaser&quot;), &quot; - Teaser&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Nielsen (TV)&quot;), &quot; - Nielsen (TV)&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Arbitron (Radio)&quot;), &quot; - Arbitron (Radio)&quot;,&quot;&quot;) , TEXT(Inventory_Item__c)  &amp; &quot; - &quot; &amp;  TEXT(Product_Detail__c) &amp; IF(INCLUDES(Attributes__c, &quot;Buzz Graph&quot;), &quot; - Buzz Graph&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Slate(s)&quot;), &quot; - Slate(s)&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Teaser&quot;), &quot; - Teaser&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Nielsen (TV)&quot;), &quot; - Nielsen (TV)&quot;,&quot;&quot;) &amp; IF(INCLUDES(Attributes__c, &quot;Arbitron (Radio)&quot;), &quot; - Arbitron (Radio)&quot;,&quot;&quot;) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Station__c</fullName>
        <formula>IF(ISBLANK(Text(US_Markets__c )), IF(ISBLANK(Text(Cable_National_Markets__c )), IF(ISBLANK(Text( Canadian_International_Markets__c)), IF(ISBLANK(Text( Radio_Markets__c)), IF(ISBLANK(Write_In_Station__c),&quot;&quot;, Write_In_Station__c), Text( Radio_Markets__c) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text( Radio_Stations__c)), Write_In_Station__c, Text( Radio_Stations__c))), Text( Canadian_International_Markets__c) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text(Canadian_International_Stations__c)), Write_In_Station__c, Text(Canadian_International_Stations__c)) ) , Text(Cable_National_Markets__c ) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text(Cable_National_Stations__c)), Write_In_Station__c, Text(Cable_National_Stations__c))) , Text(US_Markets__c) &amp; &quot; - &quot; &amp; IF(ISBLANK(Text(US_Stations__c)), Write_In_Station__c, Text(US_Stations__c)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market/Station</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Broadcast_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PinPoint_Notes__c</fullName>
        <label>PinPoint Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program_Title__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Program Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Description__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Subject/Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRT__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <inlineHelpText>This is the Total Running Time of the Clip.  TRT format is HH:MM:SS</inlineHelpText>
        <label>TRT</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_after_Tax__c</fullName>
        <formula>Subtotal_w_Discount__c  + Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Broadcast Item</label>
    <nameField>
        <displayFormat>BCast-{0000000000}</displayFormat>
        <label>Item Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Order_Instructions__c</fullName>
        <description>Added by LM on 2/21/2013; From NetSuite</description>
        <label>Opportunity Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PinPoint_Notes__c</fullName>
        <description>Added by LM on 2/21/2013; From NetSuite</description>
        <label>PinPoint Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/OpportunityPrintViewExtension.cls
public with sharing class OpportunityPrintViewExtension
{
    public Opportunity opp {get; set;}
    public List<Broadcast_Item__c> BroadcastItems{get; Set;}
    
    // Store the data for the field sets
    public List<Schema.FieldSetMember> LeftDetailFields{get;Set;}
    public List<Schema.FieldSetMember> RightDetailFields{get;Set;}
    public List<Schema.FieldSetMember> LeftRCNFields{get;Set;}
	//public List<Schema.FieldSetMember> RightRCNFields{get;Set;}
    public List<Schema.FieldSetMember> LeftShippingFields{get;Set;}
    public List<Schema.FieldSetMember> RightShippingFields{get;Set;}
        
    
    public OpportunityPrintViewExtension(ApexPages.StandardController controller) 
    {
        // Get the Opp Record
        opp = (Opportunity)controller.getRecord();
        
        if (opp != null)
        {
            List<Schema.FieldSetMember> oppDetailsList = SObjectType.Opportunity.FieldSets.Opportunity_Details.getFields();
            LeftRCNFields = SObjectType.Opportunity.FieldSets.Recurring_Client_Needs.getFields();
            List<Schema.FieldSetMember> oppShippingList = SObjectType.Opportunity.FieldSets.Shipping.getFields();
                        
            // Query the fields we want form the opp
            String query = 'SELECT ';
            for(Schema.FieldSetMember f : oppDetailsList)
            {
                query += f.getFieldPath() + ', ';
            }
            for(Schema.FieldSetMember f : LeftRCNFields)
            {
                query += f.getFieldPath() + ', ';
            }
            for(Schema.FieldSetMember f : oppShippingList)
            {
                query += f.getFieldPath() + ', ';
            }
            
            query += 'Id, Order_Instructions__c FROM Opportunity where Id = \'' + opp.Id + '\'';
            opp = Database.query(query);
                                
            // Process the fields for display purposes
			LeftDetailFields = new List<Schema.FieldSetMember>();
            RightDetailFields = new List<Schema.FieldSetMember>();
			//LeftRCNFields = new List<Schema.FieldSetMember>();
			//RightRCNFields = new List<Schema.FieldSetMember>();
            LeftShippingFields = new List<Schema.FieldSetMember>();
            RightShippingFields = new List<Schema.FieldSetMember>();
                        
            Integer currentFieldNo = 1;
			for (Schema.FieldSetMember fm : oppDetailsList)
            {
                if (currentFieldNo <= oppDetailsList.size()/2)
                {
                    LeftDetailFields.add(fm);     
                }
                else
                {
                    RightDetailFields.add(fm);
                }
                
                currentFieldNo++;
            }
            
			currentFieldNo = 1;
            for (Schema.FieldSetMember fm : oppShippingList)
            {
                if (currentFieldNo <= oppShippingList.size()/2)
                {
                    LeftShippingFields.add(fm);     
                }
                else
                {
                    RightShippingFields.add(fm);
                }
                
                currentFieldNo++;
            }
			    
                    
            
            BroadcastItems = [Select Id, Name, ItemNumber__c, PinPoint_Notes__c, Item__c, Format_Options__c, Market_Station__c, Air_Date_Time_Time_Zone__c, Program_Title__c, Subject_Description__c, TRT__c, Total_after_Tax__c from Broadcast_Item__c where Opportunity__c = :opp.Id order by  CreatedDate];
        }
    }

}