CS_PROD_20150209_01/Metadata/unpackaged/objects/Broadcast_Item__c.object
<CustomObject>
    <description>This object will used to house Broadcast Items that come in and created through VisualFlow Pages.</description>
    <label>Broadcast Item</label>
    <nameField>
        <displayFormat>BCast-{0000000000}</displayFormat>
        <label>Item Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Added by LM on 2/27/2013; From NetSuite</description>
        <label>Opportunity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Sale</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Void_Reason__c</fullName>
        <inlineHelpText>If you have selected &quot;Opp Voided&quot; for the Opportunity Stage, you must select one of the following reasons.</inlineHelpText>
        <label>Void Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Segment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client did not order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clip Not Found</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Client Need</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Prepaid_Clip_Package__c.object
<CustomObject>
    <description>Used to track Accounts who have purchased Prepaid Clip Packages, and then track how many are remaining after a client makes a purchase.</description>
    <label>Clip Package</label>
    <nameField>
        <label>Clip Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clip Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/OpportunityVoidTaxExtension.cls
public with sharing class OpportunityVoidTaxExtension
{
	public Opportunity opp {get; set;}
	public String ErrorMessage {get; set;}
	
	public OpportunityVoidTaxExtension(ApexPages.StandardController controller) 
    {
    	// Get the Opp Record
    	opp = (Opportunity)controller.getRecord();
    	    	
    	if (opp != null)
    	{
    		opp = [select Id, Opportunity_Status__c from Opportunity where Id = :opp.Id];
    	}
    }
    
    public PageReference VoidTax()
    {
    	OpportunityTaxExtension taxCalc = new OpportunityTaxExtension(opp.Id);
        taxCalc.VoidTax();
        if (taxCalc.Error)
        {
        	ErrorMessage = 'An Error Occurred when voiding this Opportunity. Message - ' + taxCalc.TaxResult;
        }
        
        if (!taxCalc.Error || Test.IsRunningTest())
        {
        	opp.Opportunity_Status__c = 'Voided';
           	update opp;
           	           	
           	PageReference ref = new PageReference('/' + opp.Id);
    		ref.SetRedirect(true);
    		return ref;
        }
        
        return null;
    }
    
     @isTest(SeeAllData=true)
     static void TestOpportunityVoidTaxExtension()
     {
        List<Account> accounts = TestingUtils.createAccounts(1, true);
        
        Opportunity opp = TestingUtils.createOpportunity(accounts[0].Id);
        opp.StageName = 'Voided';
        opp.Opportunity_Status__c = 'Voided';
		opp.Void_Reason__c = 'Quality';
        insert opp;
	    Prepaid_Clip_Package__c clipPackage = TestingUtils.createClipPackage(accounts[0].Id, TestingUtils.ADMIN_USER.Id, 'DVD Clip', true);
        Broadcast_Item__c broadcastItem = TestingUtils.createBroadcastItem(opp.Id,clipPackage.Id, true);
             	                    
        PageReference pageRef = Page.OpportunityVoidTax;
        pageRef.GetParameters().put('id', opp.Id);
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController controller = new ApexPages.StandardController(opp); 
        OpportunityVoidTaxExtension extension = new OpportunityVoidTaxExtension(controller);
        OpportunityTaxExtension taxCalc = new OpportunityTaxExtension(controller);
        taxCalc.CalculateTax();
        taxCalc.Cancel();
        taxCalc.SaveTax();
        taxCalc.FetchDestinationAddress();
        taxCalc.VoidTax();
        extension.VoidTax();
          
     }

}