CS_PROD_20150209_01/Metadata/unpackaged/objects/Broadcast_Item__c.object
<CustomObject>
    <description>This object will used to house Broadcast Items that come in and created through VisualFlow Pages.</description>
    <fields>
        <fullName>Clip_Package__c</fullName>
        <label>Clip Package</label>
        <referenceTo>Prepaid_Clip_Package__c</referenceTo>
        <relationshipLabel>Broadcast Items</relationshipLabel>
        <relationshipName>Broadcast_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Update_From_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to fire Broadcast Item trigger when parent Opportunity updates Redo Item and/or parent Clip Package updates No Clip Package.</description>
        <label>Update From Parent</label>
        <type>Checkbox</type>
    </fields>
    <label>Broadcast Item</label>
    <nameField>
        <displayFormat>BCast-{0000000000}</displayFormat>
        <label>Item Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Prepaid_Clip_Package__c.object
<CustomObject>
    <description>Used to track Accounts who have purchased Prepaid Clip Packages, and then track how many are remaining after a client makes a purchase.</description>
    <fields>
        <fullName>No_Clip_Package__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Clip Package</label>
        <type>Checkbox</type>
    </fields>
    <label>Clip Package</label>
    <nameField>
        <label>Clip Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clip Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/PrepaidClipPackageServices.cls
public with sharing class PrepaidClipPackageServices 
{
   	
    public static void updateBroadcastItems(List<Prepaid_Clip_Package__c> newClipPackages, Map<ID, Prepaid_Clip_Package__c> oldClipPackages)
	{
    
		List<Prepaid_Clip_Package__c> clipPackagesToProcess = getClipPackagesToProcess(newClipPackages, oldClipPackages);
    	
    	Set<ID> cpIds = new Set<ID>();
	    
	    for(Prepaid_Clip_Package__c cp : clipPackagesToProcess)
	    {
	            cpIds.add(cp.Id);
	    }
	    
	    List<Prepaid_Clip_Package__c> updatedClipPackages = [SELECT Id, (Select Id, Update_From_Parent__c from Broadcast_Items__r)  FROM Prepaid_Clip_Package__c WHERE Id IN :cpIds];
	 
	    List<Broadcast_Item__c> broadcastItems = new List<Broadcast_Item__c>();
	    
	    for (Prepaid_Clip_Package__c cp : updatedClipPackages)
	    {
	    	
	        // Loop through each BroadcastItem record
	        for(Broadcast_Item__c bi : cp.Broadcast_Items__r)
	        {
	            bi.Update_From_Parent__c = (!bi.Update_From_Parent__c);
	            broadcastItems.add(bi);
	        }
	        
	    }
	    
	    //update Broadcast Items
	    try
        {
            Database.update(broadcastItems);
        }
        catch (System.DmlException e) 
        {
            for (Integer i = 0; i < e.getNumDml(); i++) 
            {
        		System.debug(e.getDmlMessage(i));
            }
        }
        
 	}
 	
 	public static List<Prepaid_Clip_Package__c> getClipPackagesToProcess(List<Prepaid_Clip_Package__c> newClipPackages, Map<ID, Prepaid_Clip_Package__c> oldClipPackages)
 	{
 		List<Prepaid_Clip_Package__c> clipPackagesToProcess = new List<Prepaid_Clip_Package__c>();
 		
 		//Only process those ClipPackages where the field No_Clip_Package__c has been updated
 		
 		for (Prepaid_Clip_Package__c cp : newClipPackages) 
 		{
        	Prepaid_Clip_Package__c oldOppty = oldClipPackages.get(cp.ID);
        	if (cp.No_Clip_Package__c != oldOppty.No_Clip_Package__c) 
        	{
            	clipPackagesToProcess.add(cp);
        	}
    	}
    	
    	return clipPackagesToProcess;
 	}

}