CS_PROD_20150209_01/Metadata/unpackaged/objects/Broadcast_Item__c.object
<CustomObject>
    <description>This object will used to house Broadcast Items that come in and created through VisualFlow Pages.</description>
    <fields>
        <fullName>Account_Level_Discount__c</fullName>
        <formula>Opportunity__r.Account_Level_Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Level Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Add_l_10_minutes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Add&apos;l 10 minutes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Clip_Package__c</fullName>
        <label>Clip Package</label>
        <referenceTo>Prepaid_Clip_Package__c</referenceTo>
        <relationshipLabel>Broadcast Items</relationshipLabel>
        <relationshipName>Broadcast_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exclude_Add_l_10_Min_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Add&apos;l 10 Min Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Outside_Market_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Outside Market Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>How_many_Clip_Packages_to_pay_for_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>If using additional Clip Packages to pay for downstream fees, enter the number of additional Clip Packages being used to cover those fees.</inlineHelpText>
        <label>How many Clip Packages to pay for Fees?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Misc_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Misc. Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outside_Market_Fee_100_150__c</fullName>
        <formula>CASE(US_Markets__c,
&quot;GN: Greenville-New Bern-Washington. NC [101]&quot; , 75,
&quot;JA: Johnstown-Altoona. PA [102]&quot; , 75,
&quot;EV: Evansville. IN [104]&quot; , 75,
&quot;LH: Lincoln &amp; Hastings- Kearney. NE [105]&quot; , 75,
&quot;TT: Tallahassee. FL- Thomasville. GA [106]&quot; , 75,
&quot;TL: Tyler-Longview- Lufkin &amp; Nacogdoches. TX [107]&quot; , 75,
&quot;RE: Reno. NV [108]&quot; , 75,
&quot;FW: Ft Wayne. IN [109]&quot; , 75,
&quot;YT: Youngstown. OH [110]&quot; , 75,
&quot;AG: Augusta. GA [111]&quot; , 75,
&quot;BS: Boise. ID [112]&quot; , 75,
&quot;SM: Sioux Falls (Mitchell). SD [113]&quot; , 75,
&quot;HS: Springfield-Holyoke. MA [114]&quot; , 75,
&quot;LN: Lansing. MI [115]&quot; , 75,
&quot;PE: Peoria-Bloomington. IL [116]&quot; , 75,
&quot;FC: Fargo-Valley City. ND [117]&quot; , 75,
&quot;EU: Eugene. OR [121]&quot; , 75,
&quot;SB: Santa Barbara-Santa Maria-San Luis Obispo. CA [122]&quot; , 75,
&quot;YR: Yakima-Pasco-Richland-Kennewick. WA [123]&quot; , 75,
&quot;LF: Lafayette. LA [124]&quot; , 75,
&quot;MO: Monterey-Salinas. CA [125]&quot; , 75,
&quot;BK: Bakersfield. CA [126]&quot; , 75,
&quot;CB: Columbus. GA [127]&quot; , 75,
&quot;EC: La Crosse-Eau Claire. WI [128]&quot; , 75,
&quot;CC: Corpus Christi. TX [129]&quot; , 75,
&quot;AM: Amarillo. TX [130]&quot; , 75,
&quot;RC: Chico-Redding. CA [131]&quot; , 75,
&quot;WL: Wilmington. NC [132]&quot; , 75,
&quot;WR: Wausau-Rhinelander. WI [135]&quot; , 75,
&quot;TK: Topeka. KS [136]&quot; , 75,
&quot;CJ: Columbia-Jefferson City. MO [138]&quot; , 75,
&quot;DS: Duluth. MN-Superior. WI [139]&quot; , 75,
&quot;BT: Beaumont-Port Arthur. TX [141]&quot; , 75,
&quot;LB: Lubbock. TX [143]&quot; , 75,
&quot;SI: Salisbury. MD [144]&quot; , 75,
&quot;PS: Palm Springs. CA [145]&quot; , 75,
&quot;EE: Erie. PA [146]&quot; , 75,
&quot;SX: Sioux City. IA [147]&quot; , 75,
&quot;AA: Anchorage. AK [148]&quot; , 75,
&quot;AY: Albany. GA [150]&quot; , 75,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outside Market Fee 101 - 150</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outside_Market_Fee_150__c</fullName>
        <formula>CASE(US_Markets__c,
&quot;OD: Odessa-Midland. TX [151]&quot; , 100,
&quot;BM: Bismarck-Minot-Dickinson. ND [152]&quot; , 100,
&quot;RM: Rochester. MN-Mason City. IA-Austin. MN [153]&quot; , 100,
&quot;TH: Terre Haute. IN [154]&quot; , 100,
&quot;BB: Bluefield-Beckley-Oak Hill. WV [155]&quot; , 100,
&quot;BN: Bangor. ME [155]&quot; , 100,
&quot;BI: Binghamton. NY [157]&quot; , 100,
&quot;WG: Wheeling. WV-Steubenville. OH [158]&quot; , 100,
&quot;PC: Panama City. FL [159]&quot; , 100,
&quot;AS: Sherman. TX-Ada. OK [161]&quot; , 100,
&quot;BX: Biloxi-Gulfport. MS [162]&quot; , 100,
&quot;GV: Gainesville. FL [163]&quot; , 100,
&quot;AB: Abilene-Sweetwater. TX [164]&quot; , 100,
&quot;MU: Missoula. MT [165]&quot; , 100,
&quot;YE: Yuma. AZ-El Centro. CA [166]&quot; , 100,
&quot;BL: Billings. MT [168]&quot; , 100,
&quot;DN: Dothan. AL [169]&quot; , 100,
&quot;CK: Clarksburg-Weston. WV [170]&quot; , 100,
&quot;QH: Quincy. IL-Hannibal. MO-Keokuk. IA [171]&quot; , 100,
&quot;UT: Utica. NY [172]&quot; , 100,
&quot;RY: Rapid City. SD [173]&quot; , 100,
&quot;EL: Elmira. NY [174]&quot; , 100,
&quot;LC: Lake Charles. LA [175]&quot; , 100,
&quot;JS: Jackson. TN [176]&quot; , 100,
&quot;WN: Watertown. NY [177]&quot; , 100,
&quot;HB: Harrisonburg. VA [178]&quot; , 100,
&quot;AX: Alexandria. LA [179]&quot; , 100,
&quot;MQ: Marquette. MI [180]&quot; , 100,
&quot;JB: Jonesboro. AR [181]&quot; , 100,
&quot;BG: Bowling Green. KY [182]&quot; , 100,
&quot;CV: Charlottesville. VA [183]&quot; , 100,
&quot;LO: Laredo. TX [185]&quot; , 100,
&quot;MD: Meridian. MS [186]&quot; , 100,
&quot;GG: Greenwood-Greenville. MS [187]&quot; , 100,
&quot;BZ: Butte-Bozeman. MT [189]&quot; , 100,
&quot;GF: Great Falls. MT [190]&quot; , 100,
&quot;TF: Twin Falls. ID [191]&quot; , 100,
&quot;BE: Bend. OR [193]&quot; , 100,
&quot;UR: Eureka. CA [194]&quot; , 100,
&quot;CY: Cheyenne. WY-Scottsbluff. NE [195]&quot; , 100,
&quot;CR: Casper-Riverton. WY [196]&quot; , 100,
&quot;AO: San Angelo. TX [197]&quot; , 100,
&quot;OK: Ottumwa. IA-Kirksville. MO [199]&quot; , 100,
&quot;SJ: St Joseph. MO [200]&quot; , 100,
&quot;LI: Lima. OH [201]&quot; , 100,
&quot;FB: Fairbanks. AK [202]&quot; , 100,
&quot;ZA: Zainesville, OH [203]&quot; , 100,
&quot;VC: Victoria. TX [204]&quot; , 100,
&quot;HA: Helena. MT [206]&quot; , 100,
&quot;JU: Juneau. AK [207]&quot; , 100,
&quot;AP: Alpena. MI [208]&quot; , 100,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outside Market Fee 151 +</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outside_Market_Fee_26_50__c</fullName>
        <formula>CASE(US_Markets__c,
&quot;IN: Indianapolis. IN [26]&quot; , 25,
&quot;BA: Baltimore. MD [27]&quot; , 25,
&quot;SD: San Diego. CA [28]&quot; , 25,
&quot;NV: Nashville. TN [29]&quot; , 25,
&quot;HN: Hartford &amp; New Haven. CT [30]&quot; , 25,
&quot;KC: Kansas City. MO [31]&quot; , 25,
&quot;CS: Columbus. OH [32]&quot; , 25,
&quot;SC: Salt Lake City. UT [33]&quot; , 25,
&quot;MW: Milwaukee. WI [34]&quot; , 25,
&quot;CI: Cincinnati. OH [35]&quot; , 25,
&quot;SA: San Antonio. TX [36]&quot; , 25,
&quot;GA: Grnville-Spartanburg-Asheville-Anderson. SC [37]&quot; , 25,
&quot;WP: West Palm Beach-Ft. Pierce. FL [38]&quot; , 25,
&quot;BH: Birmingham-Anniston-Tuscaloosa. AL [39]&quot; , 25,
&quot;LV: Las Vegas. NV [40]&quot; , 25,
&quot;HL: Harrisburg-Lancaster-Lebanon- York. PA [41]&quot; , 25,
&quot;GR: Grand Rapids- Kalamazoo- Battle Creek. MI [42]&quot; , 25,
&quot;NN: Norfolk- Portsmouth- Newport News. VA [43]&quot; , 25,
&quot;OC: Oklahoma City. OK [44]&quot; , 25,
&quot;AQ: Albuquerque-Santa Fe. NM [45]&quot; , 25,
&quot;WS: Greensboro-High Point-Winston Salem. NC [46]&quot; , 25,
&quot;AU: Austin. TX [47]&quot; , 25,
&quot;LU: Louisville. KY [48]&quot; , 25,
&quot;MM: Memphis. TN [49]&quot; , 25,
&quot;JV: Jacksonville. FL [50]&quot; , 25,
0)  +

IF(ISPICKVAL( Radio_Markets__c, &quot;IN: Indianapolis. IN [26]&quot; ),
25,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outside Market Fee 26 - 50</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outside_Market_Fee_51_100__c</fullName>
        <formula>CASE( US_Markets__c, 
&quot;BF: Buffalo. NY [51]&quot; , 50, 
&quot;NO: New Orleans. LA [52]&quot; , 50, 
&quot;PV: Providence. RI-New Bedford. MA [53]&quot; , 50, 
&quot;WB: Wilkes Barre-Scranton. PA [54]&quot; , 50, 
&quot;FV: Fresno-Visalia. CA [55]&quot; , 50, 
&quot;LR: Little Rock-Pine Bluff. AR [56]&quot; , 50, 
&quot;RP: Richmond-Petersburg. VA [57]&quot; , 50, 
&quot;AL: Albany-Schenectady-Troy. NY [58]&quot; , 50, 
&quot;TU: Tulsa. OK [59]&quot; , 50, 
&quot;MP: Mobile. AL-Pensacola (Ft Walton Beach). FL [60]&quot; , 50, 
&quot;KX: Knoxville. TN [61]&quot; , 50, 
&quot;FM: Ft Myers-Naples. FL [62]&quot; , 50, 
&quot;DY: Dayton. OH [63]&quot; , 50, 
&quot;LX: Lexington. KY [64]&quot; , 50, 
&quot;CN: Charleston-Huntington. WV [65]&quot; , 50, 
&quot;RL: Roanoke-Lynchburg. VA [66]&quot; , 50, 
&quot;WH: Wichita-Hutchinson. KS Plus [67]&quot; , 50, 
&quot;FL: Flint-Saginaw-Bay City. MI [68]&quot; , 50, 
&quot;GB: Green Bay-Appleton. WI [69]&quot; , 50, 
&quot;TC: Tucson. AZ [70]&quot; , 50, 
&quot;HO: Honolulu. HI [71]&quot; , 50, 
&quot;DM: Des Moines-Ames. IA [72]&quot; , 50, 
&quot;SP: Spokane. WA [73]&quot; , 50, 
&quot;TO: Toledo. OH [74]&quot; , 50, 
&quot;SG: Springfield. MO [75]&quot; , 50, 
&quot;OM: Omaha. NE [76]&quot; , 50, 
&quot;CO: Columbia. SC [77]&quot; , 50, 
&quot;PA: Portland-Auburn. ME [78]&quot; , 50, 
&quot;RO: Rochester. NY [79]&quot; , 50, 
&quot;HD: Huntsville-Decatur (Florence). AL [80]&quot; , 50, 
&quot;HV: Paducah-Cape Girardeau-Harrisbrg Mt Vernon. [81]&quot; , 50, 
&quot;CD: Champaign &amp; Springfield-Decatur. IL [82]&quot; , 50, 
&quot;SH: Shreveport. LA [83]&quot; , 50, 
&quot;SY: Syracuse. NY [84]&quot; , 50, 
&quot;MA: Madison. WI [85]&quot; , 50, 
&quot;CG: Chattanooga. TN [86]&quot; , 50, 
&quot;BW: Harlingen-Weslaco-Brownsville- McAllen. TX [87]&quot; , 50, 
&quot;WT: Waco-Temple-Bryan. TX [88]&quot; , 50, 
&quot;CW: Cedar Rapids-Waterloo-Iowa City-Dubuque. IA [89]&quot; , 50, 
&quot;CP: Colorado Springs- Pueblo. CO [90]&quot; , 50, 
&quot;EP: El Paso. TX [91]&quot; , 50, 
&quot;SV: Savannah. GA [92]&quot; , 50, 
&quot;JK: Jackson. MS [93]&quot; , 50, 
&quot;BR: Baton Rouge. LA [94]&quot; , 50, 
&quot;BP: Burlington. VT- Plattsburgh. NY [95]&quot; , 50, 
&quot;TV: Tri-Cities. TN-VA [96]&quot; , 50, 
&quot;SE: South Bend-Elkhart. IN [97]&quot; , 50, 
&quot;CT: Charleston. SC [98]&quot; , 50, 
&quot;FS: Ft Smith-Fayetteville-Springdale- Rogers. AR [100]&quot; , 50, 
&quot;RI: Davenport. IA-Rock Island-Moline. IL [100]&quot; , 50, 
0 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outside Market Fee 51 - 100</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Before_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of Inventory Item and Product Detail</inlineHelpText>
        <label>Price Before Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>This field includes the Total Price Before Fees, Discount, Total Fees, and any Account Level Discount.</inlineHelpText>
        <label>Subtotal - old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Redo_Item__c</fullName>
        <formula>IF( Opportunity__r.Redo_Item_s__c = TRUE, &quot;Yes&quot;, &quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Redo Item?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Non_Removable_Fees__c</fullName>
        <formula>BI_Translation_Fee__c +
Attribute_Costs__c +
Transcript_Translation_Fee__c +
Special_Record_Set_Up__c + 
DNA_Fee__c +
 Search_Fee__c +
 Acquisition_Fee__c +
 Royalty_Fee__c +
 Editing_Fee__c +
 Creative_Services_Fee__c +
 Transcript_Fee__c  +
Visual_Transcript_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Non-Removable Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price_Before_Fees__c</fullName>
        <formula>Market_Adjustment__c +  Price_Before_Fees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is the Total Price before fees that will display on the invoice to the client. It includes the automatically generated pricing for the Item, as well as the Market Adjustment price increase.</inlineHelpText>
        <label>Total Price Before Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Removable_Fees__c</fullName>
        <formula>IF( Exclude_Canadian_Market_Fee__c = False, Canadian_Market_Fee__c, 0) +
 IF( Exclude_Int_l_Market_Fee__c = False,  Int_l_Market_Fee__c, 0) +
 IF( Exclude_Archive_Fee__c = False, Archive_Fee__c, 0) +
 IF( Exclude_Rush_Fee__c = False, Rush_Fee__c, 0) +
 IF( Exclude_After_Hours_Fee__c = False, After_Hours_Fee__c, 0) + 
 IF(  Exclude_HD_Archive_Fee__c = False,  HD_Archive_Fee__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Removable Fees (not Add&apos;l)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zero_Clip_Package_Selected__c</fullName>
        <formula>IF( OR( Clip_Package__r.No_Clip_Package__c = TRUE,  ISPICKVAL(Opportunity__r.StageName, &quot;Voided&quot;) ), &quot;Yes&quot;, &quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zero Clip Package Selected</label>
        <type>Text</type>
    </fields>
    <label>Broadcast Item</label>
    <nameField>
        <displayFormat>BCast-{0000000000}</displayFormat>
        <label>Item Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/BroadcastItemServices.cls
/* BroadcastItemServices class
*
* 5/02/2013 - Marc Lain (Bluewolf)
* Services class for the BroadcastItem object. 
*   
*/



public with sharing class BroadcastItemServices 
{
	
	public static void addTotalFees(List<Broadcast_Item__c> broadcastItems)
	{
		//Add fees to Total Fees. 
		//Reproduce formula field below when BroadcastItem inserted/updated
		
		
		//Total_Fees__c =
		//	Total_Removable_Fees__c + 
		//	Total_Non_Removable_Fees__c+ 
		//	IF( Exclude_Outside_Market_Fee__c = False,Outside_Market_Fee_26_50__c,0) + 
		//	IF( Exclude_Outside_Market_Fee__c = False,Outside_Market_Fee_51_100__c,0) + 
		//	IF(Exclude_Outside_Market_Fee__c = False,Outside_Market_Fee_100_150__c,0) + 
		//	IF(Exclude_Outside_Market_Fee__c = False,Outside_Market_Fee_150__c,0)+ 
		//	IF( Exclude_Add_l_10_Min_Fee__c = False, Add_l_10_minutes__c, 0 ) + 
		//	Misc_Fee__c
		

		for(Broadcast_Item__c bi : broadcastItems)
		{	
			bi.Total_Fees__c = 0;
			
			//Make sure Misc_Fee__c is not null
			if(bi.Misc_Fee__c == null)
			{
				bi.Misc_Fee__c = 0;
			}
				
			bi.Total_Fees__c = 	bi.Total_Removable_Fees__c + 
								bi.Total_Non_Removable_Fees__c + 
								bi.Misc_Fee__c;
			
			if(!bi.Exclude_Outside_Market_Fee__c)
			{
				//add Outside Market Fees
				bi.Total_Fees__c += bi.Outside_Market_Fee_26_50__c +
														bi.Outside_Market_Fee_51_100__c +
														bi.Outside_Market_Fee_100_150__c + 
														bi.Outside_Market_Fee_150__c;
			}
			
			
			if(!bi.Exclude_Add_l_10_Min_Fee__c && bi.Add_l_10_minutes__c != null)
			{
				//add Add'l 10 Min Fee
				bi.Total_Fees__c += bi.Add_l_10_minutes__c;
			}
		}
		
	}
	
	public static void calculatePrice(List<Broadcast_Item__c> broadcastItems)
	{
		//List<Broadcast_Item__c> bItems = queryParentFields(broadcastItems);
		
		for(Broadcast_Item__c bi : broadcastItems)
		{
			bi.Price__c = 0;
						
			//If Redo_Item__c is equal to Yes, then zero out entire price.
			//If No, then do the calculations
			if(bi.Redo_Item__c == 'No')
			{
				bi.Price__c = bi.Total_Fees__c;
				
				//If the user selects anything other than “No Clip Package” on the Clip_Package__c,
				//then do not add Total_Price_Before_Fees__c
				if(bi.Zero_Clip_Package_Selected__c == 'Yes')
				{	
					bi.Price__c = bi.Price__c + bi.Total_Price_Before_Fees__c;
				}
				
				/*
				//If How_many_Clip_Packages_to_pay_for_Fees__c is greater than 0, the zero out Total_Fees__c.
				if(bi.How_many_Clip_Packages_to_pay_for_Fees__c == null || bi.How_many_Clip_Packages_to_pay_for_Fees__c == 0)
				{
					bi.Price__c = bi.Price__c + bi.Total_Fees__c;

				}	
				
				
				//Apply discounts
				if(bi.Account_Level_Discount__c != null)
				{
					bi.Price__c = bi.Price__c - (bi.Price__c * (bi.Account_Level_Discount__c/100));
				}
								
				if(bi.Discount__c != null)
				{
					bi.Price__c = bi.Price__c - bi.Discount__c;
				}
				*/
				
				
			}
			else
			{
				bi.Price__c = 0;
			}
			
			//Make sure Discount__c is not null
			if(bi.Discount__c == null)
			{
				bi.Discount__c = 0;
			}
			
			//Update Total Sale
			bi.Total_Sale__c = bi.Price__c - ( bi.Price__c * (bi.Account_Level_Discount__c/100) + bi.Discount__c);
		}
	}
	
	/*
	public static List<Broadcast_Item__c> queryParentFields(List<Broadcast_Item__c> broadcastItems)
	{
		Set<ID> bItemIDs = new Set<ID>();

		for(Broadcast_Item__c bi : broadcastItems)
		{
			bItemIDs.add(bi.Id);
		}
		
		List<Broadcast_Item__c> bItems = [Select Id, 
												Opportunity__r.Redo_Item_s__c,
												Clip_Package__r.No_Clip_Package__c,
												How_many_Clip_Packages_to_pay_for_Fees__c,
												Total_Fees__c,
												Total_Price_Before_Fees__c,
												Price__c
											From Broadcast_Item__c
											Where Id IN : bItemIDs];
											
		return bItems;	
	}
	*/
	
	/*
	public static void getTotalPriceBeforeFees(List<Broadcast_Item__c> broadcastItems)
	{
		
		//Total_Price_Before_Fees__c =
		//	Market_Adjustment__c + Price_Before_Fees__c

		for(Broadcast_Item__c bi : broadcastItems)
		{	
			bi.Total_Fees__c = 0;
			
			bi.Total_Price_Before_Fees__c = bi.Market_Adjustment__c + 
											bi.Price_Before_Fees__c;
		}
		
	}
	*/
	
}