CS_PROD_20150209_01/Metadata/unpackaged/objects/Broadcast_Item__c.object
<CustomObject>
    <description>This object will used to house Broadcast Items that come in and created through VisualFlow Pages.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Broadcast_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>This field includes the Total Price Before Fees, Discount, Total Fees, and any Account Level Discount.</inlineHelpText>
        <label>Subtotal - old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Update_From_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to fire Broadcast Item trigger when parent Opportunity updates Redo Item and/or parent Clip Package updates No Clip Package.</description>
        <label>Update From Parent</label>
        <type>Checkbox</type>
    </fields>
    <label>Broadcast Item</label>
    <nameField>
        <displayFormat>BCast-{0000000000}</displayFormat>
        <label>Item Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Redo_Item_s__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Redo Opportunities</inlineHelpText>
        <label>Redo Item(s)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/OpportunityServices.cls
public with sharing class OpportunityServices 
{
   	public static boolean runTrigger = true;
   	
    public static void updateBroadcastItems(List<Opportunity> newOpportunities, Map<ID, Opportunity> oldOpportunities)
	{
		List<Opportunity> opportunitiesToProcess = getOpportunitiesToProcess(newOpportunities, oldOpportunities);
    
    	Set<ID> oppIds = new Set<ID>();
	    
	    for(Opportunity opp : opportunitiesToProcess)
	    {
	            oppIds.add(opp.Id);
	    }
	    
	    List<Opportunity> updatedOpps = [SELECT Id, Redo_Item_s__c, (Select Id, Price__c, Update_From_Parent__c from Broadcast_Orders__r)  FROM Opportunity WHERE Id IN :oppIds];
	 
	    List<Broadcast_Item__c> broadcastItems = new List<Broadcast_Item__c>();
	    
	    for (Opportunity opp : updatedOpps)
	    {
	    	
	        // Loop through each BroadcastItem record
	        for(Broadcast_Item__c bi : opp.Broadcast_Orders__r)
	        {
	            bi.Update_From_Parent__c = (!bi.Update_From_Parent__c);
	            System.debug('SERVICES Update From Parent ' + bi.Update_From_Parent__c);
	            broadcastItems.add(bi);
	        }
	        
	    }
	    
	    //update Broadcast Items
	    try
        {
            Database.update(broadcastItems);
        }
        catch (System.DmlException e) 
        {
            for (Integer i = 0; i < e.getNumDml(); i++) 
            {
        		System.debug(e.getDmlMessage(i));
            }
        }
        
 	}
 	
 	
 	public static List<Opportunity> getOpportunitiesToProcess(List<Opportunity> newOpportunities, Map<ID, Opportunity> oldOpportunities)
 	{
 		List<Opportunity> opportunitiesToProcess = new List<Opportunity>();
 		
 		//Only process those Opportunities where the field Redo_Item_s__c has been updated
 		//or StageName has been changed to Opp Voided
 		
 		for (Opportunity o : newOpportunities) 
 		{
        	Opportunity oldOppty = oldOpportunities.get(o.ID);
        	if ( (o.Redo_Item_s__c != oldOppty.Redo_Item_s__c) || (oldOppty.StageName != 'Opp Voided' && o.StageName == 'Opp Voided'))
        	{
            	opportunitiesToProcess.add(o);
        	}
    	}
    	
    	return opportunitiesToProcess;
 	}
 	
 	/*
 	public static void setRunTriggerToFalse()
 	{
 		runTrigger = false;
 	}
 	
 	public static void setRunTriggerToTrue()
 	{
 		runTrigger = true;
 	}
 	*/

}