CS_PROD_20150209_01/Metadata/unpackaged/objects/Broadcast_Item__c.object
<CustomObject>
    <description>This object will used to house Broadcast Items that come in and created through VisualFlow Pages.</description>
    <fields>
        <fullName>Update_From_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to fire Broadcast Item trigger when parent Opportunity updates Redo Item and/or parent Clip Package updates No Clip Package.</description>
        <label>Update From Parent</label>
        <type>Checkbox</type>
    </fields>
    <label>Broadcast Item</label>
    <nameField>
        <displayFormat>BCast-{0000000000}</displayFormat>
        <label>Item Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Invoice_Contact_Email__c</fullName>
        <inlineHelpText>Please input the email address for the Invoice Contact above.</inlineHelpText>
        <label>Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact_Name__c</fullName>
        <label>Invoice Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redo_Item_s__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Redo Opportunities</inlineHelpText>
        <label>Redo Item(s)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Redo_Reasons__c</fullName>
        <label>Redo Reasons</label>
        <picklist>
            <picklistValues>
                <fullName>Cision error - AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cision error - Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client error - Manager Comp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client error - Format</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Prepaid_Clip_Package__c.object
<CustomObject>
    <description>Used to track Accounts who have purchased Prepaid Clip Packages, and then track how many are remaining after a client makes a purchase.</description>
    <label>Clip Package</label>
    <nameField>
        <label>Clip Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clip Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestOpportunityServices.cls
@isTest (seeAllData = true) 
public with sharing class TestOpportunityServices 
{
	
    static testMethod void testUpdateBroadcastItems()
    {
    	Account acc = new Account();
    	acc.Name = 'Test';
	    acc.BillingStreet = '123 Main St';
		acc.BillingCity = 'Chicago';
		acc.BillingState = 'IL';
		acc.BillingPostalCode = '60603';
    	acc.BillingCountry = 'USA';
	   	insert acc;	   	
	   	
	   	Opportunity opp = TestingUtils.createOpportunity(acc.Id);
    	opp.Invoice_Contact_Name__c = 'John';
    	opp.Invoice_Contact_Email__c = 'john@email.com';
    	opp.Redo_Item_s__c = false;
    	insert opp;
    	
    	Prepaid_Clip_Package__c cp = TestingUtils.createClipPackage(opp.AccountId, TestingUtils.ADMIN_USER.Id, 'DVD Clip', false );
    	insert cp;
    	
        Broadcast_Item__c bItem = TestingUtils.createBroadcastItem(opp.Id, cp.Id, false);
        bItem.Update_From_Parent__c = false;
        insert bItem;
        
        //Update Redo_Item_s__c should update Update_From_Parent__c
        opp.Redo_Item_s__c = true;
        opp.Redo_Reasons__c = 'Cision error - AE';
        Test.startTest();
        update opp;
        Test.stopTest();
        
        bItem = [Select Id, Update_From_Parent__c
        			From Broadcast_Item__c
        			Where Id = :bItem.Id];
       	
       	//System.assertEquals(false, bItem.Update_From_Parent__c); 			
    }
}