CS_PROD_20150209_01/Metadata/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <description>Added by LM on 2/6/2014 for Phase2 Rollout.</description>
        <label>Actual</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Affected_CP_ID__c</fullName>
        <description>Created by LM on 2/6/2014 for Phase2</description>
        <label>Affected CP ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BAC__c</fullName>
        <description>Created by LM on 8/27/2013 for Phase 2 rollout</description>
        <label>BAC #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CisionPoint_Username__c</fullName>
        <description>Created by LM on 8/27/2013 for Phase 2 rollout</description>
        <label>CisionPoint Username</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected__c</fullName>
        <description>Added by LM on 2/6/2014 for Phase2 Rollout.</description>
        <label>Expected</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Jira_Number__c</fullName>
        <description>Created by LM on 8/27/2013 for Phase 2 rollout</description>
        <label>Jira Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Users_Affected__c</fullName>
        <description>Created by LM on 8/27/2013 for Phase 2 rollout</description>
        <label>Number of Users Affected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Search_Terms__c</fullName>
        <description>Created by LM on 8/27/2013 for Phase 2 rollout</description>
        <label>Search Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Desk_Ticket_Number__c</fullName>
        <description>Created by LM on 8/27/2013 for Phase 2 rollout</description>
        <label>Service Desk Ticket Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Steps_to_Reproduce__c</fullName>
        <description>Added by LM on 2/6/2014 for Phase2 Rollout.</description>
        <label>Steps to Reproduce</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Upset_Client_Notes__c</fullName>
        <description>Created by LM on 8/27/2013 for Phase 2 rollout</description>
        <label>Upset Client Notes</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Contract_Admin_Request</fullName>
        <active>true</active>
        <businessProcess>Client Services</businessProcess>
        <label>Contract Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <businessProcess>Client Services</businessProcess>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Round_Robin__c.object
<CustomObject>
    <description>This Object stores details to be used in all the Round Robin allocation processes</description>
    <fields>
        <fullName>Assign_Records__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Specifies whether records should be assigned to the user referenced by this rule. Allows for users to temporarily be taken out of the round robin processing</description>
        <label>Assign Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Dependent on the Object type pick list this determines the Group that this rule belongs to</description>
        <label>Group</label>
        <picklist>
            <controllingField>Object_Type__c</controllingField>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OnSite/Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Marketing New Biz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (Broadcast Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Biz (International Response)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was this the last Round Robin record to be allocated a Record</description>
        <label>Last Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Records_Assigned__c</fullName>
        <description>Shows the total number of records assigned</description>
        <label>Number of Records Assigned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>The type of Object to apply this rule to</description>
        <label>Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Print Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Open_Opps__c</fullName>
        <label>Open Opps</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Store_Stats__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Should a log be kept of all records allocated to this User</description>
        <label>Store Stats</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <label>Sub Group</label>
        <picklist>
            <controllingField>Group__c</controllingField>
            <picklistValues>
                <fullName>BASIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLIENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Small Business Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PitchEngine Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BROADCAST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the user who should be assigned a Record</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestCaseSupportExtension.cls
@isTest 
private class TestCaseSupportExtension 
{
    static testMethod void TestDCSCaseSupport() 
    {
		TestLibrary.InitAvaTax();
        List<Account> accounts = TestingUtils.createAccounts(1, true);      
        Account a = accounts.get(0);
		
        Opportunity opp = TestingUtils.createOpportunity(a.Id);
        insert opp;
        
		String caseCType = 'Broadcast Issues';
		
		List<Case> cases = TestingUtils.createCase(1, a.Id, opp.Id, caseCType);        
        Case c = cases.get(0);
		insert c;		        
        
		//RecordType rt = [SELECT Id, Name from RecordType where Name= 'DCS Broadcast Issues'];
		RecordType rt = UtilityClass.GetRecordType('DCS Broadcast Issues');
		
		Test.startTest();		
		
        PageReference pageRef = Page.CaseSupport;
        pageRef.GetParameters().put('aid', a.Id);
        pageRef.GetParameters().put('oid', opp.Id);
		pageRef.GetParameters().put('rtId', rt.Id);
        pageRef.GetParameters().put('cid', c.Id);
		
        Test.setCurrentPage(pageRef);                   
		
        ApexPages.StandardController controller = new ApexPages.StandardController(c); 
        CaseSupportExtension extension = new CaseSupportExtension(controller);      
       	extension.cs = (Case)controller.getRecord(); 
		SaveCaseInfo(extension.cs);
        extension.Save();   
		
        Test.stopTest();
    }
    
    static testMethod void TestSalesSupportCaseSupport() 
    {
		TestingUtils.InitAvaTax();
        List<Account> accounts = TestingUtils.createAccounts(1, true);      
        Account a = accounts.get(0);
		
        Opportunity opp = TestingUtils.createOpportunity(a.Id);
        insert opp;
        
		String caseCType = 'Broadcast Quote';
				
		Case c = new Case();
        
		//RecordType rt = [SELECT Id, Name from RecordType where Name= 'Sales Support Broadcast Quote'];
		RecordType rt = UtilityClass.GetRecordType('Sales Support Broadcast Quote');
		
		Test.startTest();		
		
        PageReference pageRef = Page.CaseSupport;
        pageRef.GetParameters().put('aid', a.Id);
        pageRef.GetParameters().put('oid', opp.Id);
		pageRef.GetParameters().put('rtId', rt.Id);        
		
        Test.setCurrentPage(pageRef);                   
		
        ApexPages.StandardController controller = new ApexPages.StandardController(c); 
        CaseSupportExtension extension = new CaseSupportExtension(controller);              
		extension.cs.Type = caseCType;
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();	
		extension.cs.Type = 'Pub Check';
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();
		extension.cs.Type = 'RFP';
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();
		extension.cs.Type = 'Extension Request';
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();
		extension.cs.Type = 'Trials';
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();
		SaveCaseInfo(extension.cs);
		extension.caseAttachment = null;
        extension.Save();   
		
        Test.stopTest();
    }
	
	static testMethod void TestTraining() 
    {
		TestingUtils.InitAvaTax();
        List<Account> accounts = TestingUtils.createAccounts(1, true);      
        Account a = accounts.get(0);
		
        Opportunity opp = TestingUtils.createOpportunity(a.Id);
        insert opp;
        
		String caseCType = 'Internal Training Request';
				
		List<Case> cases = TestingUtils.createCase(1, a.Id, opp.Id, caseCType);        
        Case c = cases.get(0);
		insert c;		
        
		Id rtId = TestingUtils.getRecordTypeId('Case', 'Training');		
		
		Test.startTest();		
		
        PageReference pageRef = Page.CaseSupport;
        pageRef.GetParameters().put('aid', a.Id);
        pageRef.GetParameters().put('oid', opp.Id);
		pageRef.GetParameters().put('rtId', rtId);
        pageRef.GetParameters().put('cid', c.Id);
		
        Test.setCurrentPage(pageRef);                   
		
        ApexPages.StandardController controller = new ApexPages.StandardController(c); 
        CaseSupportExtension extension = new CaseSupportExtension(controller);              
		extension.cs.Type = caseCType;
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();	
		extension.cs.Type = 'Training';
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();
		SaveCaseInfo(extension.cs);
		extension.caseAttachment = null; 		
        extension.Save();   
		
        Test.stopTest();
    }
	
	static testMethod void TestContractAdmin() 
    {
		TestingUtils.InitAvaTax();				
		User user1 = TestingUtils.createUser('CaUser1', TestingUtils.TEST_PROFILE_ID);
		user1.Email = 'Test@Cisionus.com';
		insert user1;		
		
		Round_Robin__c rr1 = new Round_Robin__c(User__c=user1.Id,Object_Type__c='Case',Group__c='Contract Admin',Sub_Group__c='',Assign_Records__c=true,Number_of_Records_Assigned__c=0,Last_Allocated__c=true,Store_Stats__c=true,Open_Opps__c=0);
		insert rr1;
		
        List<Account> accounts = TestingUtils.createAccounts(1, true);      
        Account a = accounts.get(0);
		
        Opportunity opp = TestingUtils.createOpportunity(a.Id);
        insert opp;
        
		String caseCType = 'Contract Admin';
				
		List<Case> cases = TestingUtils.createCase(1, a.Id, opp.Id, caseCType);        
        Case c = cases.get(0);
		insert c;		
        
		//Id rtId = TestingUtils.getRecordTypeId('Case', 'Contract_Admin_Request');
		RecordType rt = UtilityClass.GetRecordType('Contract Admin');
		
		Test.startTest();		
		
        PageReference pageRef = Page.CaseSupport;
        pageRef.GetParameters().put('aid', a.Id);
        pageRef.GetParameters().put('oid', opp.Id);
		pageRef.GetParameters().put('rtId', rt.Id);
        pageRef.GetParameters().put('cid', c.Id);
		
        Test.setCurrentPage(pageRef);                   
		
        ApexPages.StandardController controller = new ApexPages.StandardController(c); 
        CaseSupportExtension extension = new CaseSupportExtension(controller);              
		extension.cs.Type = caseCType;
		extension.cs = (Case)controller.getRecord();        
        extension.GetCaseFieldSet();			
		SaveCaseInfo(extension.cs);
		extension.caseAttachment = null;
        extension.Save();   
		
        Test.stopTest();
	}
	
	static void SaveCaseInfo(Case cs)
	{
		cs.Search_Terms__c = 'Test Terms';
		cs.Description = 'Test Description';
		cs.Subject = 'Test Subject';
		//extension.cs.ContactPhone = '1234567890';
		cs.Service_Desk_Ticket_Number__c = '1234';
		cs.Affected_CP_ID__c = '12345';
		cs.CisionPoint_Username__c = 'TestUser';
		cs.Number_of_Users_Affected__c = 1;
		cs.BAC__c = 'Test BAC';
		cs.Steps_to_Reproduce__c = 'Test Steps to Reproduce';
		cs.Expected__c = 'Test Expected';
		cs.Actual__c = 'Test Actual';
		cs.Jira_Number__c = 'Test Jira #';
		cs.Upset_Client_Notes__c = 'Test Upset Client Notes';
	}
}