CS_PROD_20150209_01/Metadata/unpackaged/objects/Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitive_Spend__c</fullName>
        <description>Added by LM on 3/15/2013; New for SFDC rollout</description>
        <label>Competitive Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <label>Competitor Name</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gorkana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus/PRWeb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 9/4/2013 for Phase 2 rollout</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Provided__c</fullName>
        <label>Service Provided</label>
        <picklist>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <description>Added by MD 09/13/2012. A Field to hold the name of the Competitor that the Sale was Lost to or Stolen from</description>
        <inlineHelpText>A Competitor Name must be selected when Closing an Opportunity and the Close Reason is &quot;Competitor&quot;</inlineHelpText>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurrellesLuce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Won&apos;t Say/Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Mention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dow Jones Factiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlobeNewswire/NASDAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoogleNews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketwired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meltwater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyMediaInfo (MMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Newswire (Agility)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radian6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sysomos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TVEyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vocus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact_Email__c</fullName>
        <inlineHelpText>Please input the email address for the Invoice Contact above.</inlineHelpText>
        <label>Invoice Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact_Name__c</fullName>
        <label>Invoice Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redo_Item_s__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Redo Opportunities</inlineHelpText>
        <label>Redo Item(s)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestCompetitorTrigger.cls
@isTest
private class TestCompetitorTrigger
{
	static testMethod void CompetitorTriggerTest()
	{
		TestLibrary.InitAvaTax();
		
		User u = TestLibrary.createUser ('Test', TestLibrary.STANDARD_USER_PROFILE);
        insert u;
		
		Account acc = TestLibrary.CreateAccount('Test Account', u.Id);  
		insert acc;
		
		Opportunity opp = TestLibrary.CreateOpportunity('Test', u.Id, acc.Id);   	
	   	opp.Invoice_Contact_Name__c = 'Mark';
    	opp.Invoice_Contact_Email__c = 'mark.doggett@cision.com';
    	opp.Redo_Item_s__c = false;
    	insert opp;
		
		Test.startTest();
		
		Competitor__c comp = new Competitor__c(Account__c = acc.Id, Opportunity__c = opp.Id, Competitive_Spend__c = 10000, Competitor_Name__c = 'Biz360');
		insert comp;
		delete comp;
		
		comp = new Competitor__c(Account__c = acc.Id, Opportunity__c = opp.Id, Competitive_Spend__c = 10000, Service_Provided__c = 'Plan;Connect');
		insert comp;
		
		Test.stopTest();
		
		List<Competitor__c> compList = [Select Id from Competitor__c];
		System.debug('Competitor Size == ' + compList.size());
		System.Assert(compList.size() == 1);
	}
}