CS_PROD_20150209_01/Metadata/unpackaged/objects/Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 9/4/2013 for Phase 2 rollout</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/classes/CompetitorAfterDeleteTriggerHandler.cls
public with sharing class CompetitorAfterDeleteTriggerHandler extends TriggerHandlerBase
{
	public override void mainEntry(TriggerParameters tp)
	{
		CompetitorHelper helper = new CompetitorHelper((List<Competitor__c>)tp.oldList);
	
		for(Competitor__c comp : (List<Competitor__c>)tp.oldList)
		{
			helper.UpdateAccountCompetitorField(comp.Account__c);
			helper.UpdateOpportunityCompetitorField(comp.Opportunity__c);
        }
		
		if (helper.oppsMap != null)
		{
			sObjectsToUpdate.putAll((Map<ID, Sobject>)helper.oppsMap);
		}
		
		if (helper.accountsMap != null)
		{
			sObjectsToUpdate.putAll((Map<ID, Sobject>)helper.accountsMap);
		}
	}
}