CS_PROD_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates this contract as the master contract for this account. Upon renewal all contracts will be rolled into this contract.</description>
        <inlineHelpText>Designates this contract as the master contract for this account. Upon renewal all contracts will be rolled into this contract.</inlineHelpText>
        <label>Master Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote that generated this contract.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer account. Defaulted on create from the opportunity.</description>
        <inlineHelpText>Customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master contract with which subscription products in this quote are to be co-terminated.</description>
        <inlineHelpText>Master contract with which subscription products in this quote are to be co-terminated.</inlineHelpText>
        <label>Master Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Co-Terminated Quotes</relationshipLabel>
        <relationshipName>CoTerminatedQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds the Opportunity of the Quote</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines (Original Quote)</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/SBQQQuoteHelper.cls
public with sharing class SBQQQuoteHelper
{
	public static void UpdateQuoteLines(List<SBQQ__Quote__c> quotesList)
	{
		List<SBQQ__QuoteLine__c> quoteLinesList = [Select Id, SBQQ__Quote__c, Original_Quote__c, Opportunity__c, SBQQ__Quote__r.SBQQ__MasterContract__r.SBQQ__Quote__c from SBQQ__QuoteLine__c where SBQQ__Quote__c in :quotesList];
		Map<Id, List<SBQQ__QuoteLine__c>> quoteLinesMap = new Map<Id, List<SBQQ__QuoteLine__c>>();
		for (SBQQ__QuoteLine__c ql : quoteLinesList)
		{
			if (quoteLinesMap.containsKey(ql.SBQQ__Quote__c))
			{
				quoteLinesMap.get(ql.SBQQ__Quote__c).add(ql);
			}
			else
			{
				List<SBQQ__QuoteLine__c> tempList = new List<SBQQ__QuoteLine__c>();
				tempList.add(ql);
				quoteLinesMap.put(ql.SBQQ__Quote__c, tempList);
			}
		}
		
		for (SBQQ__Quote__c q : quotesList)
		{
			// Get the associated Quote Lines
			List<SBQQ__QuoteLine__c> qlList = quoteLinesMap.get(q.Id);
			
			if (qlList != null)
			{
				List<SBQQ__QuoteLine__c> linesToUpdate = new List<SBQQ__QuoteLine__c>();
				Boolean needsUpdate = false;
				
				for (SBQQ__QuoteLine__c ql : qlList)
				{
					if (ql.Opportunity__c != q.SBQQ__Opportunity__c)
					{
						ql.Opportunity__c = q.SBQQ__Opportunity__c;
						needsUpdate = true;
					}
					
					if (ql.SBQQ__Quote__c != null && ql.SBQQ__Quote__r.SBQQ__MasterContract__c != null && ql.Original_Quote__c != ql.SBQQ__Quote__r.SBQQ__MasterContract__r.SBQQ__Quote__c)
					{
						ql.Original_Quote__c = ql.SBQQ__Quote__r.SBQQ__MasterContract__r.SBQQ__Quote__c;
						needsUpdate = true;
					}
					
					if (needsUpdate)
					{
						linesToUpdate.add(ql);
					}
				}
				
				update linesToUpdate;
			}
		}
	}
	
	public static void AreAccountsDifferent(List<SBQQ__Quote__c> quotesList)
	{
		// Check if the Account against the Master Contract and the Acocunt Directly related to the Quote are different
		Set<Id> contractIds = new Set<Id>();
		for (SBQQ__Quote__c q : quotesList)
		{
			if (q.SBQQ__MasterContract__c != null)
			{
				contractIds.add(q.SBQQ__MasterContract__c);
			}
		}
			
		Map<Id, Contract> masterContractMap = new Map<Id, Contract>([Select Id, AccountId from Contract where Id in :contractIds]);
		
		for (SBQQ__Quote__c q : quotesList)
		{
			if (q.SBQQ__MasterContract__c != null)
			{
				Contract c = masterContractMap.get(q.SBQQ__MasterContract__c);
			
				if (c != null)
				{
					if (c.AccountId != q.SBQQ__Account__c)
					{
						q.addError('The Master Contract on this Quote does not belong to the Account on this Quote.  Please choose a different Master Contract.');
					}
				}
			}
		}
	}
	
	
	
}