CS_PROD_20150209_01/Metadata/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote that generated this contract.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Docusign_Envelope_Id__c</fullName>
        <externalId>true</externalId>
        <label>Docusign Envelope Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docusign_Status__c</fullName>
        <description>Stores to Docusign Status</description>
        <label>Docusign Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Bypass_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a System Admin Attribute that for certain circumstances, we can bypass Validation when Deploying.</description>
        <inlineHelpText>This is a System Admin Attribute that for certain circumstances, we can bypass Validation when Deploying.</inlineHelpText>
        <label>Bypass Validation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/UnlockQuoteExtension.cls
public class UnlockQuoteExtension
{
	public SBQQ__Quote__c q {get; set;}
	
	private Opportunity opp;
			
	public UnlockQuoteExtension(ApexPages.StandardController controller) 
    {
    	// Get the Opp Record
    	q = (SBQQ__Quote__c)controller.getRecord();
    	    	
    	if (q != null)
    	{
    		q = [Select Id, Name, SBQQ__Status__c, SBQQ__Opportunity__c from SBQQ__Quote__c where Id = :q.Id];
    		opp = [Select Id, StageName from Opportunity where Id = :q.SBQQ__Opportunity__c];
		}
    }
	
	public PageReference UnlockQuote()
	{
		Boolean updateRecords = false;
					
		// First think is to try and revoke the Approval
		if (opp.StageName == 'APP: Pending Approval')
		{
			List<ProcessInstanceWorkItem> workItemList = [Select p.ProcessInstance.Status, p.ProcessInstance.TargetObjectId,p.ProcessInstanceId,p.OriginalActorId,p.Id,p.ActorId
        		From ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId = :q.Id];
			
			if (workItemList != null && workItemList.size() > 0)
			{
				Approval.ProcessWorkitemRequest PWR = new Approval.ProcessWorkitemRequest();
				PWR.setComments('Removed by Request from ' + UserInfo.getName());
				PWR.setAction('Removed');
				PWR.setWorkitemId(workItemList[0].Id);
				Approval.process(PWR);
			}
			
			updateRecords = true;
		}
		
		if (opp.StageName == 'APP: Rejected' || opp.StageName == 'APP: Approved' ||  opp.StageName == 'CA: Review' ||  opp.StageName == 'CA: Rejected')
		{
			updateRecords = true;	
		}
		else if (opp.StageName == 'Contract Sent' || opp.StageName == 'Cust: Contract Opened' || opp.StageName == 'Cust: Contract Signed' || opp.StageName == 'Cust: Contract Rejected')
		{
			q.Docusign_Envelope_Id__c = '';
			q.Docusign_Status__c = '';
			updateRecords = true;	
		}
		
		if (updateRecords)
		{
			User u = [Select Id, Bypass_Validation__c from User where Id = :UserInfo.getUserId()];
			u.Bypass_Validation__c = true;
			update u;
			
			opp.StageName = 'In Negotiation';
			update opp;
			
			q.SBQQ__Status__c = 'Draft';
			update q;
			
			u.Bypass_Validation__c = false;
			update u;
		}
		
		return null;
	}

}