CS_PROD_20150209_01/Metadata/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Last_Years_Quantity__c</fullName>
        <label>Last Years Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Years_Sales_Price__c</fullName>
        <label>Last Years Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Last_Years_Quantity__c</fullName>
        <label>Last Years Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Years_Sales_Price__c</fullName>
        <label>Last Years Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds the Opportunity of the Quote</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_with_Uplift__c</fullName>
        <formula>IF(ISBLANK( Last_Years_Sales_Price__c ), null, Last_Years_Sales_Price__c + ((Last_Years_Sales_Price__c  / 100) * 5))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price with Uplift</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/SBQQQuoteLineHelper.cls
public with sharing class SBQQQuoteLineHelper
{	
		
	public static void AssignLastYearsSalesPriceToQuoteLine(List<SBQQ__QuoteLine__c> quoteLines)
	{
		Set<Id> oppIds = new Set<Id>();
		Set<Id> productIds = new Set<Id>();
		Set<Id> quoteIds = new Set<Id>();
		
		for (SBQQ__QuoteLine__c line : quoteLines)
		{
			if (line.SBQQ__Quote__c != null)
			{
				quoteIds.add(line.SBQQ__Quote__c);
			}
			
			if (line.SBQQ__Product__c != null)
			{
				productIds.add(line.SBQQ__Product__c);
			}
		}
			
		List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__Opportunity__c from SBQQ__Quote__c where Id in :quoteIds];
		for (SBQQ__Quote__c q : quoteList)
		{
			if (q.SBQQ__Opportunity__c != null)
			{
				oppIds.add(q.SBQQ__Opportunity__c);
			}
		}
		
		Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([Select Id, (Select Id, ListPrice, ProductCode, Last_Years_Sales_Price__c, Last_Years_Quantity__c from OpportunityLineItems) from Opportunity where Id in :oppIds]);
		Map<Id, product2> productMap = new Map<Id, product2>([Select Id, ProductCode from Product2 where Id in :productIds]);
						
		for (SBQQ__QuoteLine__c line : quoteLines)
		{
			System.debug('########################IN Quote LINE');
			Opportunity opp = opportunityMap.get(line.Opportunity__c);
			Product2 p = productMap.get(line.SBQQ__Product__c);
			
			if (opp != null)
			{
				line.Opportunity__c = opp.Id;	
			}
			
			if (opp != null && p != null && opp.OpportunityLineItems != null)
			{
				System.debug('########################Got Opp');
				for (OpportunityLineItem oppLineItem : opp.OpportunityLineItems)
				{
					if (oppLineItem.ProductCode == p.ProductCode)
					{
						System.debug('########################Found Line Item');
						line.Last_Years_Sales_Price__c = oppLineItem.Last_Years_Sales_Price__c;
						line.Last_Years_Quantity__c = oppLineItem.Last_Years_Quantity__c;
						line.SBQQ__Quantity__c = oppLineItem.Quantity;
						System.debug('#####################################Last Years SP = ' + line.Last_Years_Sales_Price__c);
						System.debug('#####################################Last Years SP = ' + line.Last_Years_Quantity__c);
						System.debug('#####################################Uplift = ' + line.Price_With_Uplift__c);
						break;
					}
				}
			}
		}
	}
}