CS_PROD_20150209_01/Metadata/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CA_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by LM on 12/3/2013 for Phase 2 rollout</description>
        <label>CA Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/Round_Robin__c.object
<CustomObject>
    <description>This Object stores details to be used in all the Round Robin allocation processes</description>
    <fields>
        <fullName>Assign_Records__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Specifies whether records should be assigned to the user referenced by this rule. Allows for users to temporarily be taken out of the round robin processing</description>
        <label>Assign Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the user who should be assigned a Record</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>CA_Rep__c</fullName>
        <description>Created by LM on 1/30/2014 for Phase2 Rollout</description>
        <label>CA Rep</label>
        <relationshipName>CA_Rep</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/UserAfterUpdateTriggerHandler.cls
public class UserAfterUpdateTriggerHandler extends TriggerHandlerBase
{
	public override void mainEntry(TriggerParameters tp)
	{
		for (User u : (List<User>)tp.newList)
		{	
			// Get the old user
			User oldUser = (User)tp.oldMap.get(u.Id);
			
			if (oldUser.CA_Rep__c != u.CA_Rep__c)
			{
				ChangeCAForUser(u.Id);
			}
			
			if (oldUser.IsActive && !u.IsActive)
			{
				RemoveUserFromRoundRobin(u.Id);
			}
			
		}
	}
	
	@future
	public static void RemoveUserFromRoundRobin(Id userId)
	{
		// Get all the round robin record relating to this user
		List<Round_Robin__c> rrList = [Select Id, Assign_Records__c from Round_Robin__c where User__c = :userId];
	
		if (rrList != null)
		{
			for (Round_Robin__c rr : rrList)
			{
				rr.Assign_Records__c = false;
			}
		}
		
		update rrList;
	}
	
	@future
	public static void ChangeCAForUser(Id userId)
	{
		List<Opportunity> oppsList = [select Id, OwnerId, CA_Rep__c from Opportunity where OwnerId = :userId and IsClosed = false];
		User u = [Select Id, CA_Rep__c from User where Id = :userId];
		List<Opportunity> oppsToUpdate = new List<Opportunity>();
		
		for (Opportunity o : oppsList)
		{
			if (o.CA_Rep__c != u.CA_Rep__c)
			{
				o.CA_Rep__c = u.CA_Rep__c;
				oppsToUpdate.add(o);
			}
		}
		
		update oppsToUpdate;
	}
}