CS_PROD_20150209_01/Metadata/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_SBOX_20150209_01/Metadata/unpackaged/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TestTestLibrary.cls
@isTest
private class TestTestLibrary
{
	static testMethod void TestLibraryMethods()
	{
		TestLibrary.InitAvaTax();
		
		Id su = TestLibrary.STANDARD_USER_PROFILE;
		id sa = TestLibrary.SYSTEM_ADMIN_USER_PROFILE;
		Id bt = TestLibrary.BROADCAST_TRANSACTION_PROFILE;
		Id nb = TestLibrary.NEW_BIZ_PROFILE;
		Id m = TestLibrary.MARKETING_PROFILE;
	
		Id tcs = TestLibrary.TASK_CLIENT_SERVICES_RECORD_TYPE;	
		Id nbrt = TestLibrary.OPPORTUNITY_NEW_BIZ_RECORD_TYPE;
		Id rrt = TestLibrary.OPPORTUNITY_RENEWALS_RECORD_TYPE;
	
		Id sau = TestLibrary.SFDC_ADMIN_USER;
		
		List<User> usersList = TestLibrary.CreateUsers('Test', TestLibrary.STANDARD_USER_PROFILE,  1);
		insert usersList;
		
		List<Account> accList = TestLibrary.CreateAccounts('Test', usersList[0].Id, 1);
		insert accList;
		
		List<Contact> contList = TestLibrary.CreateContacts('Test', 'test@cisionca.com', usersList[0].Id, accList[0].Id, 1);
		insert contList;
					
		List<Opportunity> oppList = TestLibrary.CreateOpportunities('Test', usersList[0].Id, accList[0].Id, 1);
		insert oppList;
		
		List<OpportunityLineItem> liList = TestLibrary.CreateOpportunityLineItems('111', oppList[0].Id, 1);
		
		List<Campaign> campList = TestLibrary.CreateCampaigns('Test', usersList[0].Id, 1);
		
		List<Product2> prodList = TestLibrary.createProducts('Test', 'Test', 'Test', 1);
		insert prodList;
		
		List<OpportunityLineItem> liList2 = TestLibrary.CreateOpportunityLineItems(prodList[0].Id, oppList[0].Id, 1);
		
		System.Debug('Inserting Quote. Acc Id = ' + accList[0].Id + ' Opp Id = ' + oppList[0].Id);
		List<SBQQ__Quote__c> quoteList = TestLibrary.CreateQuotes(accList[0].Id, oppList[0].Id, 1);
		//insert quoteList;
		
		//List<SBQQ__QuoteLine__c> quoteLineList = TestLibrary.createQuoteLines(quoteList[0].Id, prodList[0].Id, 1);
		//insert quoteLineList;
		
		List<Case> caseList = TestLibrary.createCases('Test', accList[0].Id, 1);
				
		List<Task> taskList = TestLibrary.CreateTasks('Test', 'Test', 'Test', 1);
		
	}
}