CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/OCRHelper.cls
public with sharing class OCRHelper
{
	public static List<SObject> objectsToUpdate = new List<SObject>();
	
	public static void SetPrimaryContactForQuote(List<OpportunityContactRole> ocrList)
	{
		Set<Id> oppIds = new Set<Id>();
		for (OpportunityContactRole ocr : ocrList)
		{
			if (ocr.IsPrimary)
			{
				oppIds.add(ocr.OpportunityId);
			}
		}
		
		List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__PrimaryContact__c, SBQQ__Opportunity__c from SBQQ__Quote__c where SBQQ__Opportunity__c in :oppIds];
		Map<Id, List<SBQQ__Quote__c>> quoteMap = new Map<Id, List<SBQQ__Quote__c>>();
		for (SBQQ__Quote__c q : quoteList)
		{
			if (quoteMap.containsKey(q.SBQQ__Opportunity__c))
			{
				quoteMap.get(q.SBQQ__Opportunity__c).add(q);
			}
			else
			{
				List<SBQQ__Quote__c> tempList = new List<SBQQ__Quote__c>();
				tempList.add(q);
				quoteMap.put(q.SBQQ__Opportunity__c, tempList);
			}
		}
				
		for (OpportunityContactRole ocr : ocrList)
		{
			if (ocr.IsPrimary)
			{
				// Get all quotes linked to the Opp of this OCR
				List<SBQQ__Quote__c> qList = quoteMap.get(ocr.OpportunityId);
				
				if (qList != null)
				{
					for (SBQQ__Quote__c q : qList)
					{
						q.SBQQ__PrimaryContact__c = ocr.ContactId;
						objectsToUpdate.add(q);
					}
				}
			}
		}
	}
}