CS_PROD_20150209_01/Metadata/unpackaged/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <description>Opportunity being quoted.</description>
        <inlineHelpText>Opportunity being quoted.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS_PROD_20150209_01/Metadata/unpackaged/classes/TaskBeforeUpdateTriggerHandler.cls
public with sharing class TaskBeforeUpdateTriggerHandler extends TriggerHandlerBase
{
	public override void mainEntry(TriggerParameters tp)
	{
		TaskHelper helper = new TaskHelper((List<Task>)tp.newList);
		List<Id> accountIds = new List<Id>();
		List<Id> oppIds = new List<Id>();
		Id objId = null;
		helper.UpdateSalesPersonAndState();		
		
		for (Task t : (List<Task>)tp.newList)
		{			
			//Check for account
			System.debug('################# WhatId = ' + t.WhatId);
			System.debug('################# WhoId = ' + t.WhoId);
			System.debug('################# AccountId = ' + t.AccountId);
			objId = t.WhatId;
			
			if(t.AccountId != null)
			{				
				accountIds.Add(t.AccountId);			
			}	
			
			if(objId != null)
			{
				if(string.valueOf(objId).startsWith('006'))
				{
					oppIds.add(objId);					
				}
				else if(string.valueOf(objId).startsWith('a0q'))
				{
					SBQQ__Quote__c q = UtilityClass.GetQuote(objId);
					System.debug('################# = ' + q);
					oppIds.add(q.SBQQ__Opportunity__c);
				}
			}
		}
		
		AccountHelper.UpdateSalesLastTouchedDate(accountIds);
		//OpportunityHelper.UpdateSalesLastTouchedDate(oppIds);
	}
}